
precompilation:
---------------

asset 103 reflexive assignment in recital   1:   LEX: «Asset».

asset 103 reflexive assignment in recital   3:   "«Id»" is a text.
asset 103 reflexive assignment in recital   4:   "«Creator»" is a person.
asset 103 reflexive assignment in recital   5:   "«Owner»" is a person.

asset 103 reflexive assignment in recital   7:   The «Creator» fixes the «Id», and appoints herself as the «Owner».


asset 103 reflexive assignment in recital  10:   CLAUSE: «Transfer».

asset 103 reflexive assignment in recital  12:   The «Owner» may appoint a new «Owner».


