/** Lexon-generated Sophia code
 **
 **	code:        Burn
 **
 **	file:        cover/burn.lex
 **
 **	compiler:    lexon 0.3 beta 2
 **
 **	grammar:     0.2.20 / subset 0.3.11 beta 3 - English / Reyes
 **
 **	backend:     sophia 0.3.102 beta 2
 **
 **	target:      sophia 8+
 **
 **	options:     --sophia  --all-auxiliaries 
 **


   INSTRUCTIONS FOR USE:

   Deploy this smart contract to the Aeternity blockchain or testchain. An easy way to
   get started is to copy-paste this code into  https://studio.aepps.com.  Replace the
   <parameters> with literal values to interact with the contract via terminal.

   LIKE ALL SMART CONTRACTS THIS CODE MUST BE AUDITED BEFORE USING IT IN PRODUCTION.

   Note  that the instructions below  reflect your Lexon code,  as well as the options
   used during compilation of the code: different clauses and options will result from
   different input code.  Some functions are 'built-in' but only appear when needed as
   per compiler options used  during compilation – a list of options is available with
   lexon -h.  The functions are given in the order of appearance, in the Lexon source.

   The required caller is noted in double angle brackets << >>.  Some functions can be
   called by anyone.  Note that roles are being defined by using an account for it for
   the first time. This will require for the same account to be used for the same role
   after this point. Else, the call will revert, i.e. cancelled and not go through.

   Some clauses of the original Lexon source text do not appear in the comments below.
   Namely, those without permission phrase, wherefore they are regarded as internal.

   These are the constructor parameters for deployment. If you are using Aestudio, the
   fields under the deploy button are where your values for them go before deploying.

   

   These are the state progress functions that allow to interact with the contract:

 */

@compiler >=8

/**
 **
 **	Main Burn contract system
 **
 **/

/*
 | 	LEX Burn.
 | 
 | 	"Payer" is a person.
 | 	"Amount" is an amount.
 | 
 | 	The Payer pays an Amount into escrow.
 */


payable main contract Burn =
    record state = {
        
            payer : option(address),
            amount : option(int)
        }
    entrypoint init() = {
            payer = Some(Call.caller),
            amount = Some(Call.value)
        }
    

/* end */
