
precompilation:
---------------

escrow 103 long preamble text 5   1:   LEX: «Escrow».

escrow 103 long preamble text 5   3:   Preamble: ‹This is a long preamble text delimited by quote in the first definition line.›.

escrow 103 long preamble text 5   5:   A "«Payer»" is a person.
escrow 103 long preamble text 5   6:   "«Payee»" is a person.
escrow 103 long preamble text 5   7:   "«Arbiter»" is a person.
escrow 103 long preamble text 5   8:   "«Fee»" is an amount.

escrow 103 long preamble text 5  10:   The «Payer» pays an amount into escrow, appoints the «Payee», appoints the «Arbiter», and fixes the «Fee».

escrow 103 long preamble text 5  12:   CLAUSE: «Pay Out».
escrow 103 long preamble text 5  13:   The «Arbiter» may pay from escrow the «Fee» to themselves, and afterwards pay the remainder of the escrow to the «Payee».

escrow 103 long preamble text 5  15:   CLAUSE: «Pay Back».
escrow 103 long preamble text 5  16:   The «Arbiter» may pay from escrow the «Fee» to themselves, and afterwards return the remainder of the escrow to the «Payer».


