module.exports = class Escrow {

    constructor(buyer, amount, seller, agent, service_fee) {

        let main = this;
        this._escrow = 0;
        this.buyer = buyer;
        this.seller = seller;
        this.agent = agent;
        this.amount = amount;
        this.service_fee = service_fee;
        this.transfer(this.buyer, 'escrow', this.amount);
    }



    pay_out(caller)  {
        if(caller != this.agent) return 'not permitted';
        this.transfer('escrow', this.agent, this.service_fee);
        this.transfer('escrow', this.seller, this._escrow);
    }


    pay_back(caller)  {
        if(caller != this.agent) return 'not permitted';
        this.transfer('escrow', this.agent, this.service_fee);
        this.transfer('escrow', this.buyer, this._escrow);
    }


    transfer(from, to, amount) {
        console.log(`➠ system message: transfer ${amount} from ${from} to ${to}.`);
        if(from == 'escrow') main._escrow -= amount;
        if(to == 'escrow') main._escrow += amount;
    }
}