// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

contract Escrow {

    address payable buyer;
    address payable payee;
    address payable agent;
    uint amount;
    uint fee;
    bool amount__set = false;

    constructor(address payable _payee, address payable _agent, uint _fee) payable {
        buyer = payable(msg.sender);
        amount = msg.value;
        amount__set = true;
        payee = _payee;
        agent = _agent;
        fee = _fee;
    }

    function transfer(address _to, uint _amount) internal {
        (bool _success, ) = _to.call{value:_amount}("");
        require(_success, "transfer failed on receiver side");
    }

    function permit(address _authorized) internal view {
        require(msg.sender == _authorized, "not permitted");
    }


    function pay_out() public {
        permit(agent);
        transfer(agent, fee);
        transfer(payee, address(this).balance);
    }

    function pay_back() public {
        permit(agent);
        transfer(agent, fee);
        transfer(buyer, address(this).balance);
    }
}