

@compiler >=6

main contract Escrow =

    record state = {
            payer : address,
            seller : address,
            arbiter : address,
            amount : int
        }

    payable entrypoint init(seller : address, arbiter : address) = {
            payer = Call.caller,
            seller = seller,
            arbiter = arbiter,
            amount = Call.value
        }



    stateful function transfer(to : address, amount : int) =
        Chain.spend(to, amount)


    function permit(authorized : address) =
        require(Call.caller == authorized, "access")


    stateful entrypoint pay_out() =
        permit(state.arbiter)
        transfer(state.seller, Contract.balance)


    stateful entrypoint pay_back() =
        permit(state.arbiter)
        transfer(state.payer, Contract.balance)