module.exports = class Escrow {

    constructor(payer, amount, payee, agent, fee) {

        let main = this;
        this._escrow = 0;
        this.payer = payer;
        this.payee = payee;
        this.agent = agent;
        this.fee = fee;
        this._pay(this.payer, 'escrow', amount);
    }


    pay_out(caller)  {
        if(caller == this.agent) {
            this._pay('escrow', this.agent, this.fee);
            this._pay('escrow', this.payee, this._escrow);
        } else {
            return 'not permitted.';
        }
    }

    pay_back(caller)  {
        if(caller == this.agent) {
            this._pay('escrow', this.agent, this.fee);
            this._pay('escrow', this.payer, this._escrow);
        } else {
            return 'not permitted.';
        }
    }

    _pay(from, to, amount) {
        console.log(`➠ system message: pay ${amount} from ${from} to ${to}.`);
        if(from == 'escrow') main._escrow -= amount;
        if(to == 'escrow') main._escrow += amount;
    }
}