   document 
    ↳  head 
    ⎸   ↳  lex «escrow»   
    ↳  terms 
        ↳  provisions 
            ↳  definitions 
            ⎸   ↳  definition «buyer» 
            ⎸   ⎸   ↳  type-term 
            ⎸   ⎸       ↳  type 
            ⎸   ⎸           ↳  person   
            ⎸   ⎸ 
            ⎸   ↳  definition «payee» 
            ⎸   ⎸   ↳  type-term 
            ⎸   ⎸       ↳  type 
            ⎸   ⎸           ↳  person   
            ⎸   ⎸ 
            ⎸   ↳  definition «arbiter» 
            ⎸   ⎸   ↳  type-term 
            ⎸   ⎸       ↳  type 
            ⎸   ⎸           ↳  person   
            ⎸   ⎸ 
            ⎸   ↳  definition «amount» 
            ⎸       ↳  type-term 
            ⎸           ↳  type 
            ⎸               ↳  amount    
            ⎸ 
            ↳  clauses 
            ⎸   ↳  clause «pay-out» 
            ⎸   ⎸   ↳  body 
            ⎸   ⎸       ↳  statements 
            ⎸   ⎸           ↳  statement 
            ⎸   ⎸               ↳  action 
            ⎸   ⎸                   ↳  subject 
            ⎸   ⎸                   ⎸   ↳  symbols 
            ⎸   ⎸                   ⎸       ↳  symbol «arbiter»    
            ⎸   ⎸                   ⎸ 
            ⎸   ⎸                   ↳  predicates 
            ⎸   ⎸                   ⎸   ↳  predicate 
            ⎸   ⎸                   ⎸       ↳  payment 
            ⎸   ⎸                   ⎸           ↳  pay 
            ⎸   ⎸                   ⎸           ⎸ 
            ⎸   ⎸                   ⎸           ↳  preposition 
            ⎸   ⎸                   ⎸           ⎸ 
            ⎸   ⎸                   ⎸           ↳  object 
            ⎸   ⎸                   ⎸           ⎸   ↳  symbol «payee»   
            ⎸   ⎸                   ⎸           ⎸ 
            ⎸   ⎸                   ⎸           ↳  escrow    
            ⎸   ⎸                   ⎸ 
            ⎸   ⎸                   ↳  permission      
            ⎸   ⎸ 
            ⎸   ↳  clause «pay-back» 
            ⎸       ↳  body 
            ⎸           ↳  statements 
            ⎸               ↳  statement 
            ⎸                   ↳  action 
            ⎸                       ↳  subject 
            ⎸                       ⎸   ↳  symbols 
            ⎸                       ⎸       ↳  symbol «arbiter»    
            ⎸                       ⎸ 
            ⎸                       ↳  predicates 
            ⎸                       ⎸   ↳  predicate 
            ⎸                       ⎸       ↳  payment 
            ⎸                       ⎸           ↳  pay 
            ⎸                       ⎸           ⎸ 
            ⎸                       ⎸           ↳  preposition 
            ⎸                       ⎸           ⎸ 
            ⎸                       ⎸           ↳  object 
            ⎸                       ⎸           ⎸   ↳  symbol «buyer»   
            ⎸                       ⎸           ⎸ 
            ⎸                       ⎸           ↳  escrow    
            ⎸                       ⎸ 
            ⎸                       ↳  permission       
            ↳  statements 
                ↳  statement 
                    ↳  action 
                        ↳  subject 
                        ⎸   ↳  symbols 
                        ⎸       ↳  symbol «buyer»    
                        ↳  predicates 
                            ↳  predicate 
                            ⎸   ↳  payment 
                            ⎸       ↳  pay 
                            ⎸       ⎸ 
                            ⎸       ↳  expression 
                            ⎸       ⎸   ↳  combination 
                            ⎸       ⎸       ↳  combinor 
                            ⎸       ⎸           ↳  combinand 
                            ⎸       ⎸               ↳  symbol «amount»      
                            ⎸       ⎸ 
                            ⎸       ↳  preposition 
                            ⎸       ⎸ 
                            ⎸       ↳  object    
                            ⎸ 
                            ↳  predicate 
                            ⎸   ↳  appointment 
                            ⎸       ↳  appoint 
                            ⎸       ⎸ 
                            ⎸       ↳  symbol «payee»    
                            ↳  predicate 
                                ↳  appointment 
                                    ↳  appoint 
                                    ↳  symbol «arbiter»          
