// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

contract Escrow {

    address payable public buyer;
    address payable public payee;
    address payable public arbiter;
    uint public fee;

    constructor(address payable _payee, address payable _arbiter, uint _fee) payable {
        buyer = payable(msg.sender);
        payee = _payee;
        arbiter = _arbiter;
        fee = _fee;
    }


    function permit(address payable _authorized) internal view {
        require(msg.sender == _authorized, "not permitted");
    }


    function transfer(address payable _to, uint _amount) internal {
        (bool _success, ) = _to.call{value:_amount}("");
        require(_success, "transfer failed on receiver side");
    }


    function pay_out() public {
        permit(arbiter);
        transfer(arbiter, fee);
        transfer(payee, address(this).balance);
    }


    function pay_back() public {
        permit(arbiter);
        transfer(arbiter, fee);
        transfer(buyer, address(this).balance);
    }
}