module.exports = class Escrow {

    constructor(payer, amount, payee, arbiter, service_fee) {

        let main = this;
        this._escrow = 0;
        this.payer = payer;
        this.payee = payee;
        this.arbiter = arbiter;
        this.amount = amount;
        this.service_fee = service_fee;
        this._pay(this.payer, 'escrow', this.amount);
    }



    pay_out(caller)  {
        if(caller != this.arbiter) return 'not permitted';
        this._pay('escrow', this.arbiter, this.service_fee);
        this._pay('escrow', this.payee, this._escrow);
    }


    pay_back(caller)  {
        if(caller != this.arbiter) return 'not permitted';
        this._pay('escrow', this.arbiter, this.service_fee);
        this._pay('escrow', this.payer, this._escrow);
    }


    _pay(from, to, amount) {
        console.log(`➠ system message: pay ${amount} from ${from} to ${to}.`);
        if(from == 'escrow') main._escrow -= amount;
        if(to == 'escrow') main._escrow += amount;
    }
}