
precompilation:
---------------

escrow 103 long preamble text 4   1:   LEX: «Escrow».

escrow 103 long preamble text 4   3:   Preamble: ‹

This is a long preamble text
delimited with by "TERMS".›.

escrow 103 long preamble text 4   8:   TERMS: 

escrow 103 long preamble text 4  10:   "«Payer»" is a person.
escrow 103 long preamble text 4  11:   "«Payee»" is a person.
escrow 103 long preamble text 4  12:   "«Arbiter»" is a person.
escrow 103 long preamble text 4  13:   "«Fee»" is an amount.

escrow 103 long preamble text 4  15:   The «Payer» pays an amount into escrow, appoints the «Payee», appoints the «Arbiter», and fixes the «Fee».

escrow 103 long preamble text 4  17:   CLAUSE: «Pay Out».
escrow 103 long preamble text 4  18:   The «Arbiter» may pay from escrow the «Fee» to themselves, and afterwards pay the remainder of the escrow to the «Payee».

escrow 103 long preamble text 4  20:   CLAUSE: «Pay Back».
escrow 103 long preamble text 4  21:   The «Arbiter» may pay from escrow the «Fee» to themselves, and afterwards return the remainder of the escrow to the «Payer».


