module.exports = class Escrow {

    constructor(payer, amount, payee, agent, fee) {

        let main = this;
        this._escrow = 0;
        this.payer = payer;
        this.payee = payee;
        this.agent = agent;
        this.fee = fee;
        this.transfer(this.payer, 'escrow', amount);
    }



    pay_out(caller)  {
        if(caller != this.agent) return 'not permitted';
        this.transfer('escrow', this.agent, this.fee);
        this.transfer('escrow', this.payee, this._escrow);
    }


    pay_back(caller)  {
        if(caller != this.agent) return 'not permitted';
        this.transfer('escrow', this.agent, this.fee);
        this.transfer('escrow', this.payer, this._escrow);
    }


    transfer(from, to, amount) {
        console.log(`➠ system message: transfer ${amount} from ${from} to ${to}.`);
        if(from == 'escrow') main._escrow -= amount;
        if(to == 'escrow') main._escrow += amount;
    }
}