
precompilation:
---------------

escrow 103 precompilation margin   1:   LEX: «Escrow».

escrow 103 precompilation margin   3:   Preamble: ‹

## FIXTURE PREDICATE / PASSIVE
setting:     illocutor ["then"] ["therefor"["e"]] symbol
illocutor:   be ["defined"] ["as"]
be:          "be" or "is"›.


escrow 103 precompilation margin  11:   "«Payer»" is a person.
escrow 103 precompilation margin  12:   "«Payee»" is a person.
escrow 103 precompilation margin  13:   "«Arbiter»" is a person.
escrow 103 precompilation margin  14:   "«Fee»" is an amount.

escrow 103 precompilation margin  16:   The «Payer» pays an amount into escrow, appoints the «Payee», appoints the «Arbiter», and fixes the «Fee».

escrow 103 precompilation margin  18:   CLAUSE: «Pay Out».
escrow 103 precompilation margin  19:   The «Arbiter» may pay from escrow the «Fee» to themselves, and afterwards pay the remainder of the escrow to the «Payee».

escrow 103 precompilation margin  21:   CLAUSE: «Pay Back».
escrow 103 precompilation margin  22:   The «Arbiter» may pay from escrow the «Fee» to themselves, and afterwards return the remainder of the escrow to the «Payer».


