
precompilation:
---------------

escrow 103 long preamble text 6   1:   LEX: «Escrow».

escrow 103 long preamble text 6   3:   Preamble: ‹This is a long preamble text delimited by quote in the first definition line.›.

escrow 103 long preamble text 6   5:   "«Payer»" is a person.
escrow 103 long preamble text 6   6:   "«Payee»" is a person.
escrow 103 long preamble text 6   7:   "«Arbiter»" is a person.
escrow 103 long preamble text 6   8:   "«Fee»" is an amount.

escrow 103 long preamble text 6  10:   The «Payer» pays an amount into escrow, appoints the «Payee», appoints the «Arbiter», and fixes the «Fee».

escrow 103 long preamble text 6  12:   CLAUSE: «Pay Out».
escrow 103 long preamble text 6  13:   The «Arbiter» may pay from escrow the «Fee» to themselves, and afterwards pay the remainder of the escrow to the «Payee».

escrow 103 long preamble text 6  15:   CLAUSE: «Pay Back».
escrow 103 long preamble text 6  16:   The «Arbiter» may pay from escrow the «Fee» to themselves, and afterwards return the remainder of the escrow to the «Payer».


