

@compiler >=6

main contract Escrow =

    record state = {
            buyer : address,
            seller : address,
            arbiter : address,
            amount : int,
            service_fee : int
        }

    entrypoint init(seller : address, arbiter : address, service_fee : int) = {
            buyer = Call.caller,
            seller = seller,
            arbiter = arbiter,
            amount = Call.value,
            service_fee = service_fee
        }


    stateful function transfer(to : address, amount : int) =
        Chain.spend(to, amount)

    function permit(authorized : address) =
        require(Call.caller == authorized, "access")


    stateful entrypoint pay_out() =
        permit(state.arbiter)
        transfer(state.arbiter, state.service_fee)
        transfer(state.seller, Contract.balance)

    stateful entrypoint pay_back() =
        permit(state.arbiter)
        transfer(state.arbiter, state.service_fee)
        transfer(state.buyer, Contract.balance)