

@compiler >=6

main contract Escrow =

    record state = {
            buyer : address,
            seller : address,
            agent : address,
            amount : int,
            fee : int
        }

    payable entrypoint init(seller : address, agent : address, fee : int) = {
            buyer = Call.caller,
            seller = seller,
            agent = agent,
            amount = Call.value,
            fee = fee
        }



    function permit(authorized : address) =
        require(Call.caller == authorized, "access")


    stateful function transfer(to : address, amount : int) =
        Chain.spend(to, amount)


    stateful entrypoint pay_out() =
        permit(state.agent)
        transfer(state.agent, state.fee)
        transfer(state.seller, Contract.balance)


    stateful entrypoint pay_back() =
        permit(state.agent)
        transfer(state.agent, state.fee)
        transfer(state.buyer, Contract.balance)