( document 
    ( head 
        ( lex «escrow» ) 
        ( preamble "

## FIXTURE PREDICATE / PASSIVE
setting:     illocutor ["then"] ["therefor"["e"]] symbol
illocutor:   be ["defined"] ["as"]
be:          "be" or "is"") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «payer» ( type person ) ) 
                ( definition «payee» ( type person ) ) 
                ( definition «arbiter» ( type person ) ) 
                ( definition «fee» ( type amount ) ) ) 
            ( clauses 
                ( clause «pay-out» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «arbiter» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combinor ( combinand ( symbol «fee» ) ) ) ) ) 
                                                preposition 
                                                ( object reflexive ) 
                                                from-escrow ) ) 
                                        ( predicate 
                                            ( payment pay preposition 
                                                ( object ( symbol «payee» ) ) 
                                                escrow ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «pay-back» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «arbiter» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combinor ( combinand ( symbol «fee» ) ) ) ) ) 
                                                preposition 
                                                ( object reflexive ) 
                                                from-escrow ) ) 
                                        ( predicate 
                                            ( payment pay preposition 
                                                ( object ( symbol «payer» ) ) 
                                                escrow ) ) ) 
                                    permission ) ) ) ) ) ) 
            ( statements 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols ( symbol «payer» ) ) ) 
                        ( predicates 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combinor ( combinand ( symbol ( type amount ) ) ) ) ) ) 
                                    preposition 
                                    ( object ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol «payee» ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol «arbiter» ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «fee» ) ) ) ) ) ) ) ) ) )
