// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

contract Escrow {

    address payable buyer;
    address payable seller;
    address payable agent;
    uint amount;
    bool amount__set = false;

    constructor(address payable _seller, address payable _agent) payable {
        buyer = payable(msg.sender);
        amount = msg.value;
        amount__set = true;
        seller = _seller;
        agent = _agent;
    }

    function transfer(address _to, uint _amount) internal {
        (bool _success, ) = _to.call{value:_amount}("");
        require(_success, "transfer failed on receiver side");
    }

    function permit(address _authorized) internal view {
        require(msg.sender == _authorized, "not permitted");
    }


    function pay_out() public {
        permit(agent);
        transfer(seller, address(this).balance);
    }

    function pay_back() public {
        permit(agent);
        transfer(buyer, address(this).balance);
    }
}