

@compiler >=8
payable main contract Escrow =
    record state = {
        
            payer : address,
            payee : address,
            arbiter : address,
            amount : int
        }
    entrypoint init(payee : address, arbiter : address) = {
            payer = Call.caller,
            payee = payee,
            arbiter = arbiter,
            amount = Call.value
        }
    


    function permit(authorized : address) =
        require(Call.caller == authorized, "access")


    stateful function transfer(to : address, amount : int) =
        Chain.spend(to, amount)


    stateful entrypoint pay_out() =
        permit(state.arbiter)
        transfer(state.payee, Contract.balance)


    stateful entrypoint pay_back() =
        permit(state.arbiter)
        transfer(state.payer, Contract.balance)