   document 
    ↳  head 
    ⎸   ↳  lex «escrow»   
    ↳  terms 
        ↳  provisions 
            ↳  definitions 
            ⎸   ↳  definitions 
            ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ↳  definition «buyer» 
            ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸               ↳  person   
            ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ↳  definition «payee» 
            ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸               ↳  person   
            ⎸   ⎸   ⎸ 
            ⎸   ⎸   ↳  definition «arbiter» 
            ⎸   ⎸       ↳  type-term 
            ⎸   ⎸           ↳  type 
            ⎸   ⎸               ↳  person   
            ⎸   ⎸ 
            ⎸   ↳  definition «amount» 
            ⎸       ↳  type-term 
            ⎸           ↳  type 
            ⎸               ↳  amount    
            ⎸ 
            ↳  clauses 
            ⎸   ↳  clauses 
            ⎸   ⎸   ↳  clause «pay-out» 
            ⎸   ⎸       ↳  body 
            ⎸   ⎸           ↳  statements 
            ⎸   ⎸               ↳  statement 
            ⎸   ⎸                   ↳  action 
            ⎸   ⎸                       ↳  subject 
            ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸                       ⎸       ↳  symbol «arbiter» 
            ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸                       ⎸ 
            ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸                       ⎸       ↳  payment 
            ⎸   ⎸                       ⎸           ↳  pay 
            ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸                       ⎸           ↳  preposition 
            ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸                       ⎸           ↳  object 
            ⎸   ⎸                       ⎸           ⎸   ↳  symbol «payee» 
            ⎸   ⎸                       ⎸           ⎸       ↳  article   
            ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸                       ⎸           ↳  escrow    
            ⎸   ⎸                       ⎸ 
            ⎸   ⎸                       ↳  permission      
            ⎸   ⎸ 
            ⎸   ↳  clause «pay-back» 
            ⎸       ↳  body 
            ⎸           ↳  statements 
            ⎸               ↳  statement 
            ⎸                   ↳  action 
            ⎸                       ↳  subject 
            ⎸                       ⎸   ↳  symbols 
            ⎸                       ⎸       ↳  symbol «arbiter» 
            ⎸                       ⎸           ↳  article    
            ⎸                       ⎸ 
            ⎸                       ↳  predicates 
            ⎸                       ⎸   ↳  predicate 
            ⎸                       ⎸       ↳  payment 
            ⎸                       ⎸           ↳  pay 
            ⎸                       ⎸           ⎸ 
            ⎸                       ⎸           ↳  preposition 
            ⎸                       ⎸           ⎸ 
            ⎸                       ⎸           ↳  object 
            ⎸                       ⎸           ⎸   ↳  symbol «buyer» 
            ⎸                       ⎸           ⎸       ↳  article   
            ⎸                       ⎸           ⎸ 
            ⎸                       ⎸           ↳  escrow    
            ⎸                       ⎸ 
            ⎸                       ↳  permission       
            ↳  statements 
                ↳  statement 
                    ↳  action 
                        ↳  subject 
                        ⎸   ↳  symbols 
                        ⎸       ↳  symbol «buyer» 
                        ⎸           ↳  article    
                        ↳  predicates 
                            ↳  predicates 
                            ⎸   ↳  predicates 
                            ⎸   ⎸   ↳  predicate 
                            ⎸   ⎸       ↳  payment 
                            ⎸   ⎸           ↳  pay 
                            ⎸   ⎸           ⎸ 
                            ⎸   ⎸           ↳  expression 
                            ⎸   ⎸           ⎸   ↳  combination 
                            ⎸   ⎸           ⎸       ↳  combinor 
                            ⎸   ⎸           ⎸           ↳  combinand 
                            ⎸   ⎸           ⎸               ↳  symbol «amount»      
                            ⎸   ⎸           ⎸ 
                            ⎸   ⎸           ↳  preposition 
                            ⎸   ⎸           ⎸ 
                            ⎸   ⎸           ↳  object    
                            ⎸   ⎸ 
                            ⎸   ↳  predicate 
                            ⎸       ↳  appointment 
                            ⎸           ↳  appoint 
                            ⎸           ⎸ 
                            ⎸           ↳  symbol «payee» 
                            ⎸               ↳  article    
                            ↳  predicate 
                                ↳  appointment 
                                    ↳  appoint 
                                    ↳  symbol «arbiter» 
                                        ↳  article          
