
precompilation:
---------------

escrow 99a catch double subject for pronoun   1:   LEX: «Escrow».
escrow 99a catch double subject for pronoun   2:   COMMENT: ‹%ERR›.

escrow 99a catch double subject for pronoun   4:   "«Payer»" is a person.
escrow 99a catch double subject for pronoun   5:   "«Payee»" is a person.
escrow 99a catch double subject for pronoun   6:   "«Arbiter»" is a person.
escrow 99a catch double subject for pronoun   7:   "«Fee»" is an amount.

escrow 99a catch double subject for pronoun   9:   The «Payer» pays an amount into escrow, appoints the «Payee», appoints the «Arbiter», and fixes the «Fee».

escrow 99a catch double subject for pronoun  11:   CLAUSE: «Pay Out».
escrow 99a catch double subject for pronoun  12:   The «Arbiter» or the «Payer» may pay from escrow the «Fee» to themselves, and afterwards pay the remainder of the escrow to the «Payee».

escrow 99a catch double subject for pronoun  14:   CLAUSE: «Pay Back».
escrow 99a catch double subject for pronoun  15:   The «Arbiter» may pay from escrow the «Fee» to themselves, and afterwards return the remainder of the escrow to the «Payer».


