

@compiler >=6

main contract Escrow =

    record state = {
            payer : address,
            payee : address,
            agent : address,
            amount : int
        }

    entrypoint init(payee : address, agent : address) = {
            payer = Call.caller,
            payee = payee,
            agent = agent,
            amount = Call.value
        }


    stateful function transfer(to : address, amount : int) =
        Chain.spend(to, amount)

    function permit(authorized : address) =
        require(Call.caller == authorized, "access")


    stateful entrypoint pay_out() =
        permit(state.agent)
        transfer(state.payee, Contract.balance)

    stateful entrypoint pay_back() =
        permit(state.agent)
        transfer(state.payer, Contract.balance)