// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

contract Escrow {

    address payable public buyer;
    address payable public payee;
    address payable public agent;
    uint public amount;
    bool amount__set = false;

    constructor(address payable _payee, address payable _agent) payable {
        buyer = payable(msg.sender);
        amount = msg.value;
        amount__set = true;
        payee = _payee;
        agent = _agent;
    }


    function permit(address payable _authorized) internal view {
        require(msg.sender == _authorized, "not permitted");
    }


    function transfer(address payable _to, uint _amount) internal {
        (bool _success, ) = _to.call{value:_amount}("");
        require(_success, "transfer failed on receiver side");
    }


    function pay_out() public {
        permit(agent);
        transfer(payee, address(this).balance);
    }


    function pay_back() public {
        permit(agent);
        transfer(buyer, address(this).balance);
    }
}