   document 
    ↳  head 
    ⎸   ↳  lex «escrow»   
    ↳  terms 
        ↳  provisions 
            ↳  definitions 
            ⎸   ↳  definition «payer» 
            ⎸   ⎸   ↳  type-term 
            ⎸   ⎸       ↳  type 
            ⎸   ⎸       ⎸   ↳  person  
            ⎸   ⎸       ⎸ 
            ⎸   ⎸       ↳  article  
            ⎸   ⎸ 
            ⎸   ↳  definition «payee» 
            ⎸   ⎸   ↳  type-term 
            ⎸   ⎸       ↳  type 
            ⎸   ⎸       ⎸   ↳  person  
            ⎸   ⎸       ⎸ 
            ⎸   ⎸       ↳  article  
            ⎸   ⎸ 
            ⎸   ↳  definition «arbiter» 
            ⎸   ⎸   ↳  type-term 
            ⎸   ⎸       ↳  type 
            ⎸   ⎸       ⎸   ↳  person  
            ⎸   ⎸       ⎸ 
            ⎸   ⎸       ↳  article  
            ⎸   ⎸ 
            ⎸   ↳  definition «amount» 
            ⎸   ⎸   ↳  type-term 
            ⎸   ⎸       ↳  type 
            ⎸   ⎸       ⎸   ↳  amount  
            ⎸   ⎸       ⎸ 
            ⎸   ⎸       ↳  article  
            ⎸   ⎸ 
            ⎸   ↳  definition «fee» 
            ⎸       ↳  type-term 
            ⎸           ↳  type 
            ⎸           ⎸   ↳  amount  
            ⎸           ⎸ 
            ⎸           ↳  article   
            ⎸ 
            ↳  clauses 
            ⎸   ↳  clause «pay-out» 
            ⎸   ⎸   ↳  body 
            ⎸   ⎸       ↳  statements 
            ⎸   ⎸           ↳  statement 
            ⎸   ⎸               ↳  action 
            ⎸   ⎸                   ↳  subject 
            ⎸   ⎸                   ⎸   ↳  symbols 
            ⎸   ⎸                   ⎸       ↳  symbol «arbiter» 
            ⎸   ⎸                   ⎸           ↳  article    
            ⎸   ⎸                   ⎸ 
            ⎸   ⎸                   ↳  predicates 
            ⎸   ⎸                   ⎸   ↳  predicate 
            ⎸   ⎸                   ⎸   ⎸   ↳  payment 
            ⎸   ⎸                   ⎸   ⎸       ↳  pay 
            ⎸   ⎸                   ⎸   ⎸       ⎸ 
            ⎸   ⎸                   ⎸   ⎸       ↳  expression 
            ⎸   ⎸                   ⎸   ⎸       ⎸   ↳  combination 
            ⎸   ⎸                   ⎸   ⎸       ⎸       ↳  combinor 
            ⎸   ⎸                   ⎸   ⎸       ⎸           ↳  combinand 
            ⎸   ⎸                   ⎸   ⎸       ⎸               ↳  symbol «fee» 
            ⎸   ⎸                   ⎸   ⎸       ⎸                   ↳  article      
            ⎸   ⎸                   ⎸   ⎸       ⎸ 
            ⎸   ⎸                   ⎸   ⎸       ↳  preposition 
            ⎸   ⎸                   ⎸   ⎸       ⎸ 
            ⎸   ⎸                   ⎸   ⎸       ↳  object 
            ⎸   ⎸                   ⎸   ⎸       ⎸   ↳  reflexive  
            ⎸   ⎸                   ⎸   ⎸       ⎸ 
            ⎸   ⎸                   ⎸   ⎸       ↳  from-escrow   
            ⎸   ⎸                   ⎸   ⎸ 
            ⎸   ⎸                   ⎸   ↳  predicate 
            ⎸   ⎸                   ⎸       ↳  payment 
            ⎸   ⎸                   ⎸           ↳  pay 
            ⎸   ⎸                   ⎸           ⎸ 
            ⎸   ⎸                   ⎸           ↳  preposition 
            ⎸   ⎸                   ⎸           ⎸ 
            ⎸   ⎸                   ⎸           ↳  object 
            ⎸   ⎸                   ⎸           ⎸   ↳  symbol «payee» 
            ⎸   ⎸                   ⎸           ⎸       ↳  article   
            ⎸   ⎸                   ⎸           ⎸ 
            ⎸   ⎸                   ⎸           ↳  escrow    
            ⎸   ⎸                   ⎸ 
            ⎸   ⎸                   ↳  permission      
            ⎸   ⎸ 
            ⎸   ↳  clause «pay-back» 
            ⎸       ↳  body 
            ⎸           ↳  statements 
            ⎸               ↳  statement 
            ⎸                   ↳  action 
            ⎸                       ↳  subject 
            ⎸                       ⎸   ↳  symbols 
            ⎸                       ⎸       ↳  symbol «arbiter» 
            ⎸                       ⎸           ↳  article    
            ⎸                       ⎸ 
            ⎸                       ↳  predicates 
            ⎸                       ⎸   ↳  predicate 
            ⎸                       ⎸   ⎸   ↳  payment 
            ⎸                       ⎸   ⎸       ↳  pay 
            ⎸                       ⎸   ⎸       ⎸ 
            ⎸                       ⎸   ⎸       ↳  expression 
            ⎸                       ⎸   ⎸       ⎸   ↳  combination 
            ⎸                       ⎸   ⎸       ⎸       ↳  combinor 
            ⎸                       ⎸   ⎸       ⎸           ↳  combinand 
            ⎸                       ⎸   ⎸       ⎸               ↳  symbol «fee» 
            ⎸                       ⎸   ⎸       ⎸                   ↳  article      
            ⎸                       ⎸   ⎸       ⎸ 
            ⎸                       ⎸   ⎸       ↳  preposition 
            ⎸                       ⎸   ⎸       ⎸ 
            ⎸                       ⎸   ⎸       ↳  object 
            ⎸                       ⎸   ⎸       ⎸   ↳  reflexive  
            ⎸                       ⎸   ⎸       ⎸ 
            ⎸                       ⎸   ⎸       ↳  from-escrow   
            ⎸                       ⎸   ⎸ 
            ⎸                       ⎸   ↳  predicate 
            ⎸                       ⎸       ↳  payment 
            ⎸                       ⎸           ↳  pay 
            ⎸                       ⎸           ⎸ 
            ⎸                       ⎸           ↳  preposition 
            ⎸                       ⎸           ⎸ 
            ⎸                       ⎸           ↳  object 
            ⎸                       ⎸           ⎸   ↳  symbol «payer» 
            ⎸                       ⎸           ⎸       ↳  article   
            ⎸                       ⎸           ⎸ 
            ⎸                       ⎸           ↳  escrow    
            ⎸                       ⎸ 
            ⎸                       ↳  permission       
            ↳  statements 
                ↳  statement 
                    ↳  action 
                        ↳  subject 
                        ⎸   ↳  symbols 
                        ⎸       ↳  symbol «payer» 
                        ⎸           ↳  article    
                        ↳  predicates 
                            ↳  predicate 
                            ⎸   ↳  payment 
                            ⎸       ↳  pay 
                            ⎸       ⎸ 
                            ⎸       ↳  expression 
                            ⎸       ⎸   ↳  combination 
                            ⎸       ⎸       ↳  combinor 
                            ⎸       ⎸           ↳  combinand 
                            ⎸       ⎸               ↳  symbol «amount» 
                            ⎸       ⎸                   ↳  article      
                            ⎸       ⎸ 
                            ⎸       ↳  preposition 
                            ⎸       ⎸ 
                            ⎸       ↳  object    
                            ⎸ 
                            ↳  predicate 
                            ⎸   ↳  appointment 
                            ⎸       ↳  appoint 
                            ⎸       ⎸ 
                            ⎸       ↳  symbol «payee» 
                            ⎸           ↳  article    
                            ⎸ 
                            ↳  predicate 
                            ⎸   ↳  appointment 
                            ⎸       ↳  appoint 
                            ⎸       ⎸ 
                            ⎸       ↳  symbol «arbiter» 
                            ⎸           ↳  article    
                            ↳  predicate 
                                ↳  fixture 
                                    ↳  fix 
                                    ↳  symbol «fee» 
                                        ↳  article          
