/** Lexon-generated Sophia code
 **
 **	code:        Escrow
 **
 **	file:        lexon/escrow3.792.lex
 **
 **	compiler:    lexon 0.3 alpha 98 U
 **
 **	grammar:     0.2.20 / subset 0.3.8.3 alpha 98 - English / Reyes
 **
 **	backend:     sophia 0.3.98a U
 **
 **	target:      sophia 7.1+
 **
 **	options:     --sophia  --all-auxiliaries 
 **


   INSTRUCTIONS FOR USE:

   Deploy this smart contract to the Aeternity blockchain or testchain. An easy way to
   get started is to copy-paste this code into  https://studio.aepps.com.  Replace the
   <parameters> with literal values to interact with the contract via terminal.

   LIKE ALL SMART CONTRACTS THIS CODE MUST BE AUDITED BEFORE USING IT IN PRODUCTION.

   Note  that the instructions below  reflect your Lexon code,  as well as the options
   used during compilation of the code: different clauses and options will result from
   different input code.  Some functions are 'built-in' but only appear when needed as
   per compiler options used  during compilation – a list of options is available with
   lexon -h.  The functions are given in the order of appearance, in the Lexon source.

   The required caller is noted in double angle brackets << >>.  Some functions can be
   called by anyone.  Note that roles are being defined by using an account for it for
   the first time. This will require for the same account to be used for the same role
   after this point. Else, the call will revert, i.e. cancelled and not go through.

   Some clauses of the original Lexon source text do not appear in the comments below.
   Namely, those without permission phrase, wherefore they are regarded as internal.

   These are the constructor parameters for deployment. If you are using Aestudio, the
   fields under the deploy button are where your values for them go before deploying.

   <payee : option(address)>, <arbiter : option(address)>

   These are the state progress functions that allow to interact with the contract:

   • <<Arbiter>> ⟶   pay_out()
   • <<Arbiter>> ⟶   pay_back()
 */

@compiler >=6

include "Option.aes"

/**
 **
 **	Main Escrow contract system
 **
 **/

/*
 | 	LEX Escrow
 | 
 | 	
 | 	"Buyer" is person
 | 
 | 	"Payee" is person
 | 
 | 	"Arbiter" is person
 | 
 | 	"Amount" is amount
 | 
 | 	
 | 	Buyer pays Amount into escrow, appoints Payee, appoints Arbiter
 */



main contract Escrow =

    record state = {
            buyer : option(address),
            payee : option(address),
            arbiter : option(address),
            amount : option(int)
        }

    payable entrypoint init(payee : address, arbiter : address) = {
            buyer = Some(Call.caller),
            payee = Some(payee),
            arbiter = Some(arbiter),
            amount = Some(Call.value)
        }


    /* built-in caller assertion */

    function permit(authorized : option(address), name : string) =
        require(Call.caller == force(authorized, name), StringInternal.concat("no access for ", name))

    /* built-in safe transfer */

    stateful function transfer(to : address, amount : int) =
        Chain.spend(to, amount)

    /* built-in option type force function */

    function force(o : option('a), name : string) : 'a =
        switch(o)
            None => abort(StringInternal.concat(name, " not fixed"))
            Some(a) => a


    /* Pay Out clause */

    /*
     |  CLAUSE: Pay Out
     |  
     |  Arbiter may pay escrow to Payee
     */

    stateful entrypoint pay_out() =
        permit(state.arbiter, "Arbiter")
        transfer(force(state.payee, "Payee"), Contract.balance)


    /* Pay Back clause */

    /*
     |  CLAUSE: Pay Back
     |  
     |  Arbiter may pay escrow to Buyer
     */

    stateful entrypoint pay_back() =
        permit(state.arbiter, "Arbiter")
        transfer(force(state.buyer, "Buyer"), Contract.balance)

/* end */
