

@compiler >=6

main contract Escrow =

    record state = {
            payer : address,
            seller : address,
            arbiter : address,
            service_fee : int
        }

    payable entrypoint init(seller : address, arbiter : address, service_fee : int) = {
            payer = Call.caller,
            seller = seller,
            arbiter = arbiter,
            service_fee = service_fee
        }



    stateful function transfer(to : address, amount : int) =
        Chain.spend(to, amount)


    function permit(authorized : address) =
        require(Call.caller == authorized, "access")


    stateful entrypoint pay_out() =
        permit(state.arbiter)
        transfer(state.arbiter, state.service_fee)
        transfer(state.seller, Contract.balance)


    stateful entrypoint pay_back() =
        permit(state.arbiter)
        transfer(state.arbiter, state.service_fee)
        transfer(state.payer, Contract.balance)