
precompilation:
---------------

example 0.3 oneway   1:   LEX: «One Way Lock In».

example 0.3 oneway   3:   "«Payer»" is a person.
example 0.3 oneway   4:   "«Payee»" is a person.
example 0.3 oneway   5:   "«Amount»" is an amount.

example 0.3 oneway   7:   The «Payer» pays an «Amount» into escrow, and appoints the «Payee».

example 0.3 oneway   9:   CLAUSE: «Pay Out».
example 0.3 oneway  10:   The «Payer» may pay the escrow to the «Payee».

