// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

/** Lexon-generated Solidity code
 **
 **	code:        Four Way Escrow
 **
 **	file:        cover/example-0.3-fourway.lex
 **
 **	compiler:    lexon 0.3 alpha 99 U
 **
 **	grammar:     0.2.20 / subset 0.3.8.3 alpha 98 - English / Reyes
 **
 **	backend:     solidity 0.3.99a U
 **
 **	target:      solidity 0.8.17+
 **
 **	options:     --solidity  --all-auxiliaries 
 **


   INSTRUCTIONS FOR USE:

   Deploy this smart contract to the Ethereum blockchain or Goerli testchain.  Replace
   the <parameters> with literal values to interact with the contract via terminal.

   Note that the instructions below reflect your lexon code, as well as the parameters
   used during compilation of the code: different functions and parameters will result
   from different input.  Some functions are 'built-in' but only appear when needed as
   per compiler options used during compilation  –  a list of which, is available with
   lexon -h.  The functions are given in the order of appearance, in the lexon source.

   The required caller is noted in double angle brackets << >>.  Some functions can be
   called by anyone.  Note that roles are being defined by using an address for it for
   the first time. This will require for the same address to be used for the same role
   after this point. Else, the call will revert.

   Some clauses of the original lexon source text do not appear in the comments below.
   Namely, those without permission phrase, wherefore they are regarded as internal.

   These are the constructor parameters for deployment:

   <payee : address payable>, <arbiter : address payable>, <fee : uint>

   These are the state progress functions that allow to interact with the contract:

   • <<Arbiter>> ⟶   arbiter_pay_out()
   • <<Payer>> ⟶   voluntary_pay_out_by_payer()
   • <<Arbiter>> ⟶   arbiter_return()
   • <<Payee>> ⟶   voluntary_return_by_payer()
 */

/**
 **
 **	Main Four Way Escrow contract system
 **
 **/

/*
 | 	LEX Four Way Escrow.
 | 
 | 	"Payer" is a person.
 | 	"Payee" is a person.
 | 	"Arbiter" is a person.
 | 	"Fee" is an amount.
 | 	"Amount" is an amount.
 | 
 | 	The Payer pays an Amount into escrow, appoints the Payee, appoints the Arbiter, and fixes the Fee.
 */

contract FourWayEscrow {

    address payable public payer;
    address payable public payee;
    address payable public arbiter;
    uint public fee;
    uint public amount;
    bool amount__set = false;

    constructor(address payable _payee, address payable _arbiter, uint _fee) payable {
        payer = payable(msg.sender);
        amount = msg.value;
        amount__set = true;
        payee = _payee;
        arbiter = _arbiter;
        fee = _fee;
    }

    /* built-in caller assertion */

    function permit(address payable _authorized) internal view {
        require(msg.sender == _authorized, "not permitted");
    }

    /* built-in safe transfer */

    function transfer(address payable _to, uint _amount) internal {
        (bool _success, ) = _to.call{value:_amount}("");
        require(_success, "transfer failed on receiver side");
    }


    /* Arbiter Pay Out clause */

    /*
     |  CLAUSE: Arbiter Pay Out.
     |  The Arbiter may pay from escrow the Fee to themselves, and afterwards pay the remainder of the escrow to the Payee.
     */

    function arbiter_pay_out() public {
        permit(arbiter);
        transfer(arbiter, fee);
        transfer(payee, address(this).balance);
    }


    /* Voluntary Pay Out By Payer clause */

    /*
     |  CLAUSE: Voluntary Pay Out By Payer.
     |  The Payer may pay from escrow the Fee to themselves, and afterwards pay the remainder of the escrow to the Payee.
     */

    function voluntary_pay_out_by_payer() public {
        permit(payer);
        transfer(payer, fee);
        transfer(payee, address(this).balance);
    }


    /* Arbiter Return clause */

    /*
     |  CLAUSE: Arbiter Return.
     |  The Arbiter may pay from escrow the Fee to themselves, and afterwards return the remainder of the escrow to the Payer.
     */

    function arbiter_return() public {
        permit(arbiter);
        transfer(arbiter, fee);
        transfer(payer, address(this).balance);
    }


    /* Voluntary Return By Payer clause */

    /*
     |  CLAUSE: Voluntary Return By Payer.
     |  The Payee may pay from escrow the Fee to themselves, and afterwards return the remainder of the escrow to the Payer.
     */

    function voluntary_return_by_payer() public {
        permit(payee);
        transfer(payee, fee);
        transfer(payer, address(this).balance);
    }
}

/* end */
