// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

/** Lexon-generated Solidity code
 **
 **	code:        Burn
 **
 **	file:        cover/example-0.3-burn.lex
 **
 **	compiler:    lexon 0.3 alpha 99 U
 **
 **	grammar:     0.2.20 / subset 0.3.8.3 alpha 98 - English / Reyes
 **
 **	backend:     solidity 0.3.99a U
 **
 **	target:      solidity 0.8.17+
 **
 **	options:     --solidity  --all-auxiliaries 
 **


   INSTRUCTIONS FOR USE:

   Deploy this smart contract to the Ethereum blockchain or Goerli testchain.  Replace
   the <parameters> with literal values to interact with the contract via terminal.

   Note that the instructions below reflect your lexon code, as well as the parameters
   used during compilation of the code: different functions and parameters will result
   from different input.  Some functions are 'built-in' but only appear when needed as
   per compiler options used during compilation  –  a list of which, is available with
   lexon -h.  The functions are given in the order of appearance, in the lexon source.

   The required caller is noted in double angle brackets << >>.  Some functions can be
   called by anyone.  Note that roles are being defined by using an address for it for
   the first time. This will require for the same address to be used for the same role
   after this point. Else, the call will revert.

   Some clauses of the original lexon source text do not appear in the comments below.
   Namely, those without permission phrase, wherefore they are regarded as internal.

   These are the constructor parameters for deployment:

   

   These are the state progress functions that allow to interact with the contract:

 */

/**
 **
 **	Main Burn contract system
 **
 **/

/*
 | 	LEX Burn.
 | 
 | 	"Payer" is a person.
 | 	"Amount" is an amount.
 | 
 | 	The Payer pays an Amount into escrow.
 */

contract Burn {

    address payable public payer;
    uint public amount;
    bool amount__set = false;

    constructor() payable {
        payer = payable(msg.sender);
        amount = msg.value;
        amount__set = true;
    }
}

/* end */
