
precompilation:
---------------

example 0.3 fourway   1:   LEX: «Four Way Escrow».

example 0.3 fourway   3:   "«Payer»" is a person.
example 0.3 fourway   4:   "«Payee»" is a person.
example 0.3 fourway   5:   "«Arbiter»" is a person.
example 0.3 fourway   6:   "«Fee»" is an amount.
example 0.3 fourway   7:   "«Amount»" is an amount.

example 0.3 fourway   9:   The «Payer» pays an «Amount» into escrow, appoints the «Payee», appoints the «Arbiter», and fixes the «Fee».

example 0.3 fourway  11:   CLAUSE: «Arbiter Pay Out».
example 0.3 fourway  12:   The «Arbiter» may pay from escrow the «Fee» to themselves, and afterwards pay the remainder of the escrow to the «Payee».

example 0.3 fourway  14:   CLAUSE: «Voluntary Pay Out By Payer».
example 0.3 fourway  15:   The «Payer» may pay from escrow the «Fee» to themselves, and afterwards pay the remainder of the escrow to the «Payee».

example 0.3 fourway  17:   CLAUSE: «Arbiter Return».
example 0.3 fourway  18:   The «Arbiter» may pay from escrow the «Fee» to themselves, and afterwards return the remainder of the escrow to the «Payer».

example 0.3 fourway  20:   CLAUSE: «Voluntary Return By Payer».
example 0.3 fourway  21:   The «Payee» may pay from escrow the «Fee» to themselves, and afterwards return the remainder of the escrow to the «Payer».

