
precompilation:
---------------

example 0.3 statement   1:   LEX: «UCC Financing Statement».

example 0.3 statement   3:   LEXON: ‹0.2.12›.

example 0.3 statement   5:   "«Financing Statement»" is this contract.
example 0.3 statement   6:   "«File Number»" is data.
example 0.3 statement   7:   "«Initial Statement Date»" is a time.
example 0.3 statement   8:   "«Filer»" is a person.
example 0.3 statement   9:   "«Debtor»" is a person.
example 0.3 statement  10:   "«Secured Party»" is a person.
example 0.3 statement  11:   "«Filing Office»" is a person.
example 0.3 statement  12:   "«Collateral»" is data.
example 0.3 statement  13:   "«Digital Asset Collateral»" is an amount.
example 0.3 statement  14:   "«Reminder Fee»" is an amount.
example 0.3 statement  15:   "«Continuation Window Start»" is a time.
example 0.3 statement  16:   "«Continuation Statement Date»" is a time.
example 0.3 statement  17:   "«Continuation Statement Filing Number»" is data.
example 0.3 statement  18:   "«Lapse Date»" is a time.
example 0.3 statement  19:   "«Default»" is a binary.
example 0.3 statement  20:   "«Continuation Statement»" is a binary.
example 0.3 statement  21:   "«Termination Statement»" is a binary.
example 0.3 statement  22:   "«Termination Statement Time»" is a time.
example 0.3 statement  23:   "«Notification Statement»" is a text.

example 0.3 statement  25:   The «Filer» fixes the «Filing Office», fixes the «Debtor», fixes the «Secured Party», and fixes the «Collateral».

example 0.3 statement  27:   Clause: «Certify».
example 0.3 statement  28:   The «Filing Office» may certify the «File Number».

example 0.3 statement  30:   Clause: «Set File Date».
example 0.3 statement  31:   The «Filing Office» may fix the «Initial Statement Date» as the current time.

example 0.3 statement  33:   Clause: «Set Lapse».
example 0.3 statement  34:   The «Filing Office» may fix the «Lapse Date».

example 0.3 statement  36:   Clause: «Set Continuation Start».
example 0.3 statement  37:   The «Filing Office» may fix the «Continuation Window Start».

example 0.3 statement  39:   Clause: «Pay Fee».
example 0.3 statement  40:   The «Secured Party» may pay a «Reminder Fee» into escrow.

example 0.3 statement  42:   Clause: «Notice».
example 0.3 statement  43:   The «Filing Office» may fix the «Notification Statement».

example 0.3 statement  45:   Clause: «Notify».
example 0.3 statement  46:   The «Filing Office» may, if the «Continuation Window Start» has passed, send the «Notification Statement» to the «Secured Party».

example 0.3 statement  48:   Clause: «Pay Escrow In».
example 0.3 statement  49:   The «Debtor» may pay the «Digital Asset Collateral» into escrow.

example 0.3 statement  51:   Clause: «Fail to Pay».
example 0.3 statement  52:   The «Secured Party» may declare «Default».

example 0.3 statement  54:   Clause: «Take Possession».
example 0.3 statement  55:   The «Filing Office» may, if «Default» is declared, pay the «Digital Asset Collateral» to the «Secured Party».

example 0.3 statement  57:   Clause: «File Continuation».
example 0.3 statement  58:   The «Secured Party» may file the «Continuation Statement».

example 0.3 statement  60:   Clause: «Set Continuation Lapse».
example 0.3 statement  61:   The «Filing Office» may, if the «Continuation Statement» is filed, fix the «Continuation Statement Date».

example 0.3 statement  63:   Clause: «File Termination».
example 0.3 statement  64:   The «Secured Party» may file a «Termination Statement», and certify the «Termination Statement Time» as the then current time.

example 0.3 statement  66:   Clause: «Release Escrow».
example 0.3 statement  67:   The «Filing Office» may, if the «Termination Statement» is filed, return the «Digital Asset Collateral» to the «Debtor».

example 0.3 statement  69:   Clause: «Release Reminder Fee».
example 0.3 statement  70:   The «Filing Office» may, if the «Termination Statement» is filed, return the «Reminder Fee» to the «Secured Party».

example 0.3 statement  72:   Clause: «Termination Period».
example 0.3 statement  73:   "«Termination Period»" is defined as 365 days after the «Termination Statement Time».

example 0.3 statement  75:   Clause: «Terminate and Clear».
example 0.3 statement  76:   The «Filing Office» may, if the «Termination Period» has passed, terminate this contract.


