/** Lexon-generated Sophia code
 **
 **	code:        Preregistration
 **
 **	file:        cover/preregistration.lex
 **
 **	compiler:    lexon 0.3 alpha 99 U
 **
 **	grammar:     0.2.20 / subset 0.3.9 alpha 99 - English / Reyes
 **
 **	backend:     sophia 0.3.99a U
 **
 **	target:      sophia 8+
 **
 **	options:     --sophia  --all-auxiliaries 
 **


   INSTRUCTIONS FOR USE:

   Deploy this smart contract to the Aeternity blockchain or testchain. An easy way to
   get started is to copy-paste this code into  https://studio.aepps.com.  Replace the
   <parameters> with literal values to interact with the contract via terminal.

   LIKE ALL SMART CONTRACTS THIS CODE MUST BE AUDITED BEFORE USING IT IN PRODUCTION.

   Note  that the instructions below  reflect your Lexon code,  as well as the options
   used during compilation of the code: different clauses and options will result from
   different input code.  Some functions are 'built-in' but only appear when needed as
   per compiler options used  during compilation – a list of options is available with
   lexon -h.  The functions are given in the order of appearance, in the Lexon source.

   The required caller is noted in double angle brackets << >>.  Some functions can be
   called by anyone.  Note that roles are being defined by using an account for it for
   the first time. This will require for the same account to be used for the same role
   after this point. Else, the call will revert, i.e. cancelled and not go through.

   Some clauses of the original Lexon source text do not appear in the comments below.
   Namely, those without permission phrase, wherefore they are regarded as internal.

   These are the constructor parameters for deployment. If you are using Aestudio, the
   fields under the deploy button are where your values for them go before deploying.

   <deadline : option(int)>, <registry : option(address)>

   These are the state progress functions that allow to interact with the contract:


   The following are actions that can be performed per Attendee.

   > attendee = preregistration.add_attendee(<attendee : option(address)>)
 */

@compiler >=8

include "Option.aes"

namespace MainState =
    record main_state = {
            organizer : option(address),
            registry : option(address),
            deadline : option(int),
            _attendee_list : list(address),
            _attendee_count : int
        }

using MainState

contract interface Main =
    entrypoint get_state: () => main_state


/**
 **
 **	Main Preregistration contract system
 **
 **/

/*
 | 	LEX Preregistration
 | 
 | 	"Organizer" is a person.
 | 	"Registry" is a person.
 | 	"Deadline" is a time.
 | 
 | 	The Organizer fixes the Deadline, and appoints the Registry.
 */


main contract Preregistration : Main =


    type state = main_state

    entrypoint init(deadline : int, registry : address) = {
            organizer = Some(Call.caller),
            registry = Some(registry),
            deadline = Some(deadline),
            _attendee_list = [],
            _attendee_count = 0
        }

    entrypoint get_state() : state =
        state

        
    

    /* create new instance of Attendee covenant, and register it with main */
    stateful entrypoint add_attendee(attendee : address) : address =
        let covenant = Chain.create(Address.to_contract(Contract.address) : Preregistration, attendee) : Attendee
        put(state{ _attendee_count = state._attendee_count + 1})
        put(state{ _attendee_list = covenant.address :: state._attendee_list })
        covenant.address

/**
 **
 **	Attendee covenant class
 **
 **/

/*
 | 	TERMS PER Attendee
 | 
 | 	"Attendee" is a person.
 | 
 | 	The Registry may, if the Deadline has not yet passed, appoint an Attendee.
 */

contract Attendee =

    record state = {
            global : main_state,
            attendee : option(address)
        }

    entrypoint init(global : Main, attendee : address) = {
            attendee = Some(attendee),
            global = global.get_state()
        }
    if(Option.force_msg( state.global.deadline, "Deadline") > Chain.timestamp)

/* end */
