( document 
    ( head 
        ( lex «show-me-the-money» ) ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «payer» ( type person ) ) 
                ( definition «amount» ( type amount ) ) ) 
            ( clauses 
                ( clause «take-back» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «payer» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combinor ( combinand ( symbol «amount» ) ) ) ) ) 
                                                preposition 
                                                ( object reflexive ) ) ) ) ) ) ) ) ) ) 
            ( statements 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols ( symbol «payer» ) ) ) 
                        ( predicates 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combinor ( combinand ( symbol «amount» ) ) ) ) ) 
                                    preposition 
                                    ( object ) ) ) ) ) ) ) ) ) )
