   document 
    ↳  head 
    ⎸   ↳  lex «ucc-financing-statement»  
    ⎸   ⎸ 
    ⎸   ↳  lexon "0.2.12"  
    ↳  terms 
        ↳  provisions 
            ↳  definitions 
            ⎸   ↳  definitions 
            ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definitions 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «financing-statement» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  this-contract 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  this   
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «file-number» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  data   
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «initial-statement-date» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸   ↳  time  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «filer» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸   ↳  person  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «debtor» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸   ↳  person  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «secured-party» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸   ↳  person  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «filing-office» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸   ↳  person  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «collateral» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  data   
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «digital-asset-collateral» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸   ↳  amount  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «reminder-service-fee» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸   ↳  amount  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «continuation-window-start» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸   ↳  time  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «continuation-statement-date» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸   ↳  time  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «continuation-statement-filing-number» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  data   
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «lapse-date» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸   ↳  time  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ↳  definition «default» 
            ⎸   ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸   ⎸           ⎸   ↳  binary  
            ⎸   ⎸   ⎸   ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸           ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ↳  definition «continuation-statement» 
            ⎸   ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸   ⎸           ⎸   ↳  binary  
            ⎸   ⎸   ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸           ↳  article  
            ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ↳  definition «termination-statement» 
            ⎸   ⎸   ⎸       ↳  type-term 
            ⎸   ⎸   ⎸           ↳  type 
            ⎸   ⎸   ⎸           ⎸   ↳  binary  
            ⎸   ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸           ↳  article  
            ⎸   ⎸   ⎸ 
            ⎸   ⎸   ↳  definition «termination-statement-time» 
            ⎸   ⎸       ↳  type-term 
            ⎸   ⎸           ↳  type 
            ⎸   ⎸           ⎸   ↳  time  
            ⎸   ⎸           ⎸ 
            ⎸   ⎸           ↳  article  
            ⎸   ⎸ 
            ⎸   ↳  definition «notification-statement» 
            ⎸       ↳  type-term 
            ⎸           ↳  type 
            ⎸           ⎸   ↳  text  
            ⎸           ⎸ 
            ⎸           ↳  article   
            ⎸ 
            ↳  clauses 
            ⎸   ↳  clauses 
            ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clauses 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clause «certify» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «filing-office» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  certification 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  certify 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  symbol «file-number» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  article     
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  permission      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clause «set-file-date» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «filing-office» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  fixture 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  fix 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  symbol «initial-statement-date» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸   ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  expression 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  combination 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                   ↳  combinor 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                       ↳  combinand 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                           ↳  point-in-time 
                                                                                                                                ↳  current-time         
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  permission      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clause «set-lapse» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «filing-office» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  fixture 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  fix 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  symbol «lapse-date» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  article     
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  permission      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clause «set-continuation-start» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «filing-office» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  fixture 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  fix 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  symbol «continuation-window-start» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  article     
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  permission      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clause «pay-service-fee» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «secured-party» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  payment 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  pay 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  expression 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸   ↳  combination 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸       ↳  combinor 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸           ↳  combinand 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸               ↳  symbol «reminder-service-fee» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸                   ↳  article      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  preposition 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  object     
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  permission      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clause «notice» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «filing-office» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  fixture 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  fix 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  symbol «notification-statement» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  article     
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  permission      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clause «notify» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «filing-office» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  sending 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  send 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  expression 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸   ↳  combination 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸       ↳  combinor 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸           ↳  combinand 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸               ↳  symbol «notification-statement» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸                   ↳  article      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  preposition 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  object 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  symbol «secured-party» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                   ↳  article      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  permission 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  condition 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  if 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  expression 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  combination 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  combinor 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  combinand 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                   ↳  symbol «continuation-window-start» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                   ⎸   ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                   ↳  expiration      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  punctuation      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clause «pay-escrow-in» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «debtor» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  payment 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  pay 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  expression 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸   ↳  combination 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸       ↳  combinor 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸           ↳  combinand 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸               ↳  symbol «digital-asset-collateral» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸                   ↳  article      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  preposition 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  object     
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  permission      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clause «fail-to-pay» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «secured-party» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  declaration 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  declare 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  symbol «default»     
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  permission      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clause «take-possession» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «filing-office» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  payment 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  pay 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  expression 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸   ↳  combination 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸       ↳  combinor 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸           ↳  combinand 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸               ↳  symbol «digital-asset-collateral» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸                   ↳  article      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  preposition 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  object 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  symbol «secured-party» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                   ↳  article      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  permission 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  condition 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  if 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  expression 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  combination 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  combinor 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  combinand 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                   ↳  existence 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                       ↳  symbol «default»  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                       ↳  being 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                       ↳  true       
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  punctuation      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clause «file-continuation» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «secured-party» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  filing 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  file 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  symbol «continuation-statement» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  article     
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  permission      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clause «set-continuation-lapse» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «filing-office» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  fixture 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  fix 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  symbol «continuation-statement-date» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  article     
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  permission 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  condition 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  if 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  expression 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  combination 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  combinor 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  combinand 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                   ↳  existence 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                       ↳  symbol «continuation-statement» 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                       ⎸   ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                       ↳  being 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                       ↳  true       
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  punctuation      
            ⎸   ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸   ↳  clause «file-termination» 
            ⎸   ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «secured-party» 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicates 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ⎸       ↳  filing 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ⎸           ↳  file 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ⎸           ↳  symbol «termination-statement» 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ⎸               ↳  article    
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  certification 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  certify 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  symbol «termination-statement-time» 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸   ↳  article  
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  expression 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  combination 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                   ↳  combinor 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                       ↳  combinand 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                           ↳  point-in-time 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸                               ↳  current-time         
            ⎸   ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸   ⎸                       ↳  permission      
            ⎸   ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸   ↳  clause «release-escrow» 
            ⎸   ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  symbol «filing-office» 
            ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  payment 
            ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  pay 
            ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  expression 
            ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸   ↳  combination 
            ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸       ↳  combinor 
            ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸           ↳  combinand 
            ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸               ↳  symbol «digital-asset-collateral» 
            ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸                   ↳  article      
            ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  preposition 
            ⎸   ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  object 
            ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  symbol «debtor» 
            ⎸   ⎸   ⎸   ⎸                       ⎸                   ↳  article      
            ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸                       ↳  permission 
            ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸                       ↳  condition 
            ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  if 
            ⎸   ⎸   ⎸   ⎸                       ⎸   ⎸ 
            ⎸   ⎸   ⎸   ⎸                       ⎸   ↳  expression 
            ⎸   ⎸   ⎸   ⎸                       ⎸       ↳  combination 
            ⎸   ⎸   ⎸   ⎸                       ⎸           ↳  combinor 
            ⎸   ⎸   ⎸   ⎸                       ⎸               ↳  combinand 
            ⎸   ⎸   ⎸   ⎸                       ⎸                   ↳  existence 
            ⎸   ⎸   ⎸   ⎸                       ⎸                       ↳  symbol «termination-statement» 
            ⎸   ⎸   ⎸   ⎸                       ⎸                       ⎸   ↳  article  
            ⎸   ⎸   ⎸   ⎸                       ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸                       ⎸                       ↳  being 
            ⎸   ⎸   ⎸   ⎸                       ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸                       ⎸                       ↳  true       
            ⎸   ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸   ⎸                       ↳  punctuation      
            ⎸   ⎸   ⎸   ⎸ 
            ⎸   ⎸   ⎸   ↳  clause «release-reminder-service-fee» 
            ⎸   ⎸   ⎸       ↳  body 
            ⎸   ⎸   ⎸           ↳  statements 
            ⎸   ⎸   ⎸               ↳  statement 
            ⎸   ⎸   ⎸                   ↳  action 
            ⎸   ⎸   ⎸                       ↳  subject 
            ⎸   ⎸   ⎸                       ⎸   ↳  symbols 
            ⎸   ⎸   ⎸                       ⎸       ↳  symbol «filing-office» 
            ⎸   ⎸   ⎸                       ⎸           ↳  article    
            ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸                       ↳  predicates 
            ⎸   ⎸   ⎸                       ⎸   ↳  predicate 
            ⎸   ⎸   ⎸                       ⎸       ↳  payment 
            ⎸   ⎸   ⎸                       ⎸           ↳  pay 
            ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸                       ⎸           ↳  expression 
            ⎸   ⎸   ⎸                       ⎸           ⎸   ↳  combination 
            ⎸   ⎸   ⎸                       ⎸           ⎸       ↳  combinor 
            ⎸   ⎸   ⎸                       ⎸           ⎸           ↳  combinand 
            ⎸   ⎸   ⎸                       ⎸           ⎸               ↳  symbol «reminder-service-fee» 
            ⎸   ⎸   ⎸                       ⎸           ⎸                   ↳  article      
            ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸                       ⎸           ↳  preposition 
            ⎸   ⎸   ⎸                       ⎸           ⎸ 
            ⎸   ⎸   ⎸                       ⎸           ↳  object 
            ⎸   ⎸   ⎸                       ⎸               ↳  symbol «secured-party» 
            ⎸   ⎸   ⎸                       ⎸                   ↳  article      
            ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸                       ↳  permission 
            ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸                       ↳  condition 
            ⎸   ⎸   ⎸                       ⎸   ↳  if 
            ⎸   ⎸   ⎸                       ⎸   ⎸ 
            ⎸   ⎸   ⎸                       ⎸   ↳  expression 
            ⎸   ⎸   ⎸                       ⎸       ↳  combination 
            ⎸   ⎸   ⎸                       ⎸           ↳  combinor 
            ⎸   ⎸   ⎸                       ⎸               ↳  combinand 
            ⎸   ⎸   ⎸                       ⎸                   ↳  existence 
            ⎸   ⎸   ⎸                       ⎸                       ↳  symbol «termination-statement» 
            ⎸   ⎸   ⎸                       ⎸                       ⎸   ↳  article  
            ⎸   ⎸   ⎸                       ⎸                       ⎸ 
            ⎸   ⎸   ⎸                       ⎸                       ↳  being 
            ⎸   ⎸   ⎸                       ⎸                       ⎸ 
            ⎸   ⎸   ⎸                       ⎸                       ↳  true       
            ⎸   ⎸   ⎸                       ⎸ 
            ⎸   ⎸   ⎸                       ↳  punctuation      
            ⎸   ⎸   ⎸ 
            ⎸   ⎸   ↳  clause «termination-period» 
            ⎸   ⎸       ↳  body 
            ⎸   ⎸           ↳  function «termination-period» 
            ⎸   ⎸               ↳  illocutor 
            ⎸   ⎸               ⎸   ↳  be  
            ⎸   ⎸               ⎸ 
            ⎸   ⎸               ↳  expression 
            ⎸   ⎸                   ↳  combination 
            ⎸   ⎸                       ↳  combinor 
            ⎸   ⎸                           ↳  combinand 
            ⎸   ⎸                               ↳  point-in-time 
            ⎸   ⎸                                   ↳  relative-time 
            ⎸   ⎸                                       ↳  duration 
            ⎸   ⎸                                       ⎸   ↳  scalar-expression 365  
            ⎸   ⎸                                       ⎸   ⎸ 
            ⎸   ⎸                                       ⎸   ↳  time-unit 
            ⎸   ⎸                                       ⎸       ↳  days   
            ⎸   ⎸                                       ⎸ 
            ⎸   ⎸                                       ↳  symbol «termination-statement-time» 
            ⎸   ⎸                                           ↳  article           
            ⎸   ⎸ 
            ⎸   ↳  clause «terminate-and-clear» 
            ⎸       ↳  body 
            ⎸           ↳  statements 
            ⎸               ↳  statement 
            ⎸                   ↳  action 
            ⎸                       ↳  subject 
            ⎸                       ⎸   ↳  symbols 
            ⎸                       ⎸       ↳  symbol «filing-office» 
            ⎸                       ⎸           ↳  article    
            ⎸                       ⎸ 
            ⎸                       ↳  predicates 
            ⎸                       ⎸   ↳  predicate 
            ⎸                       ⎸       ↳  termination 
            ⎸                       ⎸           ↳  terminate 
            ⎸                       ⎸           ⎸ 
            ⎸                       ⎸           ↳  this-contract 
            ⎸                       ⎸               ↳  this     
            ⎸                       ⎸ 
            ⎸                       ↳  permission 
            ⎸                       ⎸ 
            ⎸                       ↳  condition 
            ⎸                       ⎸   ↳  if 
            ⎸                       ⎸   ⎸ 
            ⎸                       ⎸   ↳  expression 
            ⎸                       ⎸       ↳  combination 
            ⎸                       ⎸           ↳  combinor 
            ⎸                       ⎸               ↳  combinand 
            ⎸                       ⎸                   ↳  symbol «termination-period» 
            ⎸                       ⎸                   ⎸   ↳  article  
            ⎸                       ⎸                   ⎸ 
            ⎸                       ⎸                   ↳  expiration      
            ⎸                       ⎸ 
            ⎸                       ↳  punctuation       
            ↳  statements 
                ↳  statement 
                    ↳  action 
                        ↳  subject 
                        ⎸   ↳  symbols 
                        ⎸       ↳  symbol «filer» 
                        ⎸           ↳  article    
                        ↳  predicates 
                            ↳  predicates 
                            ⎸   ↳  predicates 
                            ⎸   ⎸   ↳  predicates 
                            ⎸   ⎸   ⎸   ↳  predicate 
                            ⎸   ⎸   ⎸       ↳  fixture 
                            ⎸   ⎸   ⎸           ↳  fix 
                            ⎸   ⎸   ⎸           ⎸ 
                            ⎸   ⎸   ⎸           ↳  symbol «filing-office» 
                            ⎸   ⎸   ⎸               ↳  article    
                            ⎸   ⎸   ⎸ 
                            ⎸   ⎸   ↳  predicate 
                            ⎸   ⎸       ↳  fixture 
                            ⎸   ⎸           ↳  fix 
                            ⎸   ⎸           ⎸ 
                            ⎸   ⎸           ↳  symbol «debtor» 
                            ⎸   ⎸               ↳  article    
                            ⎸   ⎸ 
                            ⎸   ↳  predicate 
                            ⎸       ↳  fixture 
                            ⎸           ↳  fix 
                            ⎸           ⎸ 
                            ⎸           ↳  symbol «secured-party» 
                            ⎸               ↳  article    
                            ↳  predicate 
                                ↳  fixture 
                                    ↳  fix 
                                    ↳  symbol «collateral» 
                                        ↳  article          
