( document 
    ( head 
        ( lex «ucc-financing-statement» ) 
        ( lexon "0.3 alpha 97") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «financing-statement» 
                    ( this-contract ) ) 
                ( definition «file-number» ( type data ) ) 
                ( definition «initial-statement-date» ( type time ) ) 
                ( definition «filer» ( type person ) ) 
                ( definition «debtor» ( type person ) ) 
                ( definition «secured-party» ( type person ) ) 
                ( definition «filing-office» ( type person ) ) 
                ( definition «collateral» ( type data ) ) 
                ( definition «digital-asset-collateral» ( type amount ) ) 
                ( definition «reminder-fee» ( type amount ) ) 
                ( definition «continuation-window-start» ( type time ) ) 
                ( definition «continuation-statement-date» ( type time ) ) 
                ( definition «continuation-statement-filing-number» ( type data ) ) 
                ( definition «lapse-date» ( type time ) ) 
                ( definition «default» ( type binary ) ) 
                ( definition «continuation-statement» ( type binary ) ) 
                ( definition «termination-statement» ( type binary ) ) 
                ( definition «termination-statement-time» ( type time ) ) 
                ( definition «notification-statement» ( type text ) ) ) 
            ( clauses 
                ( clause «multi-certify» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols 
                                            ( symbols ( symbol «filer» ) ) 
                                            ( symbol «filing-office» ) 
                                            catena ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( certification certify ( symbol «file-number» ) ) ) ) 
                                    permission ) ) 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols 
                                            ( symbols ( symbol «filer» ) ) 
                                            ( symbol «filing-office» ) 
                                            catena ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( appointment appoint ( symbol «filing-office» ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «triple-certify» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols 
                                            ( symbols 
                                                ( symbols ( symbol «filer» ) ) 
                                                ( symbol «filing-office» ) 
                                                catena ) 
                                            ( symbol «secured-party» ) 
                                            catena ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( certification certify ( symbol «file-number» ) ) ) ) 
                                    permission ) ) 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols 
                                            ( symbols ( symbol «filer» ) ) 
                                            ( symbol «filing-office» ) 
                                            catena ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( appointment appoint ( symbol «filing-office» ) ) ) ) 
                                    permission ) ) 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filing-office» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( fixture fix ( symbol «reminder-fee» ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «value-certify» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filing-office» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( fixture fix ( symbol «reminder-fee» ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «alternate-certify» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filer» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( certification certify ( symbol «file-number» ) ) ) ) 
                                    permission ) ) 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filing-office» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( appointment appoint ( symbol «filing-office» ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «super-certify» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols 
                                            ( symbols ( symbol «filer» ) ) 
                                            ( symbol «filing-office» ) 
                                            catena ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( certification certify ( symbol «file-number» ) ) ) ) 
                                    permission ) ) 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols 
                                            ( symbols ( symbol «filer» ) ) 
                                            ( symbol «filer» ) 
                                            catena ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( appointment appoint ( symbol «filing-office» ) 
                                                ( expression ( combination ( combinor ( combinand reflexive ) ) ) ) ) ) ) 
                                    permission ) ) 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filer» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( certification certify ( symbol «file-number» ) ) ) ) 
                                    permission ) ) 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filer» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( certification certify ( symbol «filer» ) ) ) ) 
                                    permission ) ) 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filing-office» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( appointment appoint ( symbol «filing-office» ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «set-file-date» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filing-office» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( fixture fix ( symbol «initial-statement-date» ) 
                                                ( expression ( combination ( combinor ( combinand 
                                                                ( point-in-time current-time ) ) ) ) ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «set-lapse» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filing-office» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( fixture fix ( symbol «lapse-date» ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «set-continuation-start» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filing-office» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( fixture fix ( symbol «continuation-window-start» ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «pay-fee» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «secured-party» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combinor ( combinand ( symbol «reminder-fee» ) ) ) ) ) 
                                                preposition 
                                                ( object ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «notice» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filing-office» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( fixture fix ( symbol «notification-statement» ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «pay-escrow-in» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «debtor» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combinor ( combinand ( symbol «digital-asset-collateral» ) ) ) ) ) 
                                                preposition 
                                                ( object ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «fail-to-pay» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «secured-party» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( declaration declare ( symbol «default» ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «take-possession» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filing-office» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combinor ( combinand ( symbol «digital-asset-collateral» ) ) ) ) ) 
                                                preposition 
                                                ( object ( symbol «secured-party» ) ) ) ) ) 
                                    permission 
                                    ( condition if 
                                        ( expression ( combination ( combinor ( combinand 
                                                        ( existence ( symbol «default» ) 
                                                            being true ) ) ) ) ) ) ) ) ) ) ) 
                ( clause «file-continuation» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «secured-party» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( filing file ( symbol «continuation-statement» ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «set-continuation-lapse» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filing-office» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( fixture fix ( symbol «continuation-statement-date» ) ) ) ) 
                                    permission 
                                    ( condition if 
                                        ( expression ( combination ( combinor ( combinand 
                                                        ( existence ( symbol «continuation-statement» ) 
                                                            being true ) ) ) ) ) ) ) ) ) ) ) 
                ( clause «file-termination» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «secured-party» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( filing file ( symbol «termination-statement» ) ) ) 
                                        ( predicate 
                                            ( certification certify ( symbol «termination-statement-time» ) 
                                                ( expression ( combination ( combinor ( combinand 
                                                                ( point-in-time current-time ) ) ) ) ) ) ) ) 
                                    permission ) ) ) ) ) 
                ( clause «release-escrow» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filing-office» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combinor ( combinand ( symbol «digital-asset-collateral» ) ) ) ) ) 
                                                preposition 
                                                ( object ( symbol «debtor» ) ) ) ) ) 
                                    permission 
                                    ( condition if 
                                        ( expression ( combination ( combinor ( combinand 
                                                        ( existence ( symbol «termination-statement» ) 
                                                            being true ) ) ) ) ) ) ) ) ) ) ) 
                ( clause «release-reminder-fee» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filing-office» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combinor ( combinand ( symbol «reminder-fee» ) ) ) ) ) 
                                                preposition 
                                                ( object ( symbol «secured-party» ) ) ) ) ) 
                                    permission 
                                    ( condition if 
                                        ( expression ( combination ( combinor ( combinand 
                                                        ( existence ( symbol «termination-statement» ) 
                                                            being true ) ) ) ) ) ) ) ) ) ) ) 
                ( clause «termination-period» 
                    ( body 
                        ( function «termination-period» 
                            ( illocutor be ) 
                            ( expression ( combination ( combinor ( combinand 
                                            ( point-in-time 
                                                ( relative-time 
                                                    ( duration 
                                                        ( scalar-expression 365 ) 
                                                        ( time-unit days ) ) 
                                                    ( symbol «termination-statement-time» ) ) ) ) ) ) ) ) ) ) 
                ( clause «terminate-and-clear» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol «filing-office» ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( termination terminate 
                                                ( this-contract ) ) ) ) 
                                    permission 
                                    ( condition if 
                                        ( expression ( combination ( combinor ( combinand ( symbol «termination-period» ) 
                                                        expiration ) ) ) ) ) ) ) ) ) ) ) 
            ( statements 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols ( symbol «filer» ) ) ) 
                        ( predicates 
                            ( predicate 
                                ( fixture fix ( symbol «filing-office» ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «debtor» ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «secured-party» ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «collateral» ) ) ) ) ) ) ) ) ) )
