( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «bar» ( type data ) ) ) 
            ( statements 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols ( symbol «bar» ) ) ) 
                        ( predicates 
                            ( predicate 
                                ( grantment grant ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( setting be ( symbol ( type data ) ) ) ) 
                            ( predicate 
                                ( certification certify ( symbol «bar» ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combination ( combinor ( combinand ( symbol ( type text ) ) 
                                                        expiration ) ) ) 
                                            ( combinor ( combinand ( symbol «bar» ) 
                                                    expiration ) ) 
                                            ( combinator or- ) ) ) 
                                    preposition 
                                    ( object ( symbol ( type binary ) ) ) ) ) 
                            ( predicate 
                                ( filing file ( symbol «bar» ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type data ) ) ) ) 
                            ( predicate 
                                ( setting be ( symbol ( type text ) ) ) ) 
                            ( predicate 
                                ( setting be ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( registration register ( symbol «bar» ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( registration register ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( declaration declare ( symbol ( type binary ) ) 
                                    ( expression ( combination ( combination ( combinor ( combinor ( combinor ( combinand ( symbol ( type person ) ) 
                                                                expiration ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol «bar» ) 
                                                                being true ) ) 
                                                        ( combinator or- ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression ( symbol «bar» ) ) 
                                                                                            ( time-unit weeks ) ) ) ) ) 
                                                                            ( time-unit seconds ) ) 
                                                                        ( symbol «bar» ) ) ) ) 
                                                            ( comparison-operator later ) 
                                                            ( scalar-expression ( symbol ( type text ) ) ) ) ) 
                                                    ( combinator nor ) ) ) 
                                            ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                    ( combinand ( symbol «bar» ) 
                                                        expiration ) 
                                                    ( combinator and ) ) 
                                                ( combinand 
                                                    ( point-in-time current-time ) ) 
                                                ( combinator or- ) ) ) ) ) ) ) 
                        permission 
                        ( condition if 
                            ( expression ( combination ( combination ( combinor ( combinand 
                                                ( scalar-comparison 
                                                    ( scalar-expression ( symbol «bar» ) ) 
                                                    ( comparison-operator equal ) 
                                                    ( scalar-expression 123 ) ) ) ) ) 
                                    ( combinor ( combinor ( combinand ( symbol «bar» ) 
                                                expiration ) ) 
                                        ( combinand expiration ) 
                                        ( combinator or- ) ) 
                                    ( combinator nor ) ) ) ) ) ) ) ) ) 
    ( covenants 
        ( covenant «foo-xyzzy» 
            ( provisions 
                ( definitions 
                    ( definition «foo-xyzzy» 
                        ( this-contract «bar» ) ) ) ) ) ) )
