( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «bar» 
                    ( this-contract «bar» ) ) ) 
            ( statements 
                ( statement 
                    ( flagging 
                        ( illocutor be ) 
                        ( symbol ( type time ) ) 
                        ( this-contract «bar» ) ) ) ) ) ) 
    ( covenants 
        ( covenant «garply» 
            ( provisions 
                ( definitions 
                    ( definition «garply» ( type amount ) ) 
                    ( definition «garply» 
                        ( this-contract «bar» ) ) ) ) ) ) )
