( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «bar» ( type data ) ) ) 
            ( statements 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols ( symbol «bar» ) ) ) 
                        ( predicates 
                            ( predicate 
                                ( notification notify 
                                    ( object reflexive ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combinor ( combinand ( symbol ( type person ) ) 
                                                        expiration ) ) ) 
                                            ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                ( existence ( symbol «bar» ) 
                                                                    be ) ) ) 
                                                        ( combinand 
                                                            ( point-in-time current-time ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand ( symbol «bar» ) 
                                                        expiration ) 
                                                    ( combinator or- ) ) 
                                                ( combinand ( symbol «bar» ) 
                                                    expiration ) 
                                                ( combinator and ) ) ) ) ) ) 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                                        ( combinand 
                                                                            ( existence ( symbol ( type binary ) ) 
                                                                                being true ) ) 
                                                                        ( combinator or- ) ) 
                                                                    ( combinand 
                                                                        ( existence ( symbol «bar» ) 
                                                                            be 
                                                                            ( contract all-contracts ) ) ) 
                                                                    ( combinator nor ) ) 
                                                                ( combinand expiration ) 
                                                                ( combinator and ) ) 
                                                            ( combinand ( symbol «bar» ) 
                                                                expiration ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol ( type data ) ) 
                                                                be ) ) 
                                                        ( combinator or- ) ) 
                                                    ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression ( symbol ( type text ) ) ) 
                                                                    ( time-unit milliseconds ) ) ) ) ) 
                                                    ( combinator or- ) ) 
                                                ( combinand 
                                                    ( point-in-time current-time ) ) 
                                                ( combinator neither ) ) ) ) 
                                    preposition 
                                    ( object reflexive ) 
                                    from-escrow ) ) 
                            ( predicate 
                                ( payment pay preposition 
                                    ( object reflexive ) 
                                    escrow ) ) 
                            ( predicate 
                                ( grantment grant ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type binary ) ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( termination terminate all-contracts ) ) 
                            ( predicate 
                                ( declaration declare ( symbol «bar» ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combinor ( combinand expiration ) ) ) ) 
                                    preposition 
                                    ( object reflexive ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combinor ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression ( symbol «bar» ) ) 
                                                                    ( time-unit years ) ) 
                                                                ( symbol ( type data ) ) ) ) ) ) ) 
                                            ( combinor ( combinor ( combinand expiration ) ) 
                                                ( combinand 
                                                    ( negation 
                                                        ( negator be ) 
                                                        ( symbol «bar» ) 
                                                        fixed ) ) 
                                                ( combinator neither ) ) 
                                            ( combinator neither ) ) ) ) ) 
                            ( predicate 
                                ( filing file ( symbol «bar» ) 
                                    ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                            ( combinand ( symbol ( type text ) ) 
                                                                expiration ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand expiration ) 
                                                        ( combinator or- ) ) ) 
                                                ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                            ( existence ( symbol «bar» ) 
                                                                                equal fixed ) ) ) 
                                                                    ( combinand expiration ) 
                                                                    ( combinator neither ) ) 
                                                                ( combinand 
                                                                    ( negation 
                                                                        ( negator be ) 
                                                                        ( symbol ( type data ) ) 
                                                                        ( contract 
                                                                            ( this-contract «bar» ) ) ) ) 
                                                                ( combinator nor ) ) 
                                                            ( combinand 
                                                                ( negation 
                                                                    ( negator ) 
                                                                    ( symbol «bar» ) 
                                                                    fixed ) ) 
                                                            ( combinator and ) ) 
                                                        ( combinand 
                                                            ( negation 
                                                                ( negator be ) 
                                                                ( symbol ( type person ) ) ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand 
                                                        ( existence ( symbol ( type person ) ) 
                                                            be ) ) 
                                                    ( combinator or- ) ) 
                                                ( combinator and ) ) 
                                            ( combinor ( combinand ( symbol «bar» ) ) ) ) ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol ( type text ) ) ) ) 
                            ( predicate 
                                ( setting be ( symbol ( type person ) ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «bar» ) 
                                    ( expression ( combination ( combination ( combinor ( combinor ( combinand 
                                                            ( point-in-time current-time ) ) ) 
                                                    ( combinand ( symbol ( type time ) ) 
                                                        expiration ) 
                                                    ( combinator or- ) ) ) 
                                            ( combinor ( combinand 
                                                    ( negation 
                                                        ( negator ) 
                                                        ( symbol ( type binary ) ) ) ) ) 
                                            ( combinator nor ) ) ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type amount ) ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «bar» ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type time ) ) ) ) ) 
                        permission 
                        ( condition if 
                            ( expression ( combination ( combinor ( combinor ( combinand expiration ) ) 
                                        ( combinand ( symbol ( type data ) ) ) 
                                        ( combinator and ) ) ) ) ) ) ) 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols 
                                ( symbols ( symbol «bar» ) ) 
                                ( symbol ( type amount ) ) 
                                catena ) ) 
                        ( predicates 
                            ( predicate 
                                ( fixture fix ( symbol ( type data ) ) ) ) 
                            ( predicate 
                                ( termination terminate all-contracts ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type text ) ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type data ) ) ) ) 
                            ( predicate 
                                ( setting be ( symbol ( type binary ) ) ) ) 
                            ( predicate 
                                ( payment pay preposition 
                                    ( object ( symbol «bar» ) ) 
                                    escrow ) ) 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combinor ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression 
                                                            ( point-in-time current-time ) ) 
                                                        ( comparison-operator equal ) 
                                                        ( scalar-expression ( symbol «bar» ) ) ) ) ) ) ) 
                                    preposition 
                                    ( object reflexive ) 
                                    from-escrow ) ) 
                            ( predicate 
                                ( registration register ( symbol «bar» ) 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combinor ( combinand 
                                                                    ( existence ( symbol ( type person ) ) 
                                                                        equal fixed ) ) ) ) 
                                                        ( combinor ( combinor ( combinand 
                                                                    ( negation 
                                                                        ( negator be ) 
                                                                        ( symbol «bar» ) ) ) ) 
                                                            ( combinand 
                                                                ( existence ( symbol ( type amount ) ) 
                                                                    equal fixed ) ) 
                                                            ( combinator neither ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinor ( combinor ( combinor ( combinand 
                                                                    ( negation 
                                                                        ( negator ) 
                                                                        ( symbol «bar» ) 
                                                                        fixed ) ) ) 
                                                            ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression ( symbol ( type text ) ) ) 
                                                                    ( comparison-operator equal ) 
                                                                    ( scalar-expression 
                                                                        ( point-in-time current-time ) ) ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol ( type amount ) ) 
                                                                be ) ) 
                                                        ( combinator neither ) ) ) 
                                                ( combinor ( combinand ( symbol «bar» ) 
                                                        expiration ) ) 
                                                ( combinator and ) ) 
                                            ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                    ( negation 
                                                                        ( negator ) 
                                                                        ( symbol «bar» ) 
                                                                        ( contract all-contracts ) ) ) ) 
                                                            ( combinand 
                                                                ( existence ( symbol «bar» ) 
                                                                    be ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand ( symbol «bar» ) 
                                                            expiration ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand 
                                                        ( point-in-time current-time ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinand 
                                                    ( negation 
                                                        ( negator be ) 
                                                        ( symbol «bar» ) ) ) 
                                                ( combinator and ) ) 
                                            ( combinator nor ) ) ) ) ) 
                            ( predicate 
                                ( declaration declare ( symbol «bar» ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( declaration declare ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol «bar» ) ) ) ) ) ) ) ) ) 
    ( covenants 
        ( covenant «garply-qux» 
            ( provisions 
                ( definitions 
                    ( definition «garply-qux» 
                        ( this-contract «bar» ) ) ) ) ) 
        ( covenant «garply-qux» 
            ( provisions 
                ( definitions 
                    ( definition «garply-qux» 
                        ( this-contract «bar» ) ) 
                    ( definition «garply-qux» 
                        ( this-contract «bar» ) ) 
                    ( definition «garply-qux» ( type data ) ) ) ) ) 
        ( covenant «garply-qux» 
            ( provisions 
                ( definitions 
                    ( definition «garply-qux» 
                        ( this-contract «bar» ) ) 
                    ( definition «garply-qux» 
                        ( this-contract «bar» ) ) ) 
                ( statements 
                    ( statement 
                        ( flagging 
                            ( illocutor be ) 
                            ( symbol ( type text ) ) 
                            ( this-contract «bar» ) ) ) 
                    ( statement 
                        ( flagging 
                            ( illocutor be ) 
                            ( symbol «garply-qux» ) ) ) ) ) ) ) )
