( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «bar» 
                    ( this-contract «bar» ) ) 
                ( definition «bar» ( type person ) ) ) 
            ( statements 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols 
                                ( symbols 
                                    ( symbols ( symbol «bar» ) ) 
                                    ( symbol ( type person ) ) 
                                    catena ) 
                                ( symbol «bar» ) 
                                catena ) ) 
                        ( predicates 
                            ( predicate 
                                ( declaration declare ( symbol ( type data ) ) 
                                    ( expression ( combination ( combinor ( combinand 
                                                    ( negation 
                                                        ( negator be ) 
                                                        ( symbol ( type time ) ) ) ) ) ) ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type time ) ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type text ) ) ) ) 
                            ( predicate 
                                ( filing file ( symbol «bar» ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( termination terminate 
                                    ( this-contract «bar» ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type amount ) ) 
                                    ( expression ( combination ( combinor ( combinand 
                                                    ( negation 
                                                        ( negator be ) 
                                                        ( symbol «bar» ) 
                                                        ( contract all-contracts ) ) ) ) ) ) ) ) 
                            ( predicate 
                                ( termination terminate all-contracts ) ) 
                            ( predicate 
                                ( registration register ( symbol ( type amount ) ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combination ( combinor ( combinand ( symbol «bar» ) ) ) ) 
                                                            ( combinor ( combinand expiration ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol ( type person ) ) ) ) 
                                                                    ( combinand ( symbol ( type data ) ) 
                                                                        expiration ) 
                                                                    ( combinator nor ) ) 
                                                                ( combinand ( symbol ( type data ) ) ) 
                                                                ( combinator neither ) ) 
                                                            ( combinand ( symbol «bar» ) 
                                                                expiration ) 
                                                            ( combinator nor ) ) ) 
                                                    ( combinor ( combinand ( symbol ( type binary ) ) ) ) ) 
                                                ( combinor ( combinand ( symbol «bar» ) 
                                                        expiration ) ) ) 
                                            ( combinor ( combinand ( symbol «bar» ) 
                                                    expiration ) ) 
                                            ( combinator and ) ) ) 
                                    preposition 
                                    ( object ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «bar» ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( registration register ( symbol «bar» ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type person ) ) 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                        ( negation 
                                                                                            ( negator be ) 
                                                                                            ( symbol «bar» ) ) ) ) 
                                                                                ( combinand ( symbol «bar» ) 
                                                                                    expiration ) 
                                                                                ( combinator or- ) ) 
                                                                            ( combinand 
                                                                                ( point-in-time current-time ) ) 
                                                                            ( combinator nor ) ) 
                                                                        ( combinand ( symbol «bar» ) ) 
                                                                        ( combinator neither ) ) 
                                                                    ( combinand 
                                                                        ( point-in-time current-time ) ) 
                                                                    ( combinator and ) ) ) 
                                                            ( combinor ( combinand ( symbol «bar» ) 
                                                                    expiration ) ) 
                                                            ( combinator or- ) ) 
                                                        ( combinor ( combinand 
                                                                ( negation 
                                                                    ( negator be ) 
                                                                    ( symbol ( type amount ) ) 
                                                                    fixed ) ) ) ) 
                                                    ( combinor ( combinand 
                                                            ( existence ( symbol «bar» ) 
                                                                equal fixed ) ) ) 
                                                    ( combinator or- ) ) 
                                                ( combinor ( combinor ( combinor ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression ( symbol «bar» ) ) 
                                                                    ( comparison-operator equal ) 
                                                                    ( scalar-expression 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression 
                                                                                        ( point-in-time current-time ) ) 
                                                                                    ( time-unit seconds ) ) ) ) ) ) ) ) 
                                                        ( combinand 
                                                            ( point-in-time 
                                                                ( relative-time 
                                                                    ( duration 
                                                                        ( scalar-expression ( symbol ( type binary ) ) ) 
                                                                        ( time-unit milliseconds ) ) ) ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand 
                                                        ( point-in-time current-time ) ) 
                                                    ( combinator nor ) ) 
                                                ( combinator nor ) ) 
                                            ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                    ( scalar-comparison 
                                                                                        ( scalar-expression 
                                                                                            ( point-in-time 
                                                                                                ( relative-time 
                                                                                                    ( duration 
                                                                                                        ( scalar-expression 123 ) 
                                                                                                        ( time-unit days ) ) ) ) ) 
                                                                                        ( comparison-operator equal ) 
                                                                                        ( scalar-expression ( symbol «bar» ) ) ) ) ) 
                                                                            ( combinand 
                                                                                ( existence ( symbol ( type data ) ) 
                                                                                    be ) ) 
                                                                            ( combinator nor ) ) 
                                                                        ( combinand expiration ) 
                                                                        ( combinator or- ) ) 
                                                                    ( combinand 
                                                                        ( point-in-time current-time ) ) 
                                                                    ( combinator nor ) ) 
                                                                ( combinand ( symbol «bar» ) 
                                                                    expiration ) 
                                                                ( combinator and ) ) 
                                                            ( combinand 
                                                                ( negation 
                                                                    ( negator be ) 
                                                                    ( symbol «bar» ) ) ) 
                                                            ( combinator and ) ) 
                                                        ( combinand ( symbol ( type text ) ) 
                                                            expiration ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand 
                                                        ( negation 
                                                            ( negator ) 
                                                            ( symbol ( type text ) ) ) ) 
                                                    ( combinator and ) ) 
                                                ( combinand ( symbol «bar» ) 
                                                    expiration ) 
                                                ( combinator and ) ) ) ) ) ) 
                            ( predicate 
                                ( registration register ( symbol ( type text ) ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( registration register ( symbol ( type time ) ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combinor ( combinor ( combinor ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression ( symbol «bar» ) ) 
                                                                    ( comparison-operator later ) 
                                                                    ( scalar-expression 123 ) ) ) ) 
                                                        ( combinand 
                                                            ( point-in-time 
                                                                ( relative-time 
                                                                    ( duration 
                                                                        ( scalar-expression 
                                                                            ( point-in-time current-time ) ) 
                                                                        ( time-unit milliseconds ) ) ) ) ) 
                                                        ( combinator and ) ) 
                                                    ( combinand 
                                                        ( existence ( symbol ( type text ) ) 
                                                            equal fixed ) ) 
                                                    ( combinator nor ) ) ) 
                                            ( combinor ( combinand ( symbol ( type amount ) ) 
                                                    expiration ) ) 
                                            ( combinator and ) ) ) ) ) 
                            ( predicate 
                                ( payment pay preposition 
                                    ( object ) 
                                    escrow ) ) 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combination ( combinor ( combinand ( symbol ( type data ) ) 
                                                        expiration ) ) ) 
                                            ( combinor ( combinor ( combinand 
                                                        ( existence ( symbol «bar» ) 
                                                            be ) ) ) 
                                                ( combinand 
                                                    ( negation 
                                                        ( negator be ) 
                                                        ( symbol ( type person ) ) ) ) 
                                                ( combinator nor ) ) 
                                            ( combinator neither ) ) ) 
                                    preposition 
                                    ( object reflexive ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol ( type amount ) ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol ( type text ) ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type binary ) ) 
                                    ( expression ( combination ( combination ( combinor ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression 123 ) 
                                                                                    ( time-unit weeks ) ) 
                                                                                ( symbol ( type data ) ) ) ) ) 
                                                                    ( time-unit seconds ) ) ) ) ) ) ) 
                                            ( combinor ( combinand 
                                                    ( point-in-time current-time ) ) ) 
                                            ( combinator or- ) ) ) ) ) 
                            ( predicate 
                                ( declaration declare ( symbol ( type text ) ) 
                                    ( expression ( combination ( combination ( combination ( combination ( combinor ( combinand 
                                                                ( point-in-time current-time ) ) ) ) 
                                                    ( combinor ( combinor ( combinand 
                                                                ( existence ( symbol «bar» ) 
                                                                    equal fixed ) ) ) 
                                                        ( combinand expiration ) 
                                                        ( combinator and ) ) 
                                                    ( combinator or- ) ) 
                                                ( combinor ( combinand 
                                                        ( negation 
                                                            ( negator ) 
                                                            ( symbol «bar» ) 
                                                            ( contract 
                                                                ( this-contract «bar» ) ) ) ) ) ) 
                                            ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                    ( combinand ( symbol ( type amount ) ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinand 
                                                    ( negation 
                                                        ( negator ) 
                                                        ( symbol «bar» ) 
                                                        fixed ) ) 
                                                ( combinator neither ) ) ) ) ) ) 
                            ( predicate 
                                ( termination terminate 
                                    ( this-contract «bar» ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combinor ( combinand 
                                                        ( existence ( symbol «bar» ) 
                                                            be 
                                                            ( contract all-contracts ) ) ) ) ) 
                                            ( combinor ( combinor ( combinor ( combinand 
                                                            ( point-in-time current-time ) ) ) 
                                                    ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression ( symbol «bar» ) ) 
                                                                    ( time-unit weeks ) ) 
                                                                ( symbol «bar» ) ) ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinand expiration ) 
                                                ( combinator neither ) ) ) ) ) ) 
                            ( predicate 
                                ( payment pay preposition 
                                    ( object ( symbol ( type text ) ) ) 
                                    escrow ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combinor ( combinand 
                                                    ( point-in-time current-time ) ) ) ) ) 
                                    preposition 
                                    ( object ( symbol ( type data ) ) ) ) ) 
                            ( predicate 
                                ( declaration declare ( symbol ( type data ) ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol ( type time ) ) ) ) 
                            ( predicate 
                                ( termination terminate all-contracts ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol ( type binary ) ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) ) 
                        permission 
                        ( condition if 
                            ( expression ( combination ( combinor ( combinor ( combinand ( symbol ( type amount ) ) ) ) 
                                        ( combinand ( symbol «bar» ) 
                                            expiration ) 
                                        ( combinator nor ) ) ) ) ) ) ) ) ) ) 
    ( covenants 
        ( covenant «garply» 
            ( provisions 
                ( definitions 
                    ( definition «garply» ( type data ) ) ) ) ) 
        ( covenant «garply» 
            ( provisions 
                ( definitions 
                    ( definition «garply» ( type data ) ) ) 
                ( clauses 
                    ( clause «garply-grault-bar» 
                        ( body 
                            ( function «garply-grault-bar» 
                                ( illocutor be ) 
                                ( expression ( combination ( combination ( combinor ( combinand 
                                                    ( point-in-time 
                                                        ( relative-time 
                                                            ( duration 
                                                                ( scalar-expression 123 ) 
                                                                ( time-unit minutes ) ) ) ) ) ) ) 
                                        ( combinor ( combinand 
                                                ( existence ( symbol «garply-grault-bar» ) 
                                                    be ) ) ) ) ) ) ) ) 
                    ( clause «fred» 
                        ( body 
                            ( statements 
                                ( statement 
                                    ( flagging 
                                        ( illocutor be ) 
                                        ( symbol ( type amount ) ) ) ) ) ) ) 
                    ( clause «plugh-grault» 
                        ( body 
                            ( function «plugh-grault» 
                                ( illocutor be ) 
                                ( expression ( combination ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol ( type person ) ) ) ) 
                                                        ( combinand ( symbol «plugh-grault» ) 
                                                            expiration ) 
                                                        ( combinator or- ) ) 
                                                    ( combinand 
                                                        ( negation 
                                                            ( negator be ) 
                                                            ( symbol «plugh-grault» ) 
                                                            ( contract all-contracts ) ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression 
                                                            ( point-in-time current-time ) ) 
                                                        ( comparison-operator equal ) 
                                                        ( scalar-expression 
                                                            ( point-in-time current-time ) ) ) ) 
                                                ( combinator neither ) ) 
                                            ( combinand 
                                                ( negation 
                                                    ( negator ) 
                                                    ( symbol «plugh-grault» ) ) ) 
                                            ( combinator neither ) ) ) ) ) ) ) ) 
                ( statements 
                    ( statement 
                        ( flagging 
                            ( illocutor be ) 
                            ( symbol «garply» ) ) ) 
                    ( statement 
                        ( flagging 
                            ( illocutor be ) 
                            ( symbol ( type time ) ) ) ) ) ) ) ) )
