( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «bar» ( type time ) ) ) 
            ( statements 
                ( statement 
                    ( flagging 
                        ( illocutor be ) 
                        ( symbol ( type person ) ) 
                        ( this-contract «bar» ) ) ) ) ) ) 
    ( covenants 
        ( covenant «qux-baz» 
            ( provisions 
                ( definitions 
                    ( definition «qux-baz» ( type amount ) ) ) 
                ( clauses 
                    ( clause «corge» 
                        ( body 
                            ( function «corge» 
                                ( illocutor be ) 
                                ( expression ( combination ( combination ( combination ( combination ( combinor ( combinand 
                                                            ( scalar-comparison 
                                                                ( scalar-expression 123 ) 
                                                                ( comparison-operator later ) 
                                                                ( scalar-expression 
                                                                    ( point-in-time 
                                                                        ( relative-time 
                                                                            ( duration 
                                                                                ( scalar-expression 123 ) 
                                                                                ( time-unit minutes ) ) 
                                                                            ( symbol ( type data ) ) ) ) ) ) ) ) ) 
                                                ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                        ( combinand ( symbol «corge» ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand ( symbol ( type text ) ) 
                                                        expiration ) 
                                                    ( combinator and ) ) 
                                                ( combinator or- ) ) 
                                            ( combinor ( combinand ( symbol «corge» ) 
                                                    expiration ) ) 
                                            ( combinator nor ) ) 
                                        ( combinor ( combinor ( combinand ( symbol «corge» ) 
                                                    expiration ) ) 
                                            ( combinand 
                                                ( existence ( symbol ( type binary ) ) 
                                                    be ) ) 
                                            ( combinator and ) ) 
                                        ( combinator neither ) ) ) ) ) ) ) 
                ( statements 
                    ( statement 
                        ( flagging 
                            ( illocutor be ) 
                            ( symbol ( type time ) ) 
                            ( this-contract «bar» ) ) ) 
                    ( statement 
                        ( action 
                            ( subject 
                                ( symbols 
                                    ( symbols 
                                        ( symbols 
                                            ( symbols ( symbol ( type binary ) ) ) 
                                            ( symbol ( type text ) ) 
                                            catena ) 
                                        ( symbol «qux-baz» ) 
                                        catena ) 
                                    ( symbol «qux-baz» ) 
                                    catena ) ) 
                            ( predicates 
                                ( predicate 
                                    ( registration register ( symbol ( type amount ) ) 
                                        ( contract 
                                            ( this-contract «bar» ) ) ) ) 
                                ( predicate 
                                    ( payment pay 
                                        ( expression ( combination ( combinor ( combinor ( combinand 
                                                            ( scalar-comparison 
                                                                ( scalar-expression ( symbol ( type binary ) ) ) 
                                                                ( comparison-operator equal ) 
                                                                ( scalar-expression 
                                                                    ( point-in-time current-time ) ) ) ) ) 
                                                    ( combinand expiration ) 
                                                    ( combinator and ) ) ) ) 
                                        preposition 
                                        ( object reflexive ) ) ) 
                                ( predicate 
                                    ( declaration declare ( symbol «qux-baz» ) ) ) 
                                ( predicate 
                                    ( termination terminate 
                                        ( this-contract «bar» ) ) ) 
                                ( predicate 
                                    ( certification certify ( symbol «qux-baz» ) 
                                        ( expression ( combination ( combination ( combinor ( combinand 
                                                            ( negation 
                                                                ( negator be ) 
                                                                ( symbol «qux-baz» ) ) ) ) ) 
                                                ( combinor ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression 123 ) 
                                                            ( comparison-operator equal ) 
                                                            ( scalar-expression 123 ) ) ) ) ) ) ) ) 
                                ( predicate 
                                    ( appointment appoint ( symbol ( type binary ) ) ) ) 
                                ( predicate 
                                    ( sending send 
                                        ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinand ( symbol ( type binary ) ) ) ) 
                                                            ( combinand expiration ) 
                                                            ( combinator or- ) ) ) 
                                                    ( combinor ( combinor ( combinor ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression ( symbol «qux-baz» ) ) 
                                                                        ( comparison-operator equal ) 
                                                                        ( scalar-expression ( symbol «qux-baz» ) ) ) ) ) 
                                                            ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression 123 ) 
                                                                    ( comparison-operator equal ) 
                                                                    ( scalar-expression 
                                                                        ( point-in-time current-time ) ) ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand 
                                                            ( point-in-time current-time ) ) 
                                                        ( combinator and ) ) ) 
                                                ( combinor ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression 123 ) 
                                                                    ( time-unit days ) ) ) ) ) ) 
                                                ( combinator and ) ) ) 
                                        preposition 
                                        ( object ) ) ) 
                                ( predicate 
                                    ( declaration declare ( symbol «qux-baz» ) 
                                        ( expression ( combination ( combination ( combinor ( combinand expiration ) ) ) 
                                                ( combinor ( combinand ( symbol ( type time ) ) ) ) ) ) ) ) 
                                ( predicate 
                                    ( grantment grant ( symbol «qux-baz» ) ) ) 
                                ( predicate 
                                    ( certification certify ( symbol ( type time ) ) 
                                        ( contract 
                                            ( this-contract «bar» ) ) ) ) 
                                ( predicate 
                                    ( setting be ( symbol «qux-baz» ) ) ) 
                                ( predicate 
                                    ( payment pay preposition 
                                        ( object ) 
                                        escrow ) ) 
                                ( predicate 
                                    ( grantment grant ( symbol «qux-baz» ) ) ) 
                                ( predicate 
                                    ( grantment grant ( symbol «qux-baz» ) ) ) 
                                ( predicate 
                                    ( termination terminate all-contracts ) ) 
                                ( predicate 
                                    ( setting be ( symbol ( type person ) ) ) ) 
                                ( predicate 
                                    ( termination terminate 
                                        ( this-contract «bar» ) ) ) 
                                ( predicate 
                                    ( declaration declare ( symbol «qux-baz» ) 
                                        ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinand 
                                                                        ( scalar-comparison 
                                                                            ( scalar-expression ( symbol «qux-baz» ) ) 
                                                                            ( comparison-operator later ) 
                                                                            ( scalar-expression 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression 123 ) 
                                                                                            ( time-unit days ) ) 
                                                                                        ( symbol «qux-baz» ) ) ) ) ) ) ) 
                                                                ( combinand 
                                                                    ( point-in-time 
                                                                        ( relative-time 
                                                                            ( duration 
                                                                                ( scalar-expression 123 ) 
                                                                                ( time-unit minutes ) ) ) ) ) 
                                                                ( combinator nor ) ) 
                                                            ( combinand 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression 123 ) 
                                                                                            ( time-unit weeks ) ) 
                                                                                        ( symbol «qux-baz» ) ) ) ) 
                                                                            ( time-unit milliseconds ) ) 
                                                                        ( symbol ( type data ) ) ) ) ) 
                                                            ( combinator neither ) ) ) 
                                                    ( combinor ( combinand ( symbol ( type text ) ) 
                                                            expiration ) ) ) 
                                                ( combinor ( combinand ( symbol ( type data ) ) ) ) ) ) ) ) 
                                ( predicate 
                                    ( sending send 
                                        ( expression ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinand 
                                                                            ( negation 
                                                                                ( negator be ) 
                                                                                ( symbol ( type text ) ) ) ) ) 
                                                                    ( combinand expiration ) 
                                                                    ( combinator neither ) ) 
                                                                ( combinand 
                                                                    ( negation 
                                                                        ( negator ) 
                                                                        ( symbol ( type data ) ) ) ) 
                                                                ( combinator and ) ) ) 
                                                        ( combinor ( combinand ( symbol «qux-baz» ) 
                                                                expiration ) ) 
                                                        ( combinator or- ) ) 
                                                    ( combinor ( combinor ( combinor ( combinand 
                                                                    ( point-in-time current-time ) ) ) 
                                                            ( combinand 
                                                                ( negation 
                                                                    ( negator ) 
                                                                    ( symbol «qux-baz» ) 
                                                                    fixed ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand 
                                                            ( negation 
                                                                ( negator be ) 
                                                                ( symbol ( type text ) ) 
                                                                ( contract all-contracts ) ) ) 
                                                        ( combinator and ) ) ) 
                                                ( combinor ( combinor ( combinand 
                                                            ( point-in-time current-time ) ) ) 
                                                    ( combinand 
                                                        ( existence ( symbol «qux-baz» ) 
                                                            being true ) ) 
                                                    ( combinator or- ) ) ) ) 
                                        preposition 
                                        ( object reflexive ) ) ) 
                                ( predicate 
                                    ( registration register ( symbol ( type binary ) ) 
                                        ( contract 
                                            ( this-contract «bar» ) ) ) ) ) 
                            permission 
                            ( condition if 
                                ( expression ( combination ( combinor ( combinor ( combinor ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression 123 ) 
                                                                    ( time-unit years ) ) 
                                                                ( symbol «qux-baz» ) ) ) ) ) 
                                                ( combinand expiration ) 
                                                ( combinator neither ) ) 
                                            ( combinand expiration ) 
                                            ( combinator neither ) ) ) ) ) ) ) ) ) ) 
        ( covenant «corge» 
            ( provisions 
                ( definitions 
                    ( definition «corge» 
                        ( this-contract «bar» ) ) ) ) ) 
        ( covenant «corge» 
            ( provisions 
                ( definitions 
                    ( definition «corge» 
                        ( this-contract «bar» ) ) ) ) ) 
        ( covenant «corge» 
            ( provisions 
                ( definitions 
                    ( definition «corge» 
                        ( this-contract «bar» ) ) 
                    ( definition «corge» ( type amount ) ) ) 
                ( statements 
                    ( statement 
                        ( action 
                            ( subject 
                                ( symbols 
                                    ( symbols 
                                        ( symbols ( symbol «corge» ) ) 
                                        ( symbol «corge» ) 
                                        catena ) 
                                    ( symbol ( type data ) ) 
                                    catena ) ) 
                            ( predicates 
                                ( predicate 
                                    ( certification certify ( symbol «corge» ) 
                                        ( expression ( combination ( combination ( combinor ( combinand 
                                                            ( point-in-time 
                                                                ( relative-time 
                                                                    ( duration 
                                                                        ( scalar-expression ( symbol ( type data ) ) ) 
                                                                        ( time-unit milliseconds ) ) 
                                                                    ( symbol ( type amount ) ) ) ) ) ) ) 
                                                ( combinor ( combinand ( symbol «corge» ) ) ) 
                                                ( combinator neither ) ) ) ) ) 
                                ( predicate 
                                    ( fixture fix ( symbol «corge» ) 
                                        ( contract 
                                            ( this-contract «bar» ) ) ) ) 
                                ( predicate 
                                    ( declaration declare ( symbol «corge» ) 
                                        ( expression ( combination ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinand expiration ) ) 
                                                                    ( combinand ( symbol ( type person ) ) 
                                                                        expiration ) 
                                                                    ( combinator or- ) ) ) 
                                                            ( combinor ( combinand expiration ) ) ) 
                                                        ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                        ( existence ( symbol ( type text ) ) 
                                                                                            be 
                                                                                            ( contract 
                                                                                                ( this-contract «bar» ) ) ) ) ) 
                                                                                ( combinand 
                                                                                    ( negation 
                                                                                        ( negator ) 
                                                                                        ( symbol ( type data ) ) ) ) 
                                                                                ( combinator nor ) ) 
                                                                            ( combinand 
                                                                                ( negation 
                                                                                    ( negator be ) 
                                                                                    ( symbol «corge» ) ) ) 
                                                                            ( combinator and ) ) 
                                                                        ( combinand 
                                                                            ( point-in-time current-time ) ) 
                                                                        ( combinator neither ) ) 
                                                                    ( combinand ( symbol ( type text ) ) 
                                                                        expiration ) 
                                                                    ( combinator or- ) ) 
                                                                ( combinand 
                                                                    ( negation 
                                                                        ( negator be ) 
                                                                        ( symbol ( type binary ) ) 
                                                                        ( contract all-contracts ) ) ) 
                                                                ( combinator or- ) ) 
                                                            ( combinand ( symbol «corge» ) ) 
                                                            ( combinator nor ) ) ) 
                                                    ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                            ( combinand ( symbol ( type person ) ) 
                                                                expiration ) 
                                                            ( combinator neither ) ) 
                                                        ( combinand 
                                                            ( point-in-time 
                                                                ( relative-time 
                                                                    ( duration 
                                                                        ( scalar-expression 123 ) 
                                                                        ( time-unit hours ) ) 
                                                                    ( symbol «corge» ) ) ) ) 
                                                        ( combinator and ) ) ) 
                                                ( combinor ( combinor ( combinor ( combinand ( symbol ( type amount ) ) ) ) 
                                                        ( combinand 
                                                            ( point-in-time 
                                                                ( relative-time 
                                                                    ( duration 
                                                                        ( scalar-expression 123 ) 
                                                                        ( time-unit minutes ) ) ) ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression 123 ) 
                                                            ( comparison-operator equal ) 
                                                            ( scalar-expression 123 ) ) ) 
                                                    ( combinator or- ) ) ) ) ) ) 
                                ( predicate 
                                    ( sending send 
                                        ( expression ( combination ( combination ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                            ( combinand 
                                                                ( existence ( symbol ( type binary ) ) 
                                                                    be ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand expiration ) 
                                                        ( combinator or- ) ) ) 
                                                ( combinor ( combinor ( combinand ( symbol ( type data ) ) ) ) 
                                                    ( combinand 
                                                        ( point-in-time current-time ) ) 
                                                    ( combinator neither ) ) ) ) 
                                        preposition 
                                        ( object reflexive ) ) ) 
                                ( predicate 
                                    ( sending send 
                                        ( expression ( combination ( combinor ( combinor ( combinand 
                                                            ( point-in-time 
                                                                ( relative-time 
                                                                    ( duration 
                                                                        ( scalar-expression 
                                                                            ( point-in-time current-time ) ) 
                                                                        ( time-unit days ) ) ) ) ) ) 
                                                    ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression ( symbol ( type time ) ) ) 
                                                                                    ( time-unit months ) ) ) ) ) 
                                                                    ( time-unit years ) ) ) ) ) 
                                                    ( combinator or- ) ) ) ) 
                                        preposition 
                                        ( object ) ) ) 
                                ( predicate 
                                    ( payment pay preposition 
                                        ( object ( symbol «corge» ) ) 
                                        escrow ) ) 
                                ( predicate 
                                    ( grantment grant ( symbol ( type time ) ) ) ) 
                                ( predicate 
                                    ( certification certify ( symbol «corge» ) 
                                        ( contract all-contracts ) ) ) 
                                ( predicate 
                                    ( notification notify 
                                        ( object ) 
                                        preposition 
                                        ( expression ( combination ( combination ( combination ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                            ( point-in-time 
                                                                                                ( relative-time 
                                                                                                    ( duration 
                                                                                                        ( scalar-expression 123 ) 
                                                                                                        ( time-unit milliseconds ) ) 
                                                                                                    ( symbol «corge» ) ) ) ) ) 
                                                                                    ( combinand 
                                                                                        ( point-in-time current-time ) ) 
                                                                                    ( combinator nor ) ) 
                                                                                ( combinand 
                                                                                    ( negation 
                                                                                        ( negator ) 
                                                                                        ( symbol ( type binary ) ) 
                                                                                        fixed ) ) 
                                                                                ( combinator and ) ) 
                                                                            ( combinand 
                                                                                ( negation 
                                                                                    ( negator ) 
                                                                                    ( symbol «corge» ) ) ) 
                                                                            ( combinator or- ) ) ) 
                                                                    ( combinor ( combinand 
                                                                            ( point-in-time 
                                                                                ( relative-time 
                                                                                    ( duration 
                                                                                        ( scalar-expression ( symbol «corge» ) ) 
                                                                                        ( time-unit weeks ) ) 
                                                                                    ( symbol «corge» ) ) ) ) ) ) 
                                                                ( combinor ( combinand 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression 123 ) 
                                                                                    ( time-unit days ) ) ) ) ) ) ) 
                                                            ( combinor ( combinand 
                                                                    ( point-in-time 
                                                                        ( relative-time 
                                                                            ( duration 
                                                                                ( scalar-expression 123 ) 
                                                                                ( time-unit milliseconds ) ) 
                                                                            ( symbol «corge» ) ) ) ) ) ) 
                                                        ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                                ( combinand ( symbol «corge» ) ) 
                                                                ( combinator and ) ) 
                                                            ( combinand ( symbol ( type binary ) ) ) 
                                                            ( combinator and ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinor ( combinand ( symbol ( type time ) ) 
                                                            expiration ) ) 
                                                    ( combinator nor ) ) 
                                                ( combinor ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression 
                                                                        ( point-in-time current-time ) ) 
                                                                    ( time-unit hours ) ) 
                                                                ( symbol «corge» ) ) ) ) ) ) ) ) ) 
                                ( predicate 
                                    ( fixture fix ( symbol ( type text ) ) ) ) 
                                ( predicate 
                                    ( appointment appoint ( symbol «corge» ) ) ) 
                                ( predicate 
                                    ( declaration declare ( symbol ( type text ) ) ) ) 
                                ( predicate 
                                    ( registration register ( symbol ( type data ) ) ) ) 
                                ( predicate 
                                    ( termination terminate all-contracts ) ) ) 
                            permission 
                            ( condition if 
                                ( expression ( combination ( combination ( combination ( combination ( combinor ( combinand 
                                                            ( negation 
                                                                ( negator ) 
                                                                ( symbol «corge» ) ) ) ) ) 
                                                ( combinor ( combinor ( combinor ( combinand 
                                                                ( negation 
                                                                    ( negator be ) 
                                                                    ( symbol ( type binary ) ) ) ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol «corge» ) 
                                                                be ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand 
                                                        ( negation 
                                                            ( negator ) 
                                                            ( symbol ( type time ) ) 
                                                            ( contract all-contracts ) ) ) 
                                                    ( combinator or- ) ) 
                                                ( combinator or- ) ) 
                                            ( combinor ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression ( symbol «corge» ) ) 
                                                        ( comparison-operator equal ) 
                                                        ( scalar-expression 123 ) ) ) ) ) 
                                        ( combinor ( combinand 
                                                ( point-in-time current-time ) ) ) ) ) ) ) ) ) ) ) ) )
