( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «bar» ( type person ) ) ) 
            ( statements 
                ( statement 
                    ( flagging 
                        ( illocutor be ) 
                        ( symbol ( type time ) ) ) ) ) ) ) 
    ( covenants 
        ( covenant «baz» 
            ( provisions 
                ( definitions 
                    ( definition «baz» ( type data ) ) 
                    ( definition «baz» 
                        ( this-contract «bar» ) ) ) 
                ( clauses 
                    ( clause «baz-fred» 
                        ( body 
                            ( function «baz-fred» 
                                ( illocutor be ) 
                                ( expression ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinand 
                                                                ( existence ( symbol ( type data ) ) 
                                                                    being true ) ) ) 
                                                        ( combinand ( symbol ( type text ) ) 
                                                            expiration ) 
                                                        ( combinator and ) ) ) 
                                                ( combinor ( combinand 
                                                        ( negation 
                                                            ( negator ) 
                                                            ( symbol ( type binary ) ) ) ) ) ) 
                                            ( combinor ( combinor ( combinor ( combinand ( symbol ( type amount ) ) ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression 123 ) 
                                                            ( comparison-operator later ) 
                                                            ( scalar-expression ( symbol ( type text ) ) ) ) ) 
                                                    ( combinator or- ) ) 
                                                ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression 
                                                            ( point-in-time current-time ) ) 
                                                        ( comparison-operator later ) 
                                                        ( scalar-expression ( symbol ( type data ) ) ) ) ) 
                                                ( combinator nor ) ) 
                                            ( combinator and ) ) 
                                        ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                ( combinand ( symbol ( type amount ) ) 
                                                    expiration ) 
                                                ( combinator neither ) ) 
                                            ( combinand expiration ) 
                                            ( combinator or- ) ) ) ) ) ) ) ) ) ) 
        ( covenant «baz-fred» 
            ( provisions 
                ( definitions 
                    ( definition «baz-fred» ( type amount ) ) ) 
                ( clauses 
                    ( clause «corge» 
                        ( body 
                            ( statements 
                                ( statement 
                                    ( flagging 
                                        ( illocutor be ) 
                                        ( symbol ( type amount ) ) ) ) ) ) ) ) ) ) 
        ( covenant «corge» 
            ( provisions 
                ( definitions 
                    ( definition «corge» ( type time ) ) 
                    ( definition «corge» ( type person ) ) ) 
                ( statements 
                    ( statement 
                        ( flagging 
                            ( illocutor be ) 
                            ( symbol «corge» ) ) ) 
                    ( statement 
                        ( flagging 
                            ( illocutor be ) 
                            ( symbol ( type time ) ) ) ) ) ) ) ) )
