	%token A
	%token Appoint
	%token Appointment_Predicate
	%token Appoints
	%token Be
	%token Mean
	%token Party
	%token Somebody
	%token To
	
	Appointment_Predicate:	
		  Appoints Somebody Be A Party                    { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoints Somebody Mean A Party                  { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoints Somebody To Be A Party                 { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoints Somebody To Mean A Party               { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoint Somebody Be A Party                     { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoint Somebody Mean A Party                   { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoint Somebody To Be A Party                  { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoint Somebody To Mean A Party                { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
