( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «bar» ( type data ) ) ) 
            ( statements 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols ( symbol «bar» ) ) ) 
                        ( predicates 
                            ( predicate 
                                ( notification notify 
                                    ( object reflexive ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combinor ( combinand ( symbol ( type person ) ) 
                                                        expiration ) ) ) 
                                            ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                ( existence ( symbol «bar» ) 
                                                                    be ) ) ) 
                                                        ( combinand 
                                                            ( point-in-time current-time ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand ( symbol «bar» ) 
                                                        expiration ) 
                                                    ( combinator or- ) ) 
                                                ( combinand ( symbol «bar» ) 
                                                    expiration ) 
                                                ( combinator and ) ) ) ) ) ) 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                                        ( combinand 
                                                                            ( existence ( symbol ( type binary ) ) 
                                                                                being true ) ) 
                                                                        ( combinator or- ) ) 
                                                                    ( combinand 
                                                                        ( existence ( symbol «bar» ) 
                                                                            be 
                                                                            ( contract all-contracts ) ) ) 
                                                                    ( combinator nor ) ) 
                                                                ( combinand expiration ) 
                                                                ( combinator and ) ) 
                                                            ( combinand ( symbol «bar» ) 
                                                                expiration ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol ( type data ) ) 
                                                                be ) ) 
                                                        ( combinator or- ) ) 
                                                    ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression ( symbol ( type text ) ) ) 
                                                                    ( time-unit milliseconds ) ) ) ) ) 
                                                    ( combinator or- ) ) 
                                                ( combinand 
                                                    ( point-in-time current-time ) ) 
                                                ( combinator neither ) ) ) ) 
                                    preposition 
                                    ( object reflexive ) 
                                    from-escrow ) ) 
                            ( predicate 
                                ( payment pay preposition 
                                    ( object reflexive ) 
                                    escrow ) ) 
                            ( predicate 
                                ( grantment grant ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type binary ) ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( termination terminate all-contracts ) ) 
                            ( predicate 
                                ( declaration declare ( symbol «bar» ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combinor ( combinand expiration ) ) ) ) 
                                    preposition 
                                    ( object reflexive ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combinor ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression ( symbol «bar» ) ) 
                                                                    ( time-unit years ) ) 
                                                                ( symbol ( type data ) ) ) ) ) ) ) 
                                            ( combinor ( combinor ( combinand expiration ) ) 
                                                ( combinand 
                                                    ( negation 
                                                        ( negator be ) 
                                                        ( symbol «bar» ) 
                                                        fixed ) ) 
                                                ( combinator neither ) ) 
                                            ( combinator neither ) ) ) ) ) 
                            ( predicate 
                                ( filing file ( symbol «bar» ) 
                                    ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                            ( combinand ( symbol ( type text ) ) 
                                                                expiration ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand expiration ) 
                                                        ( combinator or- ) ) ) 
                                                ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                            ( existence ( symbol «bar» ) 
                                                                                equal fixed ) ) ) 
                                                                    ( combinand expiration ) 
                                                                    ( combinator neither ) ) 
                                                                ( combinand 
                                                                    ( negation 
                                                                        ( negator be ) 
                                                                        ( symbol ( type data ) ) 
                                                                        ( contract 
                                                                            ( this-contract «bar» ) ) ) ) 
                                                                ( combinator nor ) ) 
                                                            ( combinand 
                                                                ( negation 
                                                                    ( negator ) 
                                                                    ( symbol «bar» ) 
                                                                    fixed ) ) 
                                                            ( combinator and ) ) 
                                                        ( combinand 
                                                            ( negation 
                                                                ( negator be ) 
                                                                ( symbol ( type person ) ) ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand 
                                                        ( existence ( symbol ( type person ) ) 
                                                            be ) ) 
                                                    ( combinator or- ) ) 
                                                ( combinator and ) ) 
                                            ( combinor ( combinand ( symbol «bar» ) ) ) ) ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol ( type text ) ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol ( type person ) ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «bar» ) 
                                    ( expression ( combination ( combination ( combinor ( combinor ( combinand 
                                                            ( point-in-time current-time ) ) ) 
                                                    ( combinand ( symbol ( type time ) ) 
                                                        expiration ) 
                                                    ( combinator or- ) ) ) 
                                            ( combinor ( combinand 
                                                    ( negation 
                                                        ( negator ) 
                                                        ( symbol ( type binary ) ) ) ) ) 
                                            ( combinator nor ) ) ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type amount ) ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «bar» ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type time ) ) ) ) ) 
                        permission 
                        ( condition if 
                            ( expression ( combination ( combinor ( combinor ( combinand expiration ) ) 
                                        ( combinand ( symbol ( type data ) ) ) 
                                        ( combinator and ) ) ) ) ) ) ) 
                ( statement 
                    ( flagging 
                        ( illocutor be ) 
                        ( symbol «bar» ) ) ) ) ) ) 
    ( covenants 
        ( covenant «fred» 
            ( provisions 
                ( definitions 
                    ( definition «fred» ( type text ) ) 
                    ( definition «fred» ( type binary ) ) 
                    ( definition «fred» 
                        ( this-contract «bar» ) ) 
                    ( definition «fred» 
                        ( this-contract «bar» ) ) ) 
                ( clauses 
                    ( clause «fred-bar» 
                        ( body 
                            ( function «fred-bar» 
                                ( illocutor be ) 
                                ( expression ( combination ( combination ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                    ( combinand expiration ) 
                                                    ( combinator neither ) ) 
                                                ( combinand expiration ) 
                                                ( combinator neither ) ) ) 
                                        ( combinor ( combinand expiration ) ) 
                                        ( combinator neither ) ) ) ) ) ) ) 
                ( statements 
                    ( statement 
                        ( flagging 
                            ( illocutor be ) 
                            ( symbol ( type amount ) ) ) ) ) ) ) 
        ( covenant «fred-bar» 
            ( provisions 
                ( definitions 
                    ( definition «fred-bar» ( type time ) ) ) 
                ( clauses 
                    ( clause «xyzzy» 
                        ( body 
                            ( statements 
                                ( statement 
                                    ( action 
                                        ( subject 
                                            ( symbols 
                                                ( symbols 
                                                    ( symbols 
                                                        ( symbols 
                                                            ( symbols ( symbol «xyzzy» ) ) 
                                                            ( symbol «xyzzy» ) 
                                                            catena ) 
                                                        ( symbol ( type person ) ) 
                                                        catena ) 
                                                    ( symbol ( type amount ) ) 
                                                    catena ) 
                                                ( symbol ( type person ) ) 
                                                catena ) ) 
                                        ( predicates 
                                            ( predicate 
                                                ( grantment grant ( symbol «xyzzy» ) ) ) 
                                            ( predicate 
                                                ( registration register ( symbol «xyzzy» ) 
                                                    ( contract all-contracts ) ) ) 
                                            ( predicate 
                                                ( filing file ( symbol «xyzzy» ) 
                                                    ( contract all-contracts ) ) ) 
                                            ( predicate 
                                                ( appointment appoint ( symbol ( type binary ) ) ) ) ) 
                                        permission ) ) ) ) ) 
                    ( clause «xyzzy-bar» 
                        ( body 
                            ( function «xyzzy-bar» 
                                ( illocutor be ) 
                                ( expression ( combination ( combination ( combination ( combination ( combinor ( combinand 
                                                            ( point-in-time current-time ) ) ) ) 
                                                ( combinor ( combinor ( combinand expiration ) ) 
                                                    ( combinand expiration ) 
                                                    ( combinator nor ) ) ) 
                                            ( combinor ( combinor ( combinand expiration ) ) 
                                                ( combinand ( symbol ( type binary ) ) ) 
                                                ( combinator nor ) ) ) 
                                        ( combinor ( combinand expiration ) ) 
                                        ( combinator nor ) ) ) ) ) ) 
                    ( clause «foo-bar» 
                        ( body 
                            ( function «foo-bar» 
                                ( illocutor be ) 
                                ( expression ( combination ( combination ( combinor ( combinor ( combinand 
                                                        ( negation 
                                                            ( negator be ) 
                                                            ( symbol «foo-bar» ) 
                                                            ( contract 
                                                                ( this-contract «bar» ) ) ) ) ) 
                                                ( combinand ( symbol ( type amount ) ) ) 
                                                ( combinator or- ) ) ) 
                                        ( combinor ( combinor ( combinand ( symbol ( type text ) ) 
                                                    expiration ) ) 
                                            ( combinand 
                                                ( point-in-time current-time ) ) 
                                            ( combinator neither ) ) ) ) ) ) ) 
                    ( clause «foo-baz» 
                        ( body 
                            ( statements 
                                ( statement 
                                    ( action 
                                        ( subject 
                                            ( symbols 
                                                ( symbols ( symbol «foo-baz» ) ) 
                                                ( symbol «foo-baz» ) 
                                                catena ) ) 
                                        ( predicates 
                                            ( predicate 
                                                ( termination terminate all-contracts ) ) 
                                            ( predicate 
                                                ( fixture fix ( symbol ( type text ) ) 
                                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combinor ( combinand ( symbol «foo-baz» ) ) ) ) 
                                                                        ( combinor ( combinor ( combinand 
                                                                                    ( scalar-comparison 
                                                                                        ( scalar-expression 123 ) 
                                                                                        ( comparison-operator equal ) 
                                                                                        ( scalar-expression ( symbol «foo-baz» ) ) ) ) ) 
                                                                            ( combinand ( symbol ( type data ) ) 
                                                                                expiration ) 
                                                                            ( combinator nor ) ) ) 
                                                                    ( combinor ( combinor ( combinand 
                                                                                ( scalar-comparison 
                                                                                    ( scalar-expression 
                                                                                        ( point-in-time 
                                                                                            ( relative-time 
                                                                                                ( duration 
                                                                                                    ( scalar-expression 
                                                                                                        ( point-in-time 
                                                                                                            ( relative-time 
                                                                                                                ( duration 
                                                                                                                    ( scalar-expression ( symbol «foo-baz» ) ) 
                                                                                                                    ( time-unit months ) ) 
                                                                                                                ( symbol «foo-baz» ) ) ) ) 
                                                                                                    ( time-unit seconds ) ) 
                                                                                                ( symbol ( type data ) ) ) ) ) 
                                                                                    ( comparison-operator later ) 
                                                                                    ( scalar-expression 123 ) ) ) ) 
                                                                        ( combinand 
                                                                            ( existence ( symbol ( type amount ) ) 
                                                                                being true ) ) 
                                                                        ( combinator and ) ) ) 
                                                                ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol ( type amount ) ) ) ) 
                                                                            ( combinand expiration ) 
                                                                            ( combinator and ) ) 
                                                                        ( combinand ( symbol «foo-baz» ) ) 
                                                                        ( combinator or- ) ) 
                                                                    ( combinand ( symbol ( type person ) ) ) 
                                                                    ( combinator neither ) ) ) 
                                                            ( combinor ( combinand 
                                                                    ( negation 
                                                                        ( negator ) 
                                                                        ( symbol «foo-baz» ) 
                                                                        fixed ) ) ) 
                                                            ( combinator and ) ) ) ) ) 
                                            ( predicate 
                                                ( certification certify ( symbol «foo-baz» ) 
                                                    ( contract 
                                                        ( this-contract «bar» ) ) ) ) 
                                            ( predicate 
                                                ( grantment grant ( symbol «foo-baz» ) ) ) ) 
                                        permission 
                                        ( condition if 
                                            ( expression ( combination ( combination ( combination ( combination ( combinor ( combinand 
                                                                        ( scalar-comparison 
                                                                            ( scalar-expression 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression ( symbol ( type amount ) ) ) 
                                                                                            ( time-unit days ) ) 
                                                                                        ( symbol ( type time ) ) ) ) ) 
                                                                            ( comparison-operator equal ) 
                                                                            ( scalar-expression 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression 
                                                                                                ( point-in-time 
                                                                                                    ( relative-time 
                                                                                                        ( duration 
                                                                                                            ( scalar-expression ( symbol ( type data ) ) ) 
                                                                                                            ( time-unit years ) ) 
                                                                                                        ( symbol ( type time ) ) ) ) ) 
                                                                                            ( time-unit months ) ) ) ) ) ) ) ) ) 
                                                            ( combinor ( combinor ( combinor ( combinand 
                                                                            ( negation 
                                                                                ( negator ) 
                                                                                ( symbol «foo-baz» ) ) ) ) 
                                                                    ( combinand 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression ( symbol ( type amount ) ) ) 
                                                                                    ( time-unit months ) ) 
                                                                                ( symbol ( type text ) ) ) ) ) 
                                                                    ( combinator nor ) ) 
                                                                ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression 123 ) 
                                                                        ( comparison-operator equal ) 
                                                                        ( scalar-expression ( symbol ( type text ) ) ) ) ) 
                                                                ( combinator neither ) ) ) 
                                                        ( combinor ( combinand 
                                                                ( point-in-time current-time ) ) ) 
                                                        ( combinator or- ) ) 
                                                    ( combinor ( combinand expiration ) ) ) ) ) ) ) 
                                ( statement 
                                    ( action 
                                        ( subject 
                                            ( symbols 
                                                ( symbols ( symbol «foo-baz» ) ) 
                                                ( symbol ( type data ) ) 
                                                catena ) ) 
                                        ( predicates 
                                            ( predicate 
                                                ( filing file ( symbol ( type time ) ) 
                                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                                                ( point-in-time 
                                                                                                                    ( relative-time 
                                                                                                                        ( duration 
                                                                                                                            ( scalar-expression ( symbol «foo-baz» ) ) 
                                                                                                                            ( time-unit seconds ) ) 
                                                                                                                        ( symbol «foo-baz» ) ) ) ) ) 
                                                                                                        ( combinand 
                                                                                                            ( scalar-comparison 
                                                                                                                ( scalar-expression 
                                                                                                                    ( point-in-time 
                                                                                                                        ( relative-time 
                                                                                                                            ( duration 
                                                                                                                                ( scalar-expression ( symbol «foo-baz» ) ) 
                                                                                                                                ( time-unit milliseconds ) ) 
                                                                                                                            ( symbol ( type data ) ) ) ) ) 
                                                                                                                ( comparison-operator equal ) 
                                                                                                                ( scalar-expression 123 ) ) ) 
                                                                                                        ( combinator or- ) ) 
                                                                                                    ( combinand 
                                                                                                        ( existence ( symbol «foo-baz» ) 
                                                                                                            be 
                                                                                                            ( contract all-contracts ) ) ) 
                                                                                                    ( combinator neither ) ) 
                                                                                                ( combinand ( symbol «foo-baz» ) ) 
                                                                                                ( combinator neither ) ) ) 
                                                                                        ( combinor ( combinor ( combinand ( symbol «foo-baz» ) ) ) 
                                                                                            ( combinand ( symbol «foo-baz» ) ) 
                                                                                            ( combinator nor ) ) ) 
                                                                                    ( combinor ( combinor ( combinand 
                                                                                                ( existence ( symbol «foo-baz» ) 
                                                                                                    being true ) ) ) 
                                                                                        ( combinand ( symbol «foo-baz» ) ) 
                                                                                        ( combinator nor ) ) ) 
                                                                                ( combinor ( combinand 
                                                                                        ( existence ( symbol ( type binary ) ) 
                                                                                            be 
                                                                                            ( contract 
                                                                                                ( this-contract «bar» ) ) ) ) ) ) 
                                                                            ( combinor ( combinand 
                                                                                    ( negation 
                                                                                        ( negator ) 
                                                                                        ( symbol ( type amount ) ) ) ) ) 
                                                                            ( combinator and ) ) 
                                                                        ( combinor ( combinand 
                                                                                ( scalar-comparison 
                                                                                    ( scalar-expression ( symbol ( type text ) ) ) 
                                                                                    ( comparison-operator equal ) 
                                                                                    ( scalar-expression 
                                                                                        ( point-in-time current-time ) ) ) ) ) ) 
                                                                    ( combinor ( combinor ( combinand 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression ( symbol ( type data ) ) ) 
                                                                                            ( time-unit weeks ) ) ) ) ) ) 
                                                                        ( combinand ( symbol ( type text ) ) ) 
                                                                        ( combinator nor ) ) ) 
                                                                ( combinor ( combinand 
                                                                        ( existence ( symbol ( type text ) ) 
                                                                            be 
                                                                            ( contract all-contracts ) ) ) ) ) 
                                                            ( combinor ( combinor ( combinand expiration ) ) 
                                                                ( combinand 
                                                                    ( existence ( symbol «foo-baz» ) 
                                                                        be ) ) 
                                                                ( combinator nor ) ) ) ) ) ) 
                                            ( predicate 
                                                ( setting 
                                                    ( illocutor be ) 
                                                    ( symbol ( type text ) ) ) ) 
                                            ( predicate 
                                                ( appointment appoint ( symbol ( type person ) ) ) ) 
                                            ( predicate 
                                                ( certification certify ( symbol «foo-baz» ) ) ) 
                                            ( predicate 
                                                ( payment pay 
                                                    ( expression ( combination ( combination ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol ( type amount ) ) ) ) 
                                                                            ( combinand expiration ) 
                                                                            ( combinator and ) ) 
                                                                        ( combinand expiration ) 
                                                                        ( combinator or- ) ) 
                                                                    ( combinand expiration ) 
                                                                    ( combinator nor ) ) ) 
                                                            ( combinor ( combinor ( combinand 
                                                                        ( negation 
                                                                            ( negator be ) 
                                                                            ( symbol ( type time ) ) 
                                                                            ( contract 
                                                                                ( this-contract «bar» ) ) ) ) ) 
                                                                ( combinand expiration ) 
                                                                ( combinator neither ) ) 
                                                            ( combinator and ) ) ) 
                                                    preposition 
                                                    ( object reflexive ) ) ) 
                                            ( predicate 
                                                ( fixture fix ( symbol «foo-baz» ) 
                                                    ( contract all-contracts ) ) ) ) 
                                        permission ) ) ) ) ) 
                    ( clause «baz» 
                        ( body 
                            ( function «baz» 
                                ( illocutor be ) 
                                ( expression ( combination ( combinor ( combinand 
                                                ( negation 
                                                    ( negator ) 
                                                    ( symbol ( type text ) ) 
                                                    fixed ) ) ) ) ) ) ) ) ) 
                ( statements 
                    ( statement 
                        ( action 
                            ( subject 
                                ( symbols ( symbol ( type text ) ) ) ) 
                            ( predicates 
                                ( predicate 
                                    ( setting 
                                        ( illocutor be ) 
                                        ( symbol ( type text ) ) ) ) 
                                ( predicate 
                                    ( registration register ( symbol ( type time ) ) 
                                        ( expression ( combination ( combination ( combination ( combination ( combinor ( combinand ( symbol «fred-bar» ) 
                                                                    expiration ) ) ) 
                                                        ( combinor ( combinor ( combinand 
                                                                    ( point-in-time 
                                                                        ( relative-time 
                                                                            ( duration 
                                                                                ( scalar-expression 
                                                                                    ( point-in-time current-time ) ) 
                                                                                ( time-unit milliseconds ) ) 
                                                                            ( symbol ( type time ) ) ) ) ) ) 
                                                            ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression ( symbol «fred-bar» ) ) 
                                                                    ( comparison-operator equal ) 
                                                                    ( scalar-expression 
                                                                        ( point-in-time current-time ) ) ) ) 
                                                            ( combinator and ) ) ) 
                                                    ( combinor ( combinand 
                                                            ( point-in-time current-time ) ) ) ) 
                                                ( combinor ( combinor ( combinand 
                                                            ( scalar-comparison 
                                                                ( scalar-expression ( symbol ( type text ) ) ) 
                                                                ( comparison-operator later ) 
                                                                ( scalar-expression ( symbol ( type amount ) ) ) ) ) ) 
                                                    ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression 
                                                                                        ( point-in-time current-time ) ) 
                                                                                    ( time-unit weeks ) ) 
                                                                                ( symbol ( type text ) ) ) ) ) 
                                                                    ( time-unit weeks ) ) 
                                                                ( symbol «fred-bar» ) ) ) ) 
                                                    ( combinator and ) ) 
                                                ( combinator and ) ) ) ) ) 
                                ( predicate 
                                    ( sending send 
                                        ( expression ( combination ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                        ( combinand ( symbol «fred-bar» ) 
                                                            expiration ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand ( symbol «fred-bar» ) 
                                                        expiration ) 
                                                    ( combinator or- ) ) ) ) 
                                        preposition 
                                        ( object ( symbol ( type person ) ) ) ) ) 
                                ( predicate 
                                    ( fixture fix ( symbol «fred-bar» ) 
                                        ( contract 
                                            ( this-contract «bar» ) ) ) ) 
                                ( predicate 
                                    ( fixture fix ( symbol «fred-bar» ) 
                                        ( contract all-contracts ) ) ) 
                                ( predicate 
                                    ( declaration declare ( symbol «fred-bar» ) 
                                        ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinand expiration ) ) 
                                                            ( combinand ( symbol «fred-bar» ) ) 
                                                            ( combinator and ) ) ) 
                                                    ( combinor ( combinor ( combinand 
                                                                ( negation 
                                                                    ( negator be ) 
                                                                    ( symbol ( type person ) ) ) ) ) 
                                                        ( combinand 
                                                            ( point-in-time 
                                                                ( relative-time 
                                                                    ( duration 
                                                                        ( scalar-expression ( symbol ( type binary ) ) ) 
                                                                        ( time-unit minutes ) ) 
                                                                    ( symbol ( type amount ) ) ) ) ) 
                                                        ( combinator or- ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinor ( combinor ( combinor ( combinand 
                                                                ( existence ( symbol ( type person ) ) 
                                                                    equal fixed ) ) ) 
                                                        ( combinand 
                                                            ( point-in-time current-time ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression ( symbol ( type binary ) ) ) 
                                                            ( comparison-operator equal ) 
                                                            ( scalar-expression 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression 
                                                                                                ( point-in-time 
                                                                                                    ( relative-time 
                                                                                                        ( duration 
                                                                                                            ( scalar-expression 
                                                                                                                ( point-in-time 
                                                                                                                    ( relative-time 
                                                                                                                        ( duration 
                                                                                                                            ( scalar-expression 
                                                                                                                                ( point-in-time current-time ) ) 
                                                                                                                            ( time-unit hours ) ) 
                                                                                                                        ( symbol ( type person ) ) ) ) ) 
                                                                                                            ( time-unit months ) ) 
                                                                                                        ( symbol ( type time ) ) ) ) ) 
                                                                                            ( time-unit hours ) ) ) ) ) 
                                                                            ( time-unit hours ) ) 
                                                                        ( symbol «fred-bar» ) ) ) ) ) ) 
                                                    ( combinator or- ) ) ) ) ) ) 
                                ( predicate 
                                    ( fixture fix ( symbol «fred-bar» ) ) ) 
                                ( predicate 
                                    ( termination terminate all-contracts ) ) 
                                ( predicate 
                                    ( appointment appoint ( symbol «fred-bar» ) ) ) 
                                ( predicate 
                                    ( payment pay 
                                        ( expression ( combination ( combinor ( combinor ( combinor ( combinand 
                                                                ( point-in-time current-time ) ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol «fred-bar» ) 
                                                                being true ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression ( symbol ( type person ) ) ) 
                                                            ( comparison-operator equal ) 
                                                            ( scalar-expression 123 ) ) ) 
                                                    ( combinator and ) ) ) ) 
                                        preposition 
                                        ( object ( symbol ( type text ) ) ) ) ) ) 
                            permission ) ) 
                    ( statement 
                        ( action 
                            ( subject 
                                ( symbols 
                                    ( symbols ( symbol ( type text ) ) ) 
                                    ( symbol «fred-bar» ) 
                                    catena ) ) 
                            ( predicates 
                                ( predicate 
                                    ( termination terminate all-contracts ) ) 
                                ( predicate 
                                    ( declaration declare ( symbol ( type person ) ) 
                                        ( contract 
                                            ( this-contract «bar» ) ) ) ) 
                                ( predicate 
                                    ( certification certify ( symbol ( type data ) ) ) ) 
                                ( predicate 
                                    ( notification notify 
                                        ( object ( symbol ( type data ) ) ) 
                                        preposition 
                                        ( expression ( combination ( combination ( combinor ( combinor ( combinand 
                                                                ( existence ( symbol «fred-bar» ) 
                                                                    equal fixed ) ) ) 
                                                        ( combinand expiration ) 
                                                        ( combinator or- ) ) ) 
                                                ( combinor ( combinor ( combinand 
                                                            ( point-in-time 
                                                                ( relative-time 
                                                                    ( duration 
                                                                        ( scalar-expression ( symbol «fred-bar» ) ) 
                                                                        ( time-unit days ) ) 
                                                                    ( symbol «fred-bar» ) ) ) ) ) 
                                                    ( combinand expiration ) 
                                                    ( combinator nor ) ) 
                                                ( combinator or- ) ) ) ) ) ) 
                            permission 
                            ( condition if 
                                ( expression ( combination ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol «fred-bar» ) 
                                                            expiration ) ) 
                                                    ( combinand expiration ) 
                                                    ( combinator or- ) ) 
                                                ( combinand 
                                                    ( existence ( symbol «fred-bar» ) 
                                                        being true ) ) 
                                                ( combinator and ) ) 
                                            ( combinand 
                                                ( existence ( symbol ( type time ) ) 
                                                    be ) ) 
                                            ( combinator neither ) ) ) ) ) ) ) ) ) ) 
        ( covenant «baz» 
            ( provisions 
                ( definitions 
                    ( definition «baz» 
                        ( this-contract «bar» ) ) ) 
                ( statements 
                    ( statement 
                        ( flagging 
                            ( illocutor be ) 
                            ( symbol ( type data ) ) ) ) 
                    ( statement 
                        ( flagging 
                            ( illocutor be ) 
                            ( symbol «baz» ) 
                            ( this-contract «bar» ) ) ) ) ) ) ) )
