( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «baz» ( type person ) ) 
                ( definition «baz» 
                    ( this-contract «bar» ) ) ) 
            ( clauses 
                ( clause «qux-waldo» 
                    ( body 
                        ( function «qux-waldo» 
                            ( illocutor be ) 
                            ( expression ( combination ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol ( type text ) ) 
                                                        expiration ) ) 
                                                ( combinand 
                                                    ( point-in-time current-time ) ) 
                                                ( combinator or- ) ) 
                                            ( combinand 
                                                ( existence ( symbol «qux-waldo» ) 
                                                    be ) ) 
                                            ( combinator and ) ) 
                                        ( combinand 
                                            ( scalar-comparison 
                                                ( scalar-expression 
                                                    ( point-in-time current-time ) ) 
                                                ( comparison-operator later ) 
                                                ( scalar-expression 
                                                    ( point-in-time 
                                                        ( relative-time 
                                                            ( duration 
                                                                ( scalar-expression 123 ) 
                                                                ( time-unit seconds ) ) 
                                                            ( symbol «qux-waldo» ) ) ) ) ) ) 
                                        ( combinator neither ) ) ) ) ) ) ) ) 
            ( statements 
                ( statement 
                    ( flagging 
                        ( illocutor be ) 
                        ( symbol «baz» ) ) ) 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols ( symbol ( type text ) ) ) ) 
                        ( predicates 
                            ( predicate 
                                ( certification certify ( symbol «baz» ) 
                                    ( expression ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinand 
                                                                    ( point-in-time current-time ) ) ) 
                                                            ( combinand ( symbol ( type amount ) ) ) 
                                                            ( combinator or- ) ) ) 
                                                    ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                                    ( combinand 
                                                                        ( scalar-comparison 
                                                                            ( scalar-expression ( symbol «baz» ) ) 
                                                                            ( comparison-operator later ) 
                                                                            ( scalar-expression 123 ) ) ) 
                                                                    ( combinator and ) ) 
                                                                ( combinand expiration ) 
                                                                ( combinator nor ) ) 
                                                            ( combinand 
                                                                ( negation 
                                                                    ( negator be ) 
                                                                    ( symbol ( type binary ) ) ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand expiration ) 
                                                        ( combinator neither ) ) ) 
                                                ( combinor ( combinand expiration ) ) 
                                                ( combinator or- ) ) 
                                            ( combinor ( combinand ( symbol ( type person ) ) ) ) ) ) ) ) 
                            ( predicate 
                                ( filing file ( symbol «baz» ) 
                                    ( expression ( combination ( combinor ( combinand 
                                                    ( negation 
                                                        ( negator ) 
                                                        ( symbol ( type data ) ) 
                                                        fixed ) ) ) ) ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object ( symbol ( type data ) ) ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combination ( combinor ( combinand ( symbol ( type amount ) ) ) ) ) 
                                                ( combinor ( combinand ( symbol ( type text ) ) ) ) 
                                                ( combinator or- ) ) 
                                            ( combinor ( combinor ( combinand expiration ) ) 
                                                ( combinand expiration ) 
                                                ( combinator or- ) ) ) ) ) ) 
                            ( predicate 
                                ( payment pay preposition 
                                    ( object ( symbol ( type person ) ) ) 
                                    escrow ) ) 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combination ( combinor ( combinand expiration ) ) ) 
                                                            ( combinor ( combinor ( combinand ( symbol «baz» ) 
                                                                        expiration ) ) 
                                                                ( combinand ( symbol ( type person ) ) ) 
                                                                ( combinator or- ) ) ) 
                                                        ( combinor ( combinor ( combinand 
                                                                    ( negation 
                                                                        ( negator ) 
                                                                        ( symbol «baz» ) ) ) ) 
                                                            ( combinand ( symbol ( type person ) ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinor ( combinand expiration ) ) 
                                                    ( combinator nor ) ) 
                                                ( combinor ( combinor ( combinand 
                                                            ( scalar-comparison 
                                                                ( scalar-expression 123 ) 
                                                                ( comparison-operator later ) 
                                                                ( scalar-expression ( symbol ( type time ) ) ) ) ) ) 
                                                    ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression 
                                                                        ( point-in-time current-time ) ) 
                                                                    ( time-unit months ) ) 
                                                                ( symbol ( type data ) ) ) ) ) 
                                                    ( combinator or- ) ) ) 
                                            ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol ( type text ) ) ) ) 
                                                                ( combinand 
                                                                    ( negation 
                                                                        ( negator be ) 
                                                                        ( symbol «baz» ) 
                                                                        ( contract 
                                                                            ( this-contract «bar» ) ) ) ) 
                                                                ( combinator neither ) ) 
                                                            ( combinand expiration ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol ( type binary ) ) 
                                                                be ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinand expiration ) 
                                                    ( combinator neither ) ) 
                                                ( combinand 
                                                    ( point-in-time current-time ) ) 
                                                ( combinator nor ) ) ) ) 
                                    preposition 
                                    ( object ) 
                                    from-escrow ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «baz» ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol ( type amount ) ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combinor ( combinor ( combinor ( combinand 
                                                                ( negation 
                                                                    ( negator be ) 
                                                                    ( symbol «baz» ) 
                                                                    fixed ) ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol «baz» ) 
                                                                equal fixed ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinand ( symbol «baz» ) 
                                                        expiration ) 
                                                    ( combinator neither ) ) ) 
                                            ( combinor ( combinor ( combinand 
                                                        ( existence ( symbol «baz» ) 
                                                            equal fixed ) ) ) 
                                                ( combinand 
                                                    ( existence ( symbol «baz» ) 
                                                        being true ) ) 
                                                ( combinator nor ) ) 
                                            ( combinator nor ) ) ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol ( type person ) ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type binary ) ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( certification certify ( symbol «baz» ) 
                                    ( expression ( combination ( combination ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                        ( combinand 
                                                            ( negation 
                                                                ( negator be ) 
                                                                ( symbol «baz» ) 
                                                                fixed ) ) 
                                                        ( combinator and ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression 123 ) 
                                                            ( comparison-operator equal ) 
                                                            ( scalar-expression ( symbol «baz» ) ) ) ) 
                                                    ( combinator neither ) ) ) 
                                            ( combinor ( combinor ( combinand expiration ) ) 
                                                ( combinand expiration ) 
                                                ( combinator neither ) ) 
                                            ( combinator or- ) ) ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol «baz» ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type time ) ) 
                                    ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression 123 ) 
                                                                        ( comparison-operator equal ) 
                                                                        ( scalar-expression 123 ) ) ) ) 
                                                            ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression ( symbol «baz» ) ) 
                                                                    ( comparison-operator equal ) 
                                                                    ( scalar-expression 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression ( symbol «baz» ) ) 
                                                                                    ( time-unit years ) ) ) ) ) ) ) 
                                                            ( combinator and ) ) 
                                                        ( combinand 
                                                            ( negation 
                                                                ( negator be ) 
                                                                ( symbol ( type amount ) ) ) ) 
                                                        ( combinator nor ) ) ) 
                                                ( combinor ( combinor ( combinand 
                                                            ( scalar-comparison 
                                                                ( scalar-expression ( symbol «baz» ) ) 
                                                                ( comparison-operator later ) 
                                                                ( scalar-expression 
                                                                    ( point-in-time 
                                                                        ( relative-time 
                                                                            ( duration 
                                                                                ( scalar-expression ( symbol «baz» ) ) 
                                                                                ( time-unit hours ) ) 
                                                                            ( symbol «baz» ) ) ) ) ) ) ) 
                                                    ( combinand ( symbol ( type person ) ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinator or- ) ) 
                                            ( combinor ( combinor ( combinand expiration ) ) 
                                                ( combinand 
                                                    ( existence ( symbol ( type person ) ) 
                                                        be 
                                                        ( contract all-contracts ) ) ) 
                                                ( combinator or- ) ) 
                                            ( combinator nor ) ) ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol ( type time ) ) ) ) 
                            ( predicate 
                                ( filing file ( symbol «baz» ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( payment pay preposition 
                                    ( object ) 
                                    escrow ) ) 
                            ( predicate 
                                ( registration register ( symbol ( type person ) ) ) ) 
                            ( predicate 
                                ( certification certify ( symbol ( type time ) ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( declaration declare ( symbol «baz» ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol ( type data ) ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type binary ) ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type time ) ) ) ) 
                            ( predicate 
                                ( certification certify ( symbol ( type time ) ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( filing file ( symbol «baz» ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( termination terminate all-contracts ) ) 
                            ( predicate 
                                ( fixture fix ( symbol ( type text ) ) 
                                    ( expression ( combination ( combination ( combinor ( combinor ( combinor ( combinand 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression ( symbol «baz» ) ) 
                                                                            ( time-unit hours ) ) ) ) ) ) 
                                                        ( combinand 
                                                            ( point-in-time current-time ) ) 
                                                        ( combinator and ) ) 
                                                    ( combinand 
                                                        ( negation 
                                                            ( negator be ) 
                                                            ( symbol «baz» ) ) ) 
                                                    ( combinator nor ) ) ) 
                                            ( combinor ( combinor ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression ( symbol ( type time ) ) ) 
                                                            ( comparison-operator equal ) 
                                                            ( scalar-expression 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression ( symbol «baz» ) ) 
                                                                            ( time-unit weeks ) ) 
                                                                        ( symbol ( type time ) ) ) ) ) ) ) ) 
                                                ( combinand 
                                                    ( negation 
                                                        ( negator be ) 
                                                        ( symbol ( type data ) ) ) ) 
                                                ( combinator nor ) ) 
                                            ( combinator or- ) ) ) ) ) 
                            ( predicate 
                                ( registration register ( symbol «baz» ) 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinand 
                                                                            ( negation 
                                                                                ( negator be ) 
                                                                                ( symbol ( type text ) ) 
                                                                                fixed ) ) ) 
                                                                    ( combinand 
                                                                        ( negation 
                                                                            ( negator be ) 
                                                                            ( symbol «baz» ) 
                                                                            ( contract all-contracts ) ) ) 
                                                                    ( combinator or- ) ) ) 
                                                            ( combinor ( combinand 
                                                                    ( point-in-time 
                                                                        ( relative-time 
                                                                            ( duration 
                                                                                ( scalar-expression ( symbol «baz» ) ) 
                                                                                ( time-unit milliseconds ) ) 
                                                                            ( symbol «baz» ) ) ) ) ) 
                                                            ( combinator neither ) ) 
                                                        ( combinor ( combinand 
                                                                ( negation 
                                                                    ( negator be ) 
                                                                    ( symbol ( type data ) ) 
                                                                    ( contract 
                                                                        ( this-contract «bar» ) ) ) ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinor ( combinand 
                                                            ( negation 
                                                                ( negator be ) 
                                                                ( symbol «baz» ) ) ) ) ) 
                                                ( combinor ( combinand 
                                                        ( existence ( symbol ( type text ) ) 
                                                            be 
                                                            ( contract all-contracts ) ) ) ) ) 
                                            ( combinor ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression ( symbol «baz» ) ) 
                                                        ( comparison-operator later ) 
                                                        ( scalar-expression 123 ) ) ) ) ) ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol «baz» ) ) ) 
                            ( predicate 
                                ( filing file ( symbol «baz» ) 
                                    ( expression ( combination ( combination ( combinor ( combinand ( symbol ( type data ) ) ) ) ) 
                                            ( combinor ( combinor ( combinand 
                                                        ( existence ( symbol «baz» ) 
                                                            be 
                                                            ( contract 
                                                                ( this-contract «bar» ) ) ) ) ) 
                                                ( combinand expiration ) 
                                                ( combinator neither ) ) ) ) ) ) 
                            ( predicate 
                                ( registration register ( symbol «baz» ) 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol ( type binary ) ) 
                                                                                expiration ) ) 
                                                                        ( combinand expiration ) 
                                                                        ( combinator and ) ) 
                                                                    ( combinand ( symbol «baz» ) ) 
                                                                    ( combinator nor ) ) 
                                                                ( combinand expiration ) 
                                                                ( combinator neither ) ) ) 
                                                        ( combinor ( combinor ( combinor ( combinand ( symbol «baz» ) 
                                                                        expiration ) ) 
                                                                ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression ( symbol ( type data ) ) ) 
                                                                        ( comparison-operator equal ) 
                                                                        ( scalar-expression 123 ) ) ) 
                                                                ( combinator or- ) ) 
                                                            ( combinand ( symbol ( type amount ) ) ) 
                                                            ( combinator or- ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinor ( combinor ( combinand 
                                                                ( existence ( symbol ( type person ) ) 
                                                                    be ) ) ) 
                                                        ( combinand ( symbol ( type time ) ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinor ( combinor ( combinor ( combinand 
                                                                ( existence ( symbol «baz» ) 
                                                                    be 
                                                                    ( contract all-contracts ) ) ) ) 
                                                        ( combinand 
                                                            ( negation 
                                                                ( negator ) 
                                                                ( symbol «baz» ) ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand 
                                                        ( negation 
                                                            ( negator be ) 
                                                            ( symbol «baz» ) ) ) 
                                                    ( combinator nor ) ) ) 
                                            ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                    ( negation 
                                                                        ( negator be ) 
                                                                        ( symbol «baz» ) ) ) ) 
                                                            ( combinand ( symbol «baz» ) ) 
                                                            ( combinator and ) ) 
                                                        ( combinand 
                                                            ( negation 
                                                                ( negator be ) 
                                                                ( symbol ( type binary ) ) ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinand 
                                                        ( point-in-time current-time ) ) 
                                                    ( combinator nor ) ) 
                                                ( combinand ( symbol «baz» ) ) 
                                                ( combinator and ) ) ) ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combinor ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression 
                                                                            ( point-in-time 
                                                                                ( relative-time 
                                                                                    ( duration 
                                                                                        ( scalar-expression ( symbol ( type data ) ) ) 
                                                                                        ( time-unit hours ) ) ) ) ) 
                                                                        ( comparison-operator equal ) 
                                                                        ( scalar-expression ( symbol ( type time ) ) ) ) ) ) ) 
                                                        ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                ( negation 
                                                                                    ( negator be ) 
                                                                                    ( symbol «baz» ) ) ) ) 
                                                                        ( combinand ( symbol «baz» ) 
                                                                            expiration ) 
                                                                        ( combinator neither ) ) 
                                                                    ( combinand 
                                                                        ( negation 
                                                                            ( negator be ) 
                                                                            ( symbol «baz» ) 
                                                                            fixed ) ) 
                                                                    ( combinator neither ) ) 
                                                                ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression 
                                                                            ( point-in-time 
                                                                                ( relative-time 
                                                                                    ( duration 
                                                                                        ( scalar-expression 123 ) 
                                                                                        ( time-unit hours ) ) 
                                                                                    ( symbol «baz» ) ) ) ) 
                                                                        ( comparison-operator later ) 
                                                                        ( scalar-expression ( symbol ( type time ) ) ) ) ) 
                                                                ( combinator and ) ) 
                                                            ( combinand 
                                                                ( point-in-time current-time ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                                    ( combinand ( symbol ( type person ) ) 
                                                                        expiration ) 
                                                                    ( combinator and ) ) 
                                                                ( combinand ( symbol «baz» ) 
                                                                    expiration ) 
                                                                ( combinator and ) ) 
                                                            ( combinand expiration ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand ( symbol «baz» ) 
                                                            expiration ) 
                                                        ( combinator and ) ) 
                                                    ( combinator nor ) ) 
                                                ( combinor ( combinor ( combinand 
                                                            ( point-in-time 
                                                                ( relative-time 
                                                                    ( duration 
                                                                        ( scalar-expression ( symbol ( type text ) ) ) 
                                                                        ( time-unit months ) ) 
                                                                    ( symbol «baz» ) ) ) ) ) 
                                                    ( combinand ( symbol ( type text ) ) ) 
                                                    ( combinator or- ) ) ) 
                                            ( combinor ( combinand 
                                                    ( existence ( symbol «baz» ) 
                                                        be 
                                                        ( contract 
                                                            ( this-contract «bar» ) ) ) ) ) 
                                            ( combinator or- ) ) ) 
                                    preposition 
                                    ( object ( symbol «baz» ) ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type binary ) ) 
                                    ( expression ( combination ( combination ( combinor ( combinand ( symbol «baz» ) 
                                                        expiration ) ) ) 
                                            ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                ( existence ( symbol ( type binary ) ) 
                                                                    be ) ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol ( type binary ) ) 
                                                                be ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand expiration ) 
                                                    ( combinator neither ) ) 
                                                ( combinand 
                                                    ( existence ( symbol ( type time ) ) 
                                                        be 
                                                        ( contract 
                                                            ( this-contract «bar» ) ) ) ) 
                                                ( combinator nor ) ) 
                                            ( combinator or- ) ) ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol ( type time ) ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinand 
                                                                ( existence ( symbol «baz» ) 
                                                                    be 
                                                                    ( contract 
                                                                        ( this-contract «bar» ) ) ) ) ) 
                                                        ( combinand ( symbol «baz» ) 
                                                            expiration ) 
                                                        ( combinator or- ) ) ) 
                                                ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol «baz» ) ) ) 
                                                                ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression 123 ) 
                                                                        ( comparison-operator equal ) 
                                                                        ( scalar-expression 
                                                                            ( point-in-time 
                                                                                ( relative-time 
                                                                                    ( duration 
                                                                                        ( scalar-expression ( symbol ( type binary ) ) ) 
                                                                                        ( time-unit hours ) ) 
                                                                                    ( symbol ( type binary ) ) ) ) ) ) ) 
                                                                ( combinator or- ) ) 
                                                            ( combinand ( symbol ( type amount ) ) ) 
                                                            ( combinator neither ) ) 
                                                        ( combinand ( symbol ( type time ) ) ) 
                                                        ( combinator or- ) ) 
                                                    ( combinand 
                                                        ( existence ( symbol ( type data ) ) 
                                                            being true ) ) 
                                                    ( combinator nor ) ) ) 
                                            ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                ( negation 
                                                                                    ( negator ) 
                                                                                    ( symbol «baz» ) ) ) ) 
                                                                        ( combinand expiration ) 
                                                                        ( combinator or- ) ) 
                                                                    ( combinand 
                                                                        ( scalar-comparison 
                                                                            ( scalar-expression 
                                                                                ( point-in-time current-time ) ) 
                                                                            ( comparison-operator later ) 
                                                                            ( scalar-expression 
                                                                                ( point-in-time current-time ) ) ) ) 
                                                                    ( combinator neither ) ) 
                                                                ( combinand 
                                                                    ( point-in-time current-time ) ) 
                                                                ( combinator nor ) ) 
                                                            ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression ( symbol ( type time ) ) ) 
                                                                                    ( time-unit months ) ) 
                                                                                ( symbol «baz» ) ) ) ) 
                                                                    ( comparison-operator later ) 
                                                                    ( scalar-expression 
                                                                        ( point-in-time current-time ) ) ) ) 
                                                            ( combinator neither ) ) 
                                                        ( combinand ( symbol «baz» ) 
                                                            expiration ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression ( symbol ( type person ) ) ) 
                                                            ( comparison-operator later ) 
                                                            ( scalar-expression 123 ) ) ) 
                                                    ( combinator nor ) ) 
                                                ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression 123 ) 
                                                        ( comparison-operator later ) 
                                                        ( scalar-expression 
                                                            ( point-in-time current-time ) ) ) ) 
                                                ( combinator or- ) ) ) ) 
                                    preposition 
                                    ( object reflexive ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type person ) ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol «baz» ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                    ( existence ( symbol «baz» ) 
                                                                                        equal fixed ) ) ) 
                                                                            ( combinand expiration ) 
                                                                            ( combinator and ) ) 
                                                                        ( combinand 
                                                                            ( negation 
                                                                                ( negator ) 
                                                                                ( symbol «baz» ) ) ) 
                                                                        ( combinator or- ) ) 
                                                                    ( combinand ( symbol «baz» ) 
                                                                        expiration ) 
                                                                    ( combinator neither ) ) 
                                                                ( combinand 
                                                                    ( existence ( symbol ( type text ) ) 
                                                                        being true ) ) 
                                                                ( combinator and ) ) ) 
                                                        ( combinor ( combinand expiration ) ) ) 
                                                    ( combinor ( combinand expiration ) ) 
                                                    ( combinator or- ) ) 
                                                ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol ( type amount ) ) 
                                                                                expiration ) ) 
                                                                        ( combinand expiration ) 
                                                                        ( combinator and ) ) 
                                                                    ( combinand ( symbol ( type binary ) ) ) 
                                                                    ( combinator neither ) ) 
                                                                ( combinand ( symbol ( type data ) ) ) 
                                                                ( combinator or- ) ) 
                                                            ( combinand expiration ) 
                                                            ( combinator and ) ) 
                                                        ( combinand expiration ) 
                                                        ( combinator neither ) ) 
                                                    ( combinand 
                                                        ( existence ( symbol ( type binary ) ) 
                                                            being true ) ) 
                                                    ( combinator nor ) ) 
                                                ( combinator neither ) ) 
                                            ( combinor ( combinand expiration ) ) 
                                            ( combinator neither ) ) ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol ( type person ) ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol ( type text ) ) ) ) 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combination ( combinor ( combinand 
                                                        ( existence ( symbol ( type text ) ) 
                                                            equal fixed ) ) ) ) 
                                            ( combinor ( combinor ( combinand 
                                                        ( negation 
                                                            ( negator be ) 
                                                            ( symbol ( type amount ) ) ) ) ) 
                                                ( combinand expiration ) 
                                                ( combinator or- ) ) 
                                            ( combinator neither ) ) ) 
                                    preposition 
                                    ( object ) 
                                    from-escrow ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol «baz» ) ) ) 
                            ( predicate 
                                ( termination terminate 
                                    ( this-contract «bar» ) ) ) 
                            ( predicate 
                                ( declaration declare ( symbol ( type amount ) ) 
                                    ( expression ( combination ( combinor ( combinand 
                                                    ( point-in-time 
                                                        ( relative-time 
                                                            ( duration 
                                                                ( scalar-expression 
                                                                    ( point-in-time 
                                                                        ( relative-time 
                                                                            ( duration 
                                                                                ( scalar-expression 123 ) 
                                                                                ( time-unit years ) ) 
                                                                            ( symbol «baz» ) ) ) ) 
                                                                ( time-unit seconds ) ) ) ) ) ) ) ) ) ) 
                            ( predicate 
                                ( declaration declare ( symbol ( type data ) ) 
                                    ( contract all-contracts ) ) ) ) 
                        permission 
                        ( condition if 
                            ( expression ( combination ( combinor ( combinor ( combinand 
                                                ( point-in-time 
                                                    ( relative-time 
                                                        ( duration 
                                                            ( scalar-expression 123 ) 
                                                            ( time-unit months ) ) 
                                                        ( symbol ( type person ) ) ) ) ) ) 
                                        ( combinand 
                                            ( negation 
                                                ( negator be ) 
                                                ( symbol ( type person ) ) 
                                                ( contract 
                                                    ( this-contract «bar» ) ) ) ) 
                                        ( combinator and ) ) ) ) ) ) ) 
                ( statement 
                    ( flagging 
                        ( illocutor be ) 
                        ( symbol ( type time ) ) 
                        ( this-contract «bar» ) ) ) 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols 
                                ( symbols 
                                    ( symbols 
                                        ( symbols 
                                            ( symbols ( symbol «baz» ) ) 
                                            ( symbol ( type data ) ) 
                                            catena ) 
                                        ( symbol ( type binary ) ) 
                                        catena ) 
                                    ( symbol «baz» ) 
                                    catena ) 
                                ( symbol «baz» ) 
                                catena ) ) 
                        ( predicates 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combination ( combinor ( combinand 
                                                        ( existence ( symbol ( type person ) ) 
                                                            be ) ) ) ) 
                                            ( combinor ( combinand ( symbol «baz» ) ) ) ) ) 
                                    preposition 
                                    ( object ( symbol ( type amount ) ) ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object reflexive ) 
                                    preposition 
                                    ( expression ( combination ( combinor ( combinor ( combinand 
                                                        ( existence ( symbol ( type data ) ) 
                                                            equal fixed ) ) ) 
                                                ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression ( symbol ( type time ) ) ) 
                                                        ( comparison-operator later ) 
                                                        ( scalar-expression ( symbol «baz» ) ) ) ) 
                                                ( combinator nor ) ) ) ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol «baz» ) ) ) 
                            ( predicate 
                                ( certification certify ( symbol ( type binary ) ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol ( type data ) ) ) ) 
                            ( predicate 
                                ( declaration declare ( symbol ( type person ) ) 
                                    ( expression ( combination ( combination ( combinor ( combinand 
                                                        ( existence ( symbol ( type person ) ) 
                                                            being true ) ) ) ) 
                                            ( combinor ( combinor ( combinand 
                                                        ( existence ( symbol «baz» ) 
                                                            be 
                                                            ( contract all-contracts ) ) ) ) 
                                                ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression ( symbol «baz» ) ) 
                                                        ( comparison-operator later ) 
                                                        ( scalar-expression 123 ) ) ) 
                                                ( combinator or- ) ) ) ) ) ) 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combination ( combination ( combination ( combinor ( combinand ( symbol «baz» ) ) ) ) 
                                                    ( combinor ( combinand ( symbol «baz» ) 
                                                            expiration ) ) ) 
                                                ( combinor ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression ( symbol «baz» ) ) 
                                                                    ( time-unit days ) ) ) ) ) ) 
                                                ( combinator neither ) ) 
                                            ( combinor ( combinor ( combinand expiration ) ) 
                                                ( combinand ( symbol ( type text ) ) 
                                                    expiration ) 
                                                ( combinator nor ) ) 
                                            ( combinator nor ) ) ) 
                                    preposition 
                                    ( object ( symbol ( type amount ) ) ) 
                                    from-escrow ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type amount ) ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type binary ) ) ) ) ) 
                        permission ) ) ) ) ) 
    ( covenants 
        ( covenant «qux-waldo» 
            ( provisions 
                ( definitions 
                    ( definition «qux-waldo» ( type person ) ) ) ) ) ) )
