( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «bar» ( type data ) ) ) 
            ( statements 
                ( statement 
                    ( flagging 
                        ( illocutor be ) 
                        ( symbol ( type time ) ) 
                        ( this-contract «bar» ) ) ) 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols ( symbol ( type person ) ) ) ) 
                        ( predicates 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combination ( combination ( combinor ( combinand 
                                                            ( existence ( symbol ( type binary ) ) 
                                                                equal fixed ) ) ) ) 
                                                ( combinor ( combinand ( symbol ( type person ) ) ) ) 
                                                ( combinator or- ) ) 
                                            ( combinor ( combinor ( combinand 
                                                        ( existence ( symbol ( type data ) ) 
                                                            be 
                                                            ( contract 
                                                                ( this-contract «bar» ) ) ) ) ) 
                                                ( combinand 
                                                    ( point-in-time current-time ) ) 
                                                ( combinator or- ) ) 
                                            ( combinator or- ) ) ) 
                                    preposition 
                                    ( object ( symbol «bar» ) ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type binary ) ) ) ) 
                            ( predicate 
                                ( declaration declare ( symbol «bar» ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol ( type person ) ) ) ) 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combinor ( combinand 
                                                    ( point-in-time 
                                                        ( relative-time 
                                                            ( duration 
                                                                ( scalar-expression ( symbol «bar» ) ) 
                                                                ( time-unit weeks ) ) ) ) ) ) ) ) 
                                    preposition 
                                    ( object ) 
                                    from-escrow ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type binary ) ) 
                                    ( expression ( combination ( combinor ( combinor ( combinand ( symbol ( type time ) ) 
                                                        expiration ) ) 
                                                ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression ( symbol ( type amount ) ) ) 
                                                        ( comparison-operator equal ) 
                                                        ( scalar-expression 123 ) ) ) 
                                                ( combinator or- ) ) ) ) ) ) 
                            ( predicate 
                                ( termination terminate 
                                    ( this-contract «bar» ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combination ( combinor ( combinor ( combinor ( combinand 
                                                                ( existence ( symbol ( type data ) ) 
                                                                    equal fixed ) ) ) 
                                                        ( combinand ( symbol ( type data ) ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinand 
                                                        ( existence ( symbol «bar» ) 
                                                            be ) ) 
                                                    ( combinator or- ) ) ) 
                                            ( combinor ( combinand 
                                                    ( point-in-time 
                                                        ( relative-time 
                                                            ( duration 
                                                                ( scalar-expression ( symbol ( type binary ) ) ) 
                                                                ( time-unit weeks ) ) 
                                                            ( symbol «bar» ) ) ) ) ) 
                                            ( combinator and ) ) ) 
                                    preposition 
                                    ( object reflexive ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol «bar» ) 
                                                                                expiration ) ) 
                                                                        ( combinand expiration ) 
                                                                        ( combinator and ) ) 
                                                                    ( combinand 
                                                                        ( negation 
                                                                            ( negator be ) 
                                                                            ( symbol «bar» ) ) ) 
                                                                    ( combinator and ) ) 
                                                                ( combinand ( symbol «bar» ) ) 
                                                                ( combinator nor ) ) 
                                                            ( combinand 
                                                                ( existence ( symbol ( type amount ) ) 
                                                                    being true ) ) 
                                                            ( combinator or- ) ) ) 
                                                    ( combinor ( combinand 
                                                            ( existence ( symbol ( type data ) ) 
                                                                being true ) ) ) ) 
                                                ( combinor ( combinor ( combinand expiration ) ) 
                                                    ( combinand expiration ) 
                                                    ( combinator or- ) ) 
                                                ( combinator nor ) ) 
                                            ( combinor ( combinand ( symbol ( type text ) ) ) ) ) ) 
                                    preposition 
                                    ( object ) ) ) 
                            ( predicate 
                                ( payment pay preposition 
                                    ( object ) 
                                    escrow ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol ( type data ) ) ) ) 
                            ( predicate 
                                ( registration register ( symbol ( type person ) ) 
                                    ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression ( symbol «bar» ) ) 
                                                                    ( comparison-operator equal ) 
                                                                    ( scalar-expression ( symbol «bar» ) ) ) ) ) 
                                                        ( combinand 
                                                            ( scalar-comparison 
                                                                ( scalar-expression 123 ) 
                                                                ( comparison-operator equal ) 
                                                                ( scalar-expression 123 ) ) ) 
                                                        ( combinator or- ) ) ) 
                                                ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                    ( existence ( symbol «bar» ) 
                                                                        equal fixed ) ) ) 
                                                            ( combinand 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression 
                                                                                                ( point-in-time current-time ) ) 
                                                                                            ( time-unit days ) ) ) ) ) 
                                                                            ( time-unit months ) ) 
                                                                        ( symbol ( type binary ) ) ) ) ) 
                                                            ( combinator or- ) ) 
                                                        ( combinand ( symbol ( type text ) ) ) 
                                                        ( combinator and ) ) 
                                                    ( combinand 
                                                        ( negation 
                                                            ( negator be ) 
                                                            ( symbol ( type time ) ) 
                                                            fixed ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinator or- ) ) 
                                            ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol «bar» ) 
                                                                    expiration ) ) 
                                                            ( combinand 
                                                                ( point-in-time current-time ) ) 
                                                            ( combinator and ) ) 
                                                        ( combinand 
                                                            ( negation 
                                                                ( negator be ) 
                                                                ( symbol ( type person ) ) 
                                                                fixed ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression 
                                                                ( point-in-time current-time ) ) 
                                                            ( comparison-operator equal ) 
                                                            ( scalar-expression ( symbol «bar» ) ) ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinand 
                                                    ( existence ( symbol ( type amount ) ) 
                                                        equal fixed ) ) 
                                                ( combinator neither ) ) 
                                            ( combinator and ) ) ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type binary ) ) 
                                    ( expression ( combination ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression ( symbol «bar» ) ) 
                                                                                            ( time-unit minutes ) ) 
                                                                                        ( symbol «bar» ) ) ) ) 
                                                                            ( time-unit months ) ) 
                                                                        ( symbol «bar» ) ) ) ) ) 
                                                        ( combinand ( symbol «bar» ) ) 
                                                        ( combinator or- ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression ( symbol «bar» ) ) 
                                                            ( comparison-operator equal ) 
                                                            ( scalar-expression 
                                                                ( point-in-time current-time ) ) ) ) 
                                                    ( combinator and ) ) 
                                                ( combinand 
                                                    ( point-in-time 
                                                        ( relative-time 
                                                            ( duration 
                                                                ( scalar-expression 
                                                                    ( point-in-time 
                                                                        ( relative-time 
                                                                            ( duration 
                                                                                ( scalar-expression ( symbol ( type data ) ) ) 
                                                                                ( time-unit hours ) ) ) ) ) 
                                                                ( time-unit minutes ) ) ) ) ) 
                                                ( combinator and ) ) ) ) ) ) 
                            ( predicate 
                                ( certification certify ( symbol ( type amount ) ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( setting be ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( registration register ( symbol ( type person ) ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type data ) ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «bar» ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( termination terminate all-contracts ) ) 
                            ( predicate 
                                ( setting be ( symbol ( type time ) ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combination ( combinor ( combinand expiration ) ) ) 
                                            ( combinor ( combinor ( combinand expiration ) ) 
                                                ( combinand expiration ) 
                                                ( combinator or- ) ) ) ) 
                                    preposition 
                                    ( object ( symbol ( type time ) ) ) ) ) 
                            ( predicate 
                                ( registration register ( symbol «bar» ) 
                                    ( expression ( combination ( combination ( combination ( combinor ( combinand 
                                                            ( negation 
                                                                ( negator ) 
                                                                ( symbol ( type amount ) ) ) ) ) ) 
                                                ( combinor ( combinand 
                                                        ( point-in-time current-time ) ) ) 
                                                ( combinator nor ) ) 
                                            ( combinor ( combinand expiration ) ) ) ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( registration register ( symbol ( type person ) ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( setting be ( symbol ( type time ) ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object ) 
                                    preposition 
                                    ( expression ( combination ( combinor ( combinor ( combinand ( symbol ( type text ) ) 
                                                        expiration ) ) 
                                                ( combinand ( symbol ( type data ) ) ) 
                                                ( combinator nor ) ) ) ) ) ) ) 
                        permission 
                        ( condition if 
                            ( expression ( combination ( combination ( combinor ( combinand 
                                                ( point-in-time 
                                                    ( relative-time 
                                                        ( duration 
                                                            ( scalar-expression 
                                                                ( point-in-time current-time ) ) 
                                                            ( time-unit days ) ) 
                                                        ( symbol ( type amount ) ) ) ) ) ) ) 
                                    ( combinor ( combinand 
                                            ( existence ( symbol «bar» ) 
                                                equal fixed ) ) ) ) ) ) ) ) ) ) ) 
    ( covenants 
        ( covenant «corge» 
            ( provisions 
                ( definitions 
                    ( definition «corge» 
                        ( this-contract «bar» ) ) 
                    ( definition «corge» ( type data ) ) 
                    ( definition «corge» 
                        ( this-contract «bar» ) ) 
                    ( definition «corge» ( type time ) ) 
                    ( definition «corge» 
                        ( this-contract «bar» ) ) 
                    ( definition «corge» 
                        ( this-contract «bar» ) ) 
                    ( definition «corge» ( type text ) ) 
                    ( definition «corge» 
                        ( this-contract «bar» ) ) 
                    ( definition «corge» 
                        ( this-contract «bar» ) ) ) ) ) 
        ( covenant «corge» 
            ( provisions 
                ( definitions 
                    ( definition «corge» ( type amount ) ) 
                    ( definition «corge» ( type data ) ) ) ) ) ) )
