
precompilation:
---------------

test law 05   1:   LEX: «Paid Escrow».
test law 05   2:   LEXON: ‹0.3.xx›.
test law 05   3:   COMMENT: ‹%PRE %GEN %JUR an escrow that is controlled by a third party for a fee.›.
test law 05   4:   LAW: New York“«Paying Party»” is a person.
test law 05   5:   “«Paid Party»” is a person.
test law 05   6:   “«Pay Master»” is a person.
test law 05   7:   “«Payment»” is an amount.
test law 05   8:   “«Payment Fee»” is an amount.
test law 05   9:   “«Non-Payment Fee»” is an amount.
test law 05  10:   “«Master's Fee»” is an amount.

test law 05  12:   The «Paying Party» pays a «Payment» into escrow,
test law 05  13:   appoints the «Paid Party»,
test law 05  14:   appoints the «Pay Master»,
test law 05  15:   and also fixes the «Master's Fee».

test law 05  17:   CLAUSE: «Make Payment».
test law 05  18:   The «Pay Master» may pay from escrow the «Master's Fee» to themselves,
test law 05  20:   and afterwards pay the remainder of the escrow to the «Paid Party».

test law 05  22:   CLAUSE: «Return Payment».
test law 05  23:   The «Pay Master» may pay from escrow the «Non-Payment Fee» to themselves,
test law 05  25:   and afterwards return the remainder of the escrow to the «Paying Party».


