( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «bar» ( type text ) ) ) 
            ( statements 
                ( statement 
                    ( flagging 
                        ( illocutor be ) 
                        ( symbol «bar» ) 
                        ( this-contract «bar» ) ) ) ) ) ) 
    ( covenants 
        ( covenant «fred-thud» 
            ( provisions 
                ( definitions 
                    ( definition «fred-thud» ( type time ) ) ) 
                ( clauses 
                    ( clause «xyzzy» 
                        ( body 
                            ( function «xyzzy» 
                                ( illocutor be ) 
                                ( expression ( combination ( combinor ( combinor ( combinand ( symbol ( type time ) ) 
                                                    expiration ) ) 
                                            ( combinand ( symbol ( type time ) ) ) 
                                            ( combinator neither ) ) ) ) ) ) ) 
                    ( clause «xyzzy-thud» 
                        ( body 
                            ( statements 
                                ( statement 
                                    ( flagging 
                                        ( illocutor be ) 
                                        ( symbol ( type data ) ) 
                                        ( this-contract «bar» ) ) ) 
                                ( statement 
                                    ( flagging 
                                        ( illocutor be ) 
                                        ( symbol «xyzzy-thud» ) 
                                        ( this-contract «bar» ) ) ) ) ) ) 
                    ( clause «foo-bar» 
                        ( body 
                            ( statements 
                                ( statement 
                                    ( flagging 
                                        ( illocutor be ) 
                                        ( symbol «foo-bar» ) 
                                        ( this-contract «bar» ) ) ) 
                                ( statement 
                                    ( flagging 
                                        ( illocutor be ) 
                                        ( symbol ( type data ) ) 
                                        ( this-contract «bar» ) ) ) ) ) ) 
                    ( clause «foo-foo-bar» 
                        ( body 
                            ( function «foo-foo-bar» 
                                ( illocutor be ) 
                                ( expression ( combination ( combination ( combination ( combinor ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression 123 ) 
                                                                                    ( time-unit years ) ) 
                                                                                ( symbol «foo-foo-bar» ) ) ) ) 
                                                                    ( time-unit milliseconds ) ) 
                                                                ( symbol «foo-foo-bar» ) ) ) ) ) ) 
                                            ( combinor ( combinand 
                                                    ( negation 
                                                        ( negator be ) 
                                                        ( symbol ( type text ) ) 
                                                        ( contract 
                                                            ( this-contract «bar» ) ) ) ) ) ) 
                                        ( combinor ( combinor ( combinand 
                                                    ( point-in-time current-time ) ) ) 
                                            ( combinand ( symbol «foo-foo-bar» ) 
                                                expiration ) 
                                            ( combinator or- ) ) 
                                        ( combinator neither ) ) ) ) ) ) 
                    ( clause «baz» 
                        ( body 
                            ( statements 
                                ( statement 
                                    ( flagging 
                                        ( illocutor be ) 
                                        ( symbol «baz» ) ) ) 
                                ( statement 
                                    ( action 
                                        ( subject 
                                            ( symbols ( symbol ( type binary ) ) ) ) 
                                        ( predicates 
                                            ( predicate 
                                                ( notification notify 
                                                    ( object ( symbol ( type text ) ) ) 
                                                    preposition 
                                                    ( expression ( combination ( combination ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                            ( negation 
                                                                                                ( negator be ) 
                                                                                                ( symbol ( type binary ) ) 
                                                                                                ( contract 
                                                                                                    ( this-contract «bar» ) ) ) ) ) 
                                                                                    ( combinand 
                                                                                        ( existence ( symbol ( type text ) ) 
                                                                                            being true ) ) 
                                                                                    ( combinator and ) ) 
                                                                                ( combinand 
                                                                                    ( scalar-comparison 
                                                                                        ( scalar-expression ( symbol «baz» ) ) 
                                                                                        ( comparison-operator equal ) 
                                                                                        ( scalar-expression ( symbol «baz» ) ) ) ) 
                                                                                ( combinator and ) ) 
                                                                            ( combinand 
                                                                                ( scalar-comparison 
                                                                                    ( scalar-expression ( symbol ( type binary ) ) ) 
                                                                                    ( comparison-operator later ) 
                                                                                    ( scalar-expression ( symbol ( type person ) ) ) ) ) 
                                                                            ( combinator and ) ) 
                                                                        ( combinand expiration ) 
                                                                        ( combinator or- ) ) 
                                                                    ( combinand ( symbol «baz» ) 
                                                                        expiration ) 
                                                                    ( combinator nor ) ) ) 
                                                            ( combinor ( combinor ( combinand 
                                                                        ( point-in-time current-time ) ) ) 
                                                                ( combinand expiration ) 
                                                                ( combinator or- ) ) 
                                                            ( combinator or- ) ) ) ) ) 
                                            ( predicate 
                                                ( grantment grant ( symbol ( type time ) ) ) ) 
                                            ( predicate 
                                                ( notification notify 
                                                    ( object reflexive ) 
                                                    preposition 
                                                    ( expression ( combination ( combination ( combination ( combinor ( combinand 
                                                                            ( existence ( symbol ( type binary ) ) 
                                                                                be 
                                                                                ( contract all-contracts ) ) ) ) ) 
                                                                ( combinor ( combinand ( symbol ( type binary ) ) 
                                                                        expiration ) ) ) 
                                                            ( combinor ( combinor ( combinand ( symbol ( type binary ) ) 
                                                                        expiration ) ) 
                                                                ( combinand ( symbol ( type data ) ) 
                                                                    expiration ) 
                                                                ( combinator and ) ) 
                                                            ( combinator and ) ) ) ) ) 
                                            ( predicate 
                                                ( registration register ( symbol «baz» ) 
                                                    ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinand 
                                                                                    ( negation 
                                                                                        ( negator be ) 
                                                                                        ( symbol «baz» ) 
                                                                                        fixed ) ) ) 
                                                                            ( combinand 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression 
                                                                                                ( point-in-time current-time ) ) 
                                                                                            ( time-unit milliseconds ) ) ) ) ) 
                                                                            ( combinator or- ) ) 
                                                                        ( combinand expiration ) 
                                                                        ( combinator or- ) ) ) 
                                                                ( combinor ( combinor ( combinand 
                                                                            ( scalar-comparison 
                                                                                ( scalar-expression ( symbol «baz» ) ) 
                                                                                ( comparison-operator later ) 
                                                                                ( scalar-expression 123 ) ) ) ) 
                                                                    ( combinand 
                                                                        ( scalar-comparison 
                                                                            ( scalar-expression 123 ) 
                                                                            ( comparison-operator equal ) 
                                                                            ( scalar-expression 
                                                                                ( point-in-time current-time ) ) ) ) 
                                                                    ( combinator and ) ) 
                                                                ( combinator neither ) ) 
                                                            ( combinor ( combinand expiration ) ) 
                                                            ( combinator nor ) ) ) ) ) 
                                            ( predicate 
                                                ( setting be ( symbol ( type time ) ) ) ) 
                                            ( predicate 
                                                ( registration register ( symbol «baz» ) 
                                                    ( expression ( combination ( combination ( combinor ( combinand 
                                                                        ( existence ( symbol ( type time ) ) 
                                                                            be 
                                                                            ( contract all-contracts ) ) ) ) ) 
                                                            ( combinor ( combinand expiration ) ) ) ) ) ) ) 
                                        permission 
                                        ( condition if 
                                            ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinand 
                                                                            ( point-in-time current-time ) ) ) 
                                                                    ( combinand 
                                                                        ( scalar-comparison 
                                                                            ( scalar-expression 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression 
                                                                                                ( point-in-time current-time ) ) 
                                                                                            ( time-unit months ) ) 
                                                                                        ( symbol ( type text ) ) ) ) ) 
                                                                            ( comparison-operator later ) 
                                                                            ( scalar-expression 123 ) ) ) 
                                                                    ( combinator nor ) ) 
                                                                ( combinand ( symbol «baz» ) ) 
                                                                ( combinator neither ) ) ) 
                                                        ( combinor ( combinor ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression ( symbol ( type binary ) ) ) 
                                                                        ( comparison-operator equal ) 
                                                                        ( scalar-expression 123 ) ) ) ) 
                                                            ( combinand 
                                                                ( negation 
                                                                    ( negator be ) 
                                                                    ( symbol «baz» ) 
                                                                    ( contract 
                                                                        ( this-contract «bar» ) ) ) ) 
                                                            ( combinator neither ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinor ( combinor ( combinor ( combinand ( symbol ( type time ) ) ) ) 
                                                            ( combinand ( symbol ( type person ) ) ) 
                                                            ( combinator or- ) ) 
                                                        ( combinand expiration ) 
                                                        ( combinator and ) ) ) ) ) ) ) 
                                ( statement 
                                    ( action 
                                        ( subject 
                                            ( symbols ( symbol ( type text ) ) ) ) 
                                        ( predicates 
                                            ( predicate 
                                                ( registration register ( symbol ( type text ) ) 
                                                    ( expression ( combination ( combinor ( combinor ( combinand ( symbol ( type binary ) ) ) ) 
                                                                ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression 123 ) 
                                                                        ( comparison-operator later ) 
                                                                        ( scalar-expression 
                                                                            ( point-in-time 
                                                                                ( relative-time 
                                                                                    ( duration 
                                                                                        ( scalar-expression 
                                                                                            ( point-in-time current-time ) ) 
                                                                                        ( time-unit days ) ) 
                                                                                    ( symbol «baz» ) ) ) ) ) ) 
                                                                ( combinator nor ) ) ) ) ) ) 
                                            ( predicate 
                                                ( sending send 
                                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combinor ( combinand ( symbol «baz» ) ) ) ) 
                                                                        ( combinor ( combinor ( combinor ( combinand 
                                                                                        ( existence ( symbol «baz» ) 
                                                                                            equal fixed ) ) ) 
                                                                                ( combinand expiration ) 
                                                                                ( combinator nor ) ) 
                                                                            ( combinand 
                                                                                ( negation 
                                                                                    ( negator be ) 
                                                                                    ( symbol ( type data ) ) ) ) 
                                                                            ( combinator or- ) ) ) 
                                                                    ( combinor ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                                                ( combinand 
                                                                                    ( point-in-time current-time ) ) 
                                                                                ( combinator and ) ) 
                                                                            ( combinand ( symbol ( type person ) ) ) 
                                                                            ( combinator or- ) ) 
                                                                        ( combinand 
                                                                            ( negation 
                                                                                ( negator ) 
                                                                                ( symbol ( type person ) ) 
                                                                                ( contract all-contracts ) ) ) 
                                                                        ( combinator neither ) ) ) 
                                                                ( combinor ( combinand 
                                                                        ( existence ( symbol «baz» ) 
                                                                            be ) ) ) 
                                                                ( combinator neither ) ) 
                                                            ( combinor ( combinor ( combinand 
                                                                        ( negation 
                                                                            ( negator be ) 
                                                                            ( symbol «baz» ) ) ) ) 
                                                                ( combinand 
                                                                    ( existence ( symbol «baz» ) 
                                                                        equal fixed ) ) 
                                                                ( combinator nor ) ) 
                                                            ( combinator nor ) ) ) 
                                                    preposition 
                                                    ( object ) ) ) 
                                            ( predicate 
                                                ( termination terminate all-contracts ) ) 
                                            ( predicate 
                                                ( notification notify 
                                                    ( object ( symbol «baz» ) ) 
                                                    preposition 
                                                    ( expression ( combination ( combinor ( combinor ( combinor ( combinand ( symbol «baz» ) 
                                                                            expiration ) ) 
                                                                    ( combinand ( symbol ( type text ) ) 
                                                                        expiration ) 
                                                                    ( combinator neither ) ) 
                                                                ( combinand 
                                                                    ( existence ( symbol «baz» ) 
                                                                        being true ) ) 
                                                                ( combinator or- ) ) ) ) ) ) 
                                            ( predicate 
                                                ( filing file ( symbol «baz» ) 
                                                    ( contract all-contracts ) ) ) 
                                            ( predicate 
                                                ( appointment appoint ( symbol ( type data ) ) ) ) 
                                            ( predicate 
                                                ( notification notify 
                                                    ( object ) 
                                                    preposition 
                                                    ( expression ( combination ( combinor ( combinand 
                                                                    ( point-in-time current-time ) ) ) ) ) ) ) 
                                            ( predicate 
                                                ( appointment appoint ( symbol «baz» ) ) ) 
                                            ( predicate 
                                                ( sending send 
                                                    ( expression ( combination ( combinor ( combinor ( combinor ( combinand 
                                                                            ( point-in-time current-time ) ) ) 
                                                                    ( combinand 
                                                                        ( point-in-time current-time ) ) 
                                                                    ( combinator or- ) ) 
                                                                ( combinand ( symbol ( type binary ) ) ) 
                                                                ( combinator or- ) ) ) ) 
                                                    preposition 
                                                    ( object ) ) ) 
                                            ( predicate 
                                                ( notification notify 
                                                    ( object reflexive ) 
                                                    preposition 
                                                    ( expression ( combination ( combinor ( combinor ( combinand ( symbol ( type data ) ) 
                                                                        expiration ) ) 
                                                                ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression 123 ) 
                                                                        ( comparison-operator equal ) 
                                                                        ( scalar-expression 
                                                                            ( point-in-time current-time ) ) ) ) 
                                                                ( combinator nor ) ) ) ) ) ) 
                                            ( predicate 
                                                ( certification certify ( symbol «baz» ) ) ) ) 
                                        permission 
                                        ( condition if 
                                            ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinand 
                                                                        ( scalar-comparison 
                                                                            ( scalar-expression ( symbol ( type text ) ) ) 
                                                                            ( comparison-operator later ) 
                                                                            ( scalar-expression ( symbol ( type person ) ) ) ) ) ) 
                                                                ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression 123 ) 
                                                                        ( comparison-operator equal ) 
                                                                        ( scalar-expression 123 ) ) ) 
                                                                ( combinator nor ) ) ) 
                                                        ( combinor ( combinand ( symbol «baz» ) 
                                                                expiration ) ) 
                                                        ( combinator or- ) ) 
                                                    ( combinor ( combinand 
                                                            ( negation 
                                                                ( negator ) 
                                                                ( symbol «baz» ) ) ) ) 
                                                    ( combinator and ) ) ) ) ) ) ) ) ) ) ) ) ) )
