
precompilation:
---------------

test law 03   1:   LEX: «Paid Escrow».
test law 03   2:   LEXON: ‹0.3.xx›.
test law 03   3:   COMMENT: ‹%PRE %GEN %JUR an escrow that is controlled by a third party for a fee.›.

library 1     1:   CLAUSE: «Deadline Past».
library 1     2:   "«Deadline Past»" is defined as a given Time being earlier than Today.
test law 03   6:   LAW: New York
test law 03   7:   “«Paying Party»” is a person.
test law 03   8:   “«Paid Party»” is a person.
test law 03   9:   “«Pay Master»” is a person.
test law 03  10:   “«Payment»” is an amount.
test law 03  11:   “«Payment Fee»” is an amount.
test law 03  12:   “«Non-Payment Fee»” is an amount.
test law 03  13:   “«Master's Fee»” is an amount.

test law 03  15:   The «Paying Party» pays a «Payment» into escrow,
test law 03  16:   appoints the «Paid Party»,
test law 03  17:   appoints the «Pay Master»,
test law 03  18:   and also fixes the «Master's Fee».

test law 03  20:   CLAUSE: «Make Payment».
test law 03  21:   The «Pay Master» may pay from escrow the «Master's Fee» to themselves,
test law 03  23:   and afterwards pay the remainder of the escrow to the «Paid Party».

test law 03  25:   CLAUSE: «Return Payment».
test law 03  26:   The «Pay Master» may pay from escrow the «Non-Payment Fee» to themselves,
test law 03  28:   and afterwards return the remainder of the escrow to the «Paying Party».


