( document 
    ( head 
        ( lex «foo-foo-baz» ) 
        ( preamble "Cum sociis natoque penatibus et.") 
        ( authors "Aenean massa. Cum sociis.") 
        ( lexon "Aenean commodo ligula.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «foo-bar» 
                    ( this-contract «foo-foo-baz» ) ) ) 
            ( clauses 
                ( clause «baz» 
                    ( body 
                        ( statements 
                            ( statement 
                                ( action 
                                    ( subject 
                                        ( symbols ( symbol ( type amount ) ) ) ) 
                                    ( predicates 
                                        ( predicate 
                                            ( termination terminate all-contracts ) ) 
                                        ( predicate 
                                            ( certification certify ( symbol ( type binary ) ) ) ) 
                                        ( predicate 
                                            ( appointment appoint ( symbol ( type time ) ) ) ) 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combination ( combinor ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                                        ( combinand ( symbol «baz» ) ) 
                                                                        ( combinator or- ) ) 
                                                                    ( combinand ( symbol ( type time ) ) ) 
                                                                    ( combinator and ) ) 
                                                                ( combinand 
                                                                    ( point-in-time current-time ) ) 
                                                                ( combinator neither ) ) ) 
                                                        ( combinor ( combinand 
                                                                ( negation 
                                                                    ( negator be ) 
                                                                    ( symbol ( type data ) ) 
                                                                    ( contract 
                                                                        ( this-contract «foo-foo-baz» ) ) ) ) ) ) ) 
                                                preposition 
                                                ( object ) 
                                                from-escrow ) ) 
                                        ( predicate 
                                            ( filing file ( symbol «baz» ) 
                                                ( expression ( combination ( combination ( combinor ( combinor ( combinand expiration ) ) 
                                                                ( combinand 
                                                                    ( point-in-time 
                                                                        ( relative-time 
                                                                            ( duration 
                                                                                ( scalar-expression ( symbol «baz» ) ) 
                                                                                ( time-unit days ) ) 
                                                                            ( symbol ( type text ) ) ) ) ) 
                                                                ( combinator neither ) ) ) 
                                                        ( combinor ( combinand 
                                                                ( negation 
                                                                    ( negator ) 
                                                                    ( symbol ( type text ) ) 
                                                                    fixed ) ) ) 
                                                        ( combinator nor ) ) ) ) ) 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combination ( combination ( combination ( combinor ( combinand ( symbol ( type time ) ) ) ) ) 
                                                                ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                        ( negation 
                                                                                            ( negator be ) 
                                                                                            ( symbol ( type binary ) ) ) ) ) 
                                                                                ( combinand ( symbol «baz» ) 
                                                                                    expiration ) 
                                                                                ( combinator nor ) ) 
                                                                            ( combinand 
                                                                                ( negation 
                                                                                    ( negator ) 
                                                                                    ( symbol ( type binary ) ) ) ) 
                                                                            ( combinator and ) ) 
                                                                        ( combinand 
                                                                            ( negation 
                                                                                ( negator ) 
                                                                                ( symbol ( type text ) ) 
                                                                                fixed ) ) 
                                                                        ( combinator or- ) ) 
                                                                    ( combinand ( symbol «baz» ) ) 
                                                                    ( combinator and ) ) ) 
                                                            ( combinor ( combinor ( combinand ( symbol «baz» ) ) ) 
                                                                ( combinand 
                                                                    ( negation 
                                                                        ( negator be ) 
                                                                        ( symbol «baz» ) ) ) 
                                                                ( combinator nor ) ) 
                                                            ( combinator and ) ) 
                                                        ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                    ( existence ( symbol ( type time ) ) 
                                                                                        equal fixed ) ) ) 
                                                                            ( combinand ( symbol «baz» ) 
                                                                                expiration ) 
                                                                            ( combinator nor ) ) 
                                                                        ( combinand 
                                                                            ( scalar-comparison 
                                                                                ( scalar-expression 123 ) 
                                                                                ( comparison-operator equal ) 
                                                                                ( scalar-expression ( symbol «baz» ) ) ) ) 
                                                                        ( combinator nor ) ) 
                                                                    ( combinand 
                                                                        ( existence ( symbol «baz» ) 
                                                                            equal fixed ) ) 
                                                                    ( combinator neither ) ) 
                                                                ( combinand 
                                                                    ( negation 
                                                                        ( negator ) 
                                                                        ( symbol ( type text ) ) 
                                                                        ( contract all-contracts ) ) ) 
                                                                ( combinator and ) ) 
                                                            ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression 123 ) 
                                                                    ( comparison-operator later ) 
                                                                    ( scalar-expression 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression ( symbol «baz» ) ) 
                                                                                    ( time-unit years ) ) 
                                                                                ( symbol «baz» ) ) ) ) ) ) 
                                                            ( combinator neither ) ) ) ) 
                                                preposition 
                                                ( object ( symbol ( type time ) ) ) 
                                                from-escrow ) ) 
                                        ( predicate 
                                            ( filing file ( symbol «baz» ) 
                                                ( contract 
                                                    ( this-contract «foo-foo-baz» ) ) ) ) 
                                        ( predicate 
                                            ( declaration declare ( symbol «baz» ) 
                                                ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinand 
                                                                            ( negation 
                                                                                ( negator be ) 
                                                                                ( symbol ( type person ) ) 
                                                                                ( contract 
                                                                                    ( this-contract «foo-foo-baz» ) ) ) ) ) 
                                                                    ( combinand 
                                                                        ( existence ( symbol «baz» ) 
                                                                            be ) ) 
                                                                    ( combinator and ) ) ) 
                                                            ( combinor ( combinand ( symbol «baz» ) 
                                                                    expiration ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinor ( combinor ( combinand 
                                                                    ( negation 
                                                                        ( negator ) 
                                                                        ( symbol ( type amount ) ) 
                                                                        fixed ) ) ) 
                                                            ( combinand 
                                                                ( existence ( symbol «baz» ) 
                                                                    be ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinator or- ) ) ) ) ) 
                                        ( predicate 
                                            ( appointment appoint ( symbol «baz» ) ) ) 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combination ( combination ( combination ( combination ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinand 
                                                                                                        ( existence ( symbol ( type data ) ) 
                                                                                                            be ) ) ) 
                                                                                                ( combinand ( symbol «baz» ) ) 
                                                                                                ( combinator neither ) ) 
                                                                                            ( combinand ( symbol «baz» ) ) 
                                                                                            ( combinator neither ) ) ) 
                                                                                    ( combinor ( combinand ( symbol ( type amount ) ) 
                                                                                            expiration ) ) 
                                                                                    ( combinator and ) ) 
                                                                                ( combinor ( combinand ( symbol «baz» ) ) ) 
                                                                                ( combinator neither ) ) 
                                                                            ( combinor ( combinor ( combinor ( combinand 
                                                                                            ( negation 
                                                                                                ( negator be ) 
                                                                                                ( symbol «baz» ) 
                                                                                                fixed ) ) ) 
                                                                                    ( combinand 
                                                                                        ( scalar-comparison 
                                                                                            ( scalar-expression 
                                                                                                ( point-in-time current-time ) ) 
                                                                                            ( comparison-operator equal ) 
                                                                                            ( scalar-expression 
                                                                                                ( point-in-time 
                                                                                                    ( relative-time 
                                                                                                        ( duration 
                                                                                                            ( scalar-expression 123 ) 
                                                                                                            ( time-unit minutes ) ) ) ) ) ) ) 
                                                                                    ( combinator neither ) ) 
                                                                                ( combinand ( symbol «baz» ) ) 
                                                                                ( combinator and ) ) 
                                                                            ( combinator neither ) ) 
                                                                        ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                                                ( combinand 
                                                                                    ( negation 
                                                                                        ( negator ) 
                                                                                        ( symbol ( type binary ) ) 
                                                                                        fixed ) ) 
                                                                                ( combinator neither ) ) 
                                                                            ( combinand expiration ) 
                                                                            ( combinator neither ) ) 
                                                                        ( combinator or- ) ) 
                                                                    ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                        ( negation 
                                                                                            ( negator be ) 
                                                                                            ( symbol ( type amount ) ) 
                                                                                            ( contract 
                                                                                                ( this-contract «foo-foo-baz» ) ) ) ) ) 
                                                                                ( combinand 
                                                                                    ( negation 
                                                                                        ( negator ) 
                                                                                        ( symbol «baz» ) ) ) 
                                                                                ( combinator neither ) ) 
                                                                            ( combinand ( symbol ( type amount ) ) 
                                                                                expiration ) 
                                                                            ( combinator and ) ) 
                                                                        ( combinand 
                                                                            ( scalar-comparison 
                                                                                ( scalar-expression ( symbol ( type person ) ) ) 
                                                                                ( comparison-operator later ) 
                                                                                ( scalar-expression ( symbol «baz» ) ) ) ) 
                                                                        ( combinator or- ) ) ) 
                                                                ( combinor ( combinor ( combinand ( symbol ( type time ) ) ) ) 
                                                                    ( combinand 
                                                                        ( point-in-time current-time ) ) 
                                                                    ( combinator and ) ) 
                                                                ( combinator nor ) ) 
                                                            ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                ( point-in-time current-time ) ) ) 
                                                                        ( combinand ( symbol ( type amount ) ) ) 
                                                                        ( combinator neither ) ) 
                                                                    ( combinand 
                                                                        ( point-in-time current-time ) ) 
                                                                    ( combinator or- ) ) 
                                                                ( combinand expiration ) 
                                                                ( combinator nor ) ) ) 
                                                        ( combinor ( combinand expiration ) ) ) ) 
                                                preposition 
                                                ( object ) 
                                                from-escrow ) ) 
                                        ( predicate 
                                            ( payment pay preposition 
                                                ( object reflexive ) 
                                                escrow ) ) 
                                        ( predicate 
                                            ( appointment appoint ( symbol ( type text ) ) ) ) 
                                        ( predicate 
                                            ( grantment grant ( symbol ( type time ) ) ) ) 
                                        ( predicate 
                                            ( registration register ( symbol ( type binary ) ) 
                                                ( contract 
                                                    ( this-contract «foo-foo-baz» ) ) ) ) 
                                        ( predicate 
                                            ( appointment appoint ( symbol ( type binary ) ) ) ) 
                                        ( predicate 
                                            ( grantment grant ( symbol «baz» ) ) ) 
                                        ( predicate 
                                            ( appointment appoint ( symbol «baz» ) ) ) 
                                        ( predicate 
                                            ( setting 
                                                ( illocutor be ) 
                                                ( symbol «baz» ) ) ) 
                                        ( predicate 
                                            ( declaration declare ( symbol ( type amount ) ) ) ) 
                                        ( predicate 
                                            ( notification notify 
                                                ( object ) 
                                                preposition 
                                                ( expression ( combination ( combination ( combination ( combinor ( combinand ( symbol «baz» ) 
                                                                        expiration ) ) ) 
                                                            ( combinor ( combinor ( combinor ( combinand 
                                                                            ( point-in-time 
                                                                                ( relative-time 
                                                                                    ( duration 
                                                                                        ( scalar-expression 123 ) 
                                                                                        ( time-unit hours ) ) 
                                                                                    ( symbol ( type text ) ) ) ) ) ) 
                                                                    ( combinand 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression 123 ) 
                                                                                    ( time-unit years ) ) 
                                                                                ( symbol ( type data ) ) ) ) ) 
                                                                    ( combinator or- ) ) 
                                                                ( combinand 
                                                                    ( existence ( symbol «baz» ) 
                                                                        be 
                                                                        ( contract 
                                                                            ( this-contract «foo-foo-baz» ) ) ) ) 
                                                                ( combinator and ) ) 
                                                            ( combinator neither ) ) 
                                                        ( combinor ( combinand 
                                                                ( existence ( symbol «baz» ) 
                                                                    equal fixed ) ) ) 
                                                        ( combinator or- ) ) ) ) ) 
                                        ( predicate 
                                            ( setting 
                                                ( illocutor be ) 
                                                ( symbol ( type data ) ) ) ) 
                                        ( predicate 
                                            ( sending send 
                                                ( expression ( combination ( combination ( combinor ( combinor ( combinand 
                                                                        ( scalar-comparison 
                                                                            ( scalar-expression 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression 123 ) 
                                                                                            ( time-unit years ) ) ) ) ) 
                                                                            ( comparison-operator later ) 
                                                                            ( scalar-expression ( symbol ( type text ) ) ) ) ) ) 
                                                                ( combinand expiration ) 
                                                                ( combinator and ) ) ) 
                                                        ( combinor ( combinor ( combinand ( symbol «baz» ) ) ) 
                                                            ( combinand 
                                                                ( existence ( symbol ( type amount ) ) 
                                                                    be ) ) 
                                                            ( combinator and ) ) ) ) 
                                                preposition 
                                                ( object ( symbol «baz» ) ) ) ) 
                                        ( predicate 
                                            ( certification certify ( symbol «baz» ) 
                                                ( expression ( combination ( combinor ( combinand ( symbol ( type data ) ) ) ) ) ) ) ) 
                                        ( predicate 
                                            ( sending send 
                                                ( expression ( combination ( combination ( combinor ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression ( symbol ( type time ) ) ) 
                                                                        ( comparison-operator later ) 
                                                                        ( scalar-expression 
                                                                            ( point-in-time current-time ) ) ) ) ) ) 
                                                        ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                    ( existence ( symbol «baz» ) 
                                                                                        be 
                                                                                        ( contract 
                                                                                            ( this-contract «foo-foo-baz» ) ) ) ) ) 
                                                                            ( combinand ( symbol «baz» ) ) 
                                                                            ( combinator nor ) ) 
                                                                        ( combinand 
                                                                            ( existence ( symbol ( type amount ) ) 
                                                                                being true ) ) 
                                                                        ( combinator and ) ) 
                                                                    ( combinand 
                                                                        ( point-in-time current-time ) ) 
                                                                    ( combinator or- ) ) 
                                                                ( combinand ( symbol ( type amount ) ) 
                                                                    expiration ) 
                                                                ( combinator and ) ) 
                                                            ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression ( symbol ( type person ) ) ) 
                                                                                    ( time-unit months ) ) 
                                                                                ( symbol «baz» ) ) ) ) 
                                                                    ( comparison-operator later ) 
                                                                    ( scalar-expression 123 ) ) ) 
                                                            ( combinator neither ) ) 
                                                        ( combinator or- ) ) ) 
                                                preposition 
                                                ( object ) ) ) 
                                        ( predicate 
                                            ( registration register ( symbol ( type person ) ) 
                                                ( contract all-contracts ) ) ) 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combinor ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression ( symbol ( type binary ) ) ) 
                                                                    ( comparison-operator equal ) 
                                                                    ( scalar-expression ( symbol «baz» ) ) ) ) ) ) ) 
                                                preposition 
                                                ( object ) 
                                                from-escrow ) ) 
                                        ( predicate 
                                            ( grantment grant ( symbol ( type time ) ) ) ) 
                                        ( predicate 
                                            ( grantment grant ( symbol «baz» ) ) ) 
                                        ( predicate 
                                            ( setting 
                                                ( illocutor be ) 
                                                ( symbol «baz» ) ) ) 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combination ( combination ( combination ( combination ( combination ( combinor ( combinand 
                                                                                    ( existence ( symbol ( type text ) ) 
                                                                                        be 
                                                                                        ( contract 
                                                                                            ( this-contract «foo-foo-baz» ) ) ) ) ) ) 
                                                                        ( combinor ( combinor ( combinand 
                                                                                    ( scalar-comparison 
                                                                                        ( scalar-expression 123 ) 
                                                                                        ( comparison-operator later ) 
                                                                                        ( scalar-expression ( symbol «baz» ) ) ) ) ) 
                                                                            ( combinand ( symbol ( type data ) ) 
                                                                                expiration ) 
                                                                            ( combinator neither ) ) ) 
                                                                    ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                            ( scalar-comparison 
                                                                                                ( scalar-expression ( symbol «baz» ) ) 
                                                                                                ( comparison-operator later ) 
                                                                                                ( scalar-expression ( symbol ( type amount ) ) ) ) ) ) 
                                                                                    ( combinand 
                                                                                        ( point-in-time 
                                                                                            ( relative-time 
                                                                                                ( duration 
                                                                                                    ( scalar-expression 
                                                                                                        ( point-in-time 
                                                                                                            ( relative-time 
                                                                                                                ( duration 
                                                                                                                    ( scalar-expression 123 ) 
                                                                                                                    ( time-unit weeks ) ) 
                                                                                                                ( symbol «baz» ) ) ) ) 
                                                                                                    ( time-unit hours ) ) 
                                                                                                ( symbol ( type amount ) ) ) ) ) 
                                                                                    ( combinator neither ) ) 
                                                                                ( combinand 
                                                                                    ( negation 
                                                                                        ( negator be ) 
                                                                                        ( symbol «baz» ) ) ) 
                                                                                ( combinator and ) ) 
                                                                            ( combinand 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression ( symbol ( type person ) ) ) 
                                                                                            ( time-unit seconds ) ) 
                                                                                        ( symbol ( type data ) ) ) ) ) 
                                                                            ( combinator nor ) ) 
                                                                        ( combinand ( symbol ( type text ) ) ) 
                                                                        ( combinator and ) ) 
                                                                    ( combinator nor ) ) 
                                                                ( combinor ( combinand 
                                                                        ( scalar-comparison 
                                                                            ( scalar-expression ( symbol «baz» ) ) 
                                                                            ( comparison-operator equal ) 
                                                                            ( scalar-expression 123 ) ) ) ) ) 
                                                            ( combinor ( combinand 
                                                                    ( existence ( symbol «baz» ) 
                                                                        be ) ) ) ) 
                                                        ( combinor ( combinand expiration ) ) ) ) 
                                                preposition 
                                                ( object ) 
                                                from-escrow ) ) 
                                        ( predicate 
                                            ( fixture fix ( symbol ( type person ) ) ) ) 
                                        ( predicate 
                                            ( termination terminate 
                                                ( this-contract «foo-foo-baz» ) ) ) 
                                        ( predicate 
                                            ( payment pay 
                                                ( expression ( combination ( combination ( combinor ( combinand ( symbol «baz» ) ) ) ) 
                                                        ( combinor ( combinand 
                                                                ( negation 
                                                                    ( negator ) 
                                                                    ( symbol ( type binary ) ) ) ) ) 
                                                        ( combinator neither ) ) ) 
                                                preposition 
                                                ( object ( symbol ( type time ) ) ) 
                                                from-escrow ) ) 
                                        ( predicate 
                                            ( fixture fix ( symbol ( type text ) ) 
                                                ( contract 
                                                    ( this-contract «foo-foo-baz» ) ) ) ) 
                                        ( predicate 
                                            ( registration register ( symbol «baz» ) 
                                                ( expression ( combination ( combinor ( combinand expiration ) ) ) ) ) ) 
                                        ( predicate 
                                            ( notification notify 
                                                ( object ) 
                                                preposition 
                                                ( expression ( combination ( combination ( combinor ( combinand expiration ) ) ) 
                                                        ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                            ( scalar-comparison 
                                                                                ( scalar-expression ( symbol «baz» ) ) 
                                                                                ( comparison-operator later ) 
                                                                                ( scalar-expression 123 ) ) ) ) 
                                                                    ( combinand 
                                                                        ( point-in-time current-time ) ) 
                                                                    ( combinator nor ) ) 
                                                                ( combinand 
                                                                    ( point-in-time 
                                                                        ( relative-time 
                                                                            ( duration 
                                                                                ( scalar-expression 
                                                                                    ( point-in-time current-time ) ) 
                                                                                ( time-unit seconds ) ) 
                                                                            ( symbol «baz» ) ) ) ) 
                                                                ( combinator nor ) ) 
                                                            ( combinand 
                                                                ( negation 
                                                                    ( negator ) 
                                                                    ( symbol ( type time ) ) ) ) 
                                                            ( combinator or- ) ) ) ) ) ) 
                                        ( predicate 
                                            ( notification notify 
                                                ( object ( symbol «baz» ) ) 
                                                preposition 
                                                ( expression ( combination ( combinor ( combinand 
                                                                ( negation 
                                                                    ( negator be ) 
                                                                    ( symbol «baz» ) 
                                                                    fixed ) ) ) ) ) ) ) 
                                        ( predicate 
                                            ( notification notify 
                                                ( object ( symbol «baz» ) ) 
                                                preposition 
                                                ( expression ( combination ( combinor ( combinand expiration ) ) ) ) ) ) 
                                        ( predicate 
                                            ( setting 
                                                ( illocutor be ) 
                                                ( symbol ( type data ) ) ) ) 
                                        ( predicate 
                                            ( filing file ( symbol «baz» ) ) ) 
                                        ( predicate 
                                            ( appointment appoint ( symbol ( type person ) ) ) ) 
                                        ( predicate 
                                            ( sending send 
                                                ( expression ( combination ( combination ( combinor ( combinor ( combinand ( symbol «baz» ) 
                                                                        expiration ) ) 
                                                                ( combinand expiration ) 
                                                                ( combinator nor ) ) ) 
                                                        ( combinor ( combinand 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression ( symbol «baz» ) ) 
                                                                            ( time-unit years ) ) ) ) ) ) ) ) 
                                                preposition 
                                                ( object reflexive ) ) ) ) 
                                    permission 
                                    ( condition if 
                                        ( expression ( combination ( combinor ( combinor ( combinand 
                                                            ( point-in-time current-time ) ) ) 
                                                    ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression 
                                                                        ( point-in-time current-time ) ) 
                                                                    ( time-unit years ) ) 
                                                                ( symbol ( type person ) ) ) ) ) 
                                                    ( combinator or- ) ) ) ) ) ) ) 
                            ( statement 
                                ( flagging 
                                    ( illocutor be ) 
                                    ( symbol ( type binary ) ) ) ) ) ) ) ) ) ) 
    ( covenants 
        ( covenant «baz» 
            ( provisions 
                ( definitions 
                    ( definition «baz» ( type text ) ) ) 
                ( clauses 
                    ( clause «qux» 
                        ( body 
                            ( function «qux» 
                                ( illocutor be ) 
                                ( expression ( combination ( combination ( combination ( combinor ( combinand expiration ) ) ) 
                                            ( combinor ( combinor ( combinand ( symbol «qux» ) ) ) 
                                                ( combinand expiration ) 
                                                ( combinator or- ) ) ) 
                                        ( combinor ( combinand expiration ) ) 
                                        ( combinator neither ) ) ) ) ) ) 
                    ( clause «corge» 
                        ( body 
                            ( function «corge» 
                                ( illocutor be ) 
                                ( expression ( combination ( combination ( combinor ( combinand ( symbol «corge» ) 
                                                    expiration ) ) ) 
                                        ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol «corge» ) 
                                                            expiration ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression 123 ) 
                                                                            ( time-unit years ) ) ) ) ) 
                                                            ( comparison-operator later ) 
                                                            ( scalar-expression 
                                                                ( point-in-time current-time ) ) ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinand 
                                                    ( existence ( symbol «corge» ) 
                                                        equal fixed ) ) 
                                                ( combinator nor ) ) 
                                            ( combinand 
                                                ( point-in-time 
                                                    ( relative-time 
                                                        ( duration 
                                                            ( scalar-expression 
                                                                ( point-in-time current-time ) ) 
                                                            ( time-unit hours ) ) 
                                                        ( symbol «corge» ) ) ) ) 
                                            ( combinator neither ) ) 
                                        ( combinator nor ) ) ) ) ) ) ) ) ) ) )
