( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «bar» ( type data ) ) ) 
            ( statements 
                ( statement 
                    ( flagging 
                        ( illocutor be ) 
                        ( symbol «bar» ) 
                        ( this-contract «bar» ) ) ) ) ) ) 
    ( covenants 
        ( covenant «corge-thud» 
            ( provisions 
                ( definitions 
                    ( definition «corge-thud» 
                        ( this-contract «bar» ) ) 
                    ( definition «corge-thud» 
                        ( this-contract «bar» ) ) ) 
                ( statements 
                    ( statement 
                        ( flagging 
                            ( illocutor be ) 
                            ( symbol ( type text ) ) ) ) ) ) ) ) )
