	%token Appointment_Predicate
	%token Appoints
	%token Be
	%token Party
	%token Somebody
	%token To
	
	Appointment_Predicate:	
		  Appoints Somebody                               { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; root=process_appointment(Appointment); }
		| Appoints Somebody Party                         { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoints Somebody Be                            { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; root=process_appointment(Appointment); }
		| Appoints Somebody Be Party                      { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoints Somebody To                            { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; root=process_appointment(Appointment); }
		| Appoints Somebody To Party                      { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoints Somebody To Be                         { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; root=process_appointment(Appointment); }
		| Appoints Somebody To Be Party                   { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
