( document 
    ( head 
        ( lex «fred» ) 
        ( preamble "In.") 
        ( authors "Donec pede justo, fringilla vel, aliquet nec,.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «garply-plugh-bar» ( type person ) ) ) 
            ( statements 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols ( symbol ( type binary ) ) ) ) 
                        ( predicates 
                            ( predicate 
                                ( declaration declare ( symbol «garply-plugh-bar» ) 
                                    ( contract 
                                        ( this-contract «fred» ) ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                                    ( combinand ( symbol «garply-plugh-bar» ) ) 
                                                                    ( combinator and ) ) 
                                                                ( combinand ( symbol ( type text ) ) ) 
                                                                ( combinator and ) ) 
                                                            ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression 
                                                                        ( point-in-time current-time ) ) 
                                                                    ( comparison-operator later ) 
                                                                    ( scalar-expression 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression 123 ) 
                                                                                    ( time-unit seconds ) ) 
                                                                                ( symbol ( type person ) ) ) ) ) ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand expiration ) 
                                                        ( combinator or- ) ) ) 
                                                ( combinor ( combinand 
                                                        ( existence ( symbol ( type text ) ) 
                                                            being true ) ) ) ) 
                                            ( combinor ( combinor ( combinand 
                                                        ( negation 
                                                            ( negator be ) 
                                                            ( symbol «garply-plugh-bar» ) 
                                                            fixed ) ) ) 
                                                ( combinand ( symbol ( type binary ) ) 
                                                    expiration ) 
                                                ( combinator nor ) ) ) ) 
                                    preposition 
                                    ( object reflexive ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object ) 
                                    preposition 
                                    ( expression ( combination ( combinor ( combinand ( symbol ( type amount ) ) 
                                                    expiration ) ) ) ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol «garply-plugh-bar» ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type amount ) ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol ( type data ) ) ) ) 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combinor ( combinand expiration ) ) ) 
                                                        ( combinor ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression 123 ) 
                                                                    ( comparison-operator later ) 
                                                                    ( scalar-expression 
                                                                        ( point-in-time current-time ) ) ) ) ) 
                                                        ( combinator or- ) ) 
                                                    ( combinor ( combinor ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression 123 ) 
                                                                    ( comparison-operator equal ) 
                                                                    ( scalar-expression ( symbol «garply-plugh-bar» ) ) ) ) ) 
                                                        ( combinand 
                                                            ( point-in-time current-time ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinator nor ) ) 
                                                ( combinor ( combinor ( combinand ( symbol «garply-plugh-bar» ) 
                                                            expiration ) ) 
                                                    ( combinand 
                                                        ( negation 
                                                            ( negator be ) 
                                                            ( symbol «garply-plugh-bar» ) ) ) 
                                                    ( combinator nor ) ) 
                                                ( combinator nor ) ) 
                                            ( combinor ( combinand expiration ) ) ) ) 
                                    preposition 
                                    ( object ( symbol ( type person ) ) ) 
                                    from-escrow ) ) 
                            ( predicate 
                                ( registration register ( symbol «garply-plugh-bar» ) ) ) ) 
                        permission ) ) 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols 
                                ( symbols 
                                    ( symbols 
                                        ( symbols ( symbol «garply-plugh-bar» ) ) 
                                        ( symbol «garply-plugh-bar» ) 
                                        catena ) 
                                    ( symbol «garply-plugh-bar» ) 
                                    catena ) 
                                ( symbol «garply-plugh-bar» ) 
                                catena ) ) 
                        ( predicates 
                            ( predicate 
                                ( notification notify 
                                    ( object reflexive ) 
                                    preposition 
                                    ( expression ( combination ( combinor ( combinand expiration ) ) ) ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol ( type text ) ) ) ) 
                            ( predicate 
                                ( termination terminate 
                                    ( this-contract «fred» ) ) ) 
                            ( predicate 
                                ( termination terminate all-contracts ) ) 
                            ( predicate 
                                ( fixture fix ( symbol ( type text ) ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol ( type time ) ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object ( symbol «garply-plugh-bar» ) ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combinor ( combinand 
                                                        ( negation 
                                                            ( negator ) 
                                                            ( symbol «garply-plugh-bar» ) ) ) ) ) 
                                            ( combinor ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression 123 ) 
                                                        ( comparison-operator equal ) 
                                                        ( scalar-expression ( symbol «garply-plugh-bar» ) ) ) ) ) 
                                            ( combinator nor ) ) ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol «garply-plugh-bar» ) ) ) 
                            ( predicate 
                                ( termination terminate 
                                    ( this-contract «fred» ) ) ) 
                            ( predicate 
                                ( filing file ( symbol «garply-plugh-bar» ) ) ) 
                            ( predicate 
                                ( registration register ( symbol ( type text ) ) 
                                    ( expression ( combination ( combinor ( combinor ( combinor ( combinand 
                                                            ( scalar-comparison 
                                                                ( scalar-expression 123 ) 
                                                                ( comparison-operator later ) 
                                                                ( scalar-expression 
                                                                    ( point-in-time 
                                                                        ( relative-time 
                                                                            ( duration 
                                                                                ( scalar-expression 123 ) 
                                                                                ( time-unit minutes ) ) ) ) ) ) ) ) 
                                                    ( combinand 
                                                        ( negation 
                                                            ( negator ) 
                                                            ( symbol «garply-plugh-bar» ) 
                                                            fixed ) ) 
                                                    ( combinator and ) ) 
                                                ( combinand 
                                                    ( existence ( symbol ( type data ) ) 
                                                        be 
                                                        ( contract all-contracts ) ) ) 
                                                ( combinator or- ) ) ) ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinand ( symbol «garply-plugh-bar» ) 
                                                                                expiration ) ) 
                                                                        ( combinand ( symbol ( type time ) ) ) 
                                                                        ( combinator or- ) ) ) 
                                                                ( combinor ( combinand 
                                                                        ( existence ( symbol «garply-plugh-bar» ) 
                                                                            equal fixed ) ) ) 
                                                                ( combinator and ) ) 
                                                            ( combinor ( combinor ( combinand expiration ) ) 
                                                                ( combinand ( symbol «garply-plugh-bar» ) ) 
                                                                ( combinator neither ) ) ) 
                                                        ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol ( type binary ) ) 
                                                                                        expiration ) ) 
                                                                                ( combinand 
                                                                                    ( negation 
                                                                                        ( negator ) 
                                                                                        ( symbol «garply-plugh-bar» ) 
                                                                                        ( contract all-contracts ) ) ) 
                                                                                ( combinator or- ) ) 
                                                                            ( combinand expiration ) 
                                                                            ( combinator nor ) ) 
                                                                        ( combinand 
                                                                            ( scalar-comparison 
                                                                                ( scalar-expression ( symbol ( type binary ) ) ) 
                                                                                ( comparison-operator later ) 
                                                                                ( scalar-expression 123 ) ) ) 
                                                                        ( combinator neither ) ) 
                                                                    ( combinand expiration ) 
                                                                    ( combinator and ) ) 
                                                                ( combinand ( symbol «garply-plugh-bar» ) ) 
                                                                ( combinator nor ) ) 
                                                            ( combinand 
                                                                ( negation 
                                                                    ( negator ) 
                                                                    ( symbol «garply-plugh-bar» ) ) ) 
                                                            ( combinator neither ) ) ) 
                                                    ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                        ( negation 
                                                                            ( negator be ) 
                                                                            ( symbol ( type binary ) ) ) ) ) 
                                                                ( combinand ( symbol ( type person ) ) ) 
                                                                ( combinator neither ) ) 
                                                            ( combinand 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression 123 ) 
                                                                            ( time-unit seconds ) ) 
                                                                        ( symbol «garply-plugh-bar» ) ) ) ) 
                                                            ( combinator and ) ) 
                                                        ( combinand 
                                                            ( scalar-comparison 
                                                                ( scalar-expression 123 ) 
                                                                ( comparison-operator later ) 
                                                                ( scalar-expression 123 ) ) ) 
                                                        ( combinator nor ) ) ) 
                                                ( combinor ( combinand 
                                                        ( negation 
                                                            ( negator ) 
                                                            ( symbol ( type amount ) ) 
                                                            ( contract all-contracts ) ) ) ) ) 
                                            ( combinor ( combinor ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression ( symbol ( type binary ) ) ) 
                                                            ( comparison-operator later ) 
                                                            ( scalar-expression 
                                                                ( point-in-time current-time ) ) ) ) ) 
                                                ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression 123 ) 
                                                        ( comparison-operator later ) 
                                                        ( scalar-expression 
                                                            ( point-in-time 
                                                                ( relative-time 
                                                                    ( duration 
                                                                        ( scalar-expression 
                                                                            ( point-in-time current-time ) ) 
                                                                        ( time-unit weeks ) ) ) ) ) ) ) 
                                                ( combinator neither ) ) ) ) 
                                    preposition 
                                    ( object reflexive ) ) ) 
                            ( predicate 
                                ( registration register ( symbol ( type amount ) ) 
                                    ( expression ( combination ( combinor ( combinor ( combinor ( combinand 
                                                            ( scalar-comparison 
                                                                ( scalar-expression ( symbol ( type amount ) ) ) 
                                                                ( comparison-operator later ) 
                                                                ( scalar-expression ( symbol ( type text ) ) ) ) ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression 123 ) 
                                                                            ( time-unit minutes ) ) 
                                                                        ( symbol «garply-plugh-bar» ) ) ) ) 
                                                            ( comparison-operator later ) 
                                                            ( scalar-expression 123 ) ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinand 
                                                    ( point-in-time 
                                                        ( relative-time 
                                                            ( duration 
                                                                ( scalar-expression 123 ) 
                                                                ( time-unit minutes ) ) 
                                                            ( symbol ( type data ) ) ) ) ) 
                                                ( combinator nor ) ) ) ) ) ) 
                            ( predicate 
                                ( declaration declare ( symbol ( type data ) ) 
                                    ( contract 
                                        ( this-contract «fred» ) ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol «garply-plugh-bar» ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol ( type text ) ) 
                                    ( contract 
                                        ( this-contract «fred» ) ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combinor ( combinor ( combinand ( symbol ( type person ) ) 
                                                        expiration ) ) 
                                                ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression 
                                                            ( point-in-time current-time ) ) 
                                                        ( comparison-operator equal ) 
                                                        ( scalar-expression 123 ) ) ) 
                                                ( combinator nor ) ) ) ) 
                                    preposition 
                                    ( object ( symbol ( type person ) ) ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol «garply-plugh-bar» ) ) ) 
                            ( predicate 
                                ( termination terminate 
                                    ( this-contract «fred» ) ) ) 
                            ( predicate 
                                ( filing file ( symbol ( type binary ) ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( filing file ( symbol «garply-plugh-bar» ) ) ) ) 
                        permission 
                        ( condition if 
                            ( expression ( combination ( combination ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                            ( existence ( symbol «garply-plugh-bar» ) 
                                                                                being true ) ) ) 
                                                                    ( combinand 
                                                                        ( negation 
                                                                            ( negator ) 
                                                                            ( symbol ( type amount ) ) 
                                                                            fixed ) ) 
                                                                    ( combinator neither ) ) 
                                                                ( combinand 
                                                                    ( point-in-time current-time ) ) 
                                                                ( combinator nor ) ) 
                                                            ( combinand 
                                                                ( negation 
                                                                    ( negator be ) 
                                                                    ( symbol ( type person ) ) 
                                                                    ( contract 
                                                                        ( this-contract «fred» ) ) ) ) 
                                                            ( combinator neither ) ) ) 
                                                    ( combinor ( combinor ( combinor ( combinand 
                                                                    ( point-in-time 
                                                                        ( relative-time 
                                                                            ( duration 
                                                                                ( scalar-expression ( symbol ( type amount ) ) ) 
                                                                                ( time-unit minutes ) ) 
                                                                            ( symbol «garply-plugh-bar» ) ) ) ) ) 
                                                            ( combinand 
                                                                ( negation 
                                                                    ( negator ) 
                                                                    ( symbol «garply-plugh-bar» ) ) ) 
                                                            ( combinator neither ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol ( type time ) ) 
                                                                be 
                                                                ( contract 
                                                                    ( this-contract «fred» ) ) ) ) 
                                                        ( combinator and ) ) ) 
                                                ( combinor ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression ( symbol «garply-plugh-bar» ) ) 
                                                            ( comparison-operator equal ) 
                                                            ( scalar-expression ( symbol ( type amount ) ) ) ) ) ) 
                                                ( combinator and ) ) 
                                            ( combinor ( combinor ( combinor ( combinand ( symbol ( type amount ) ) ) ) 
                                                    ( combinand 
                                                        ( point-in-time current-time ) ) 
                                                    ( combinator or- ) ) 
                                                ( combinand 
                                                    ( existence ( symbol «garply-plugh-bar» ) 
                                                        be 
                                                        ( contract 
                                                            ( this-contract «fred» ) ) ) ) 
                                                ( combinator neither ) ) ) 
                                        ( combinor ( combinor ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression ( symbol «garply-plugh-bar» ) ) 
                                                        ( comparison-operator equal ) 
                                                        ( scalar-expression 
                                                            ( point-in-time current-time ) ) ) ) ) 
                                            ( combinand 
                                                ( point-in-time 
                                                    ( relative-time 
                                                        ( duration 
                                                            ( scalar-expression 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression ( symbol ( type amount ) ) ) 
                                                                            ( time-unit hours ) ) 
                                                                        ( symbol ( type binary ) ) ) ) ) 
                                                            ( time-unit years ) ) 
                                                        ( symbol ( type text ) ) ) ) ) 
                                            ( combinator neither ) ) 
                                        ( combinator neither ) ) 
                                    ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol «garply-plugh-bar» ) 
                                                                expiration ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol «garply-plugh-bar» ) 
                                                                be 
                                                                ( contract all-contracts ) ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinand ( symbol «garply-plugh-bar» ) ) 
                                                    ( combinator and ) ) 
                                                ( combinand 
                                                    ( existence ( symbol «garply-plugh-bar» ) 
                                                        be ) ) 
                                                ( combinator and ) ) 
                                            ( combinand 
                                                ( point-in-time 
                                                    ( relative-time 
                                                        ( duration 
                                                            ( scalar-expression 123 ) 
                                                            ( time-unit years ) ) ) ) ) 
                                            ( combinator or- ) ) 
                                        ( combinand expiration ) 
                                        ( combinator and ) ) ) ) ) ) ) ) ) ) 
    ( covenants 
        ( covenant «garply-plugh-bar» 
            ( provisions 
                ( definitions 
                    ( definition «garply-plugh-bar» 
                        ( this-contract «fred» ) ) 
                    ( definition «garply-plugh-bar» 
                        ( this-contract «fred» ) ) 
                    ( definition «garply-plugh-bar» ( type amount ) ) ) ) ) ) )
