( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «bar» ( type time ) ) ) 
            ( statements 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols 
                                ( symbols ( symbol ( type time ) ) ) 
                                ( symbol «bar» ) 
                                catena ) ) 
                        ( predicates 
                            ( predicate 
                                ( setting be ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( certification certify ( symbol «bar» ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object reflexive ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                            ( point-in-time current-time ) ) ) 
                                                                    ( combinand ( symbol «bar» ) ) 
                                                                    ( combinator or- ) ) 
                                                                ( combinand expiration ) 
                                                                ( combinator and ) ) 
                                                            ( combinand 
                                                                ( point-in-time current-time ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand ( symbol «bar» ) 
                                                            expiration ) 
                                                        ( combinator nor ) ) ) 
                                                ( combinor ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression 123 ) 
                                                            ( comparison-operator equal ) 
                                                            ( scalar-expression 123 ) ) ) ) ) 
                                            ( combinor ( combinand ( symbol ( type amount ) ) ) ) 
                                            ( combinator or- ) ) ) ) ) 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combinor ( combinand ( symbol «bar» ) 
                                                    expiration ) ) ) ) 
                                    preposition 
                                    ( object reflexive ) 
                                    from-escrow ) ) 
                            ( predicate 
                                ( filing file ( symbol «bar» ) 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinand 
                                                                                ( existence ( symbol ( type text ) ) 
                                                                                    be ) ) ) 
                                                                        ( combinand ( symbol ( type person ) ) ) 
                                                                        ( combinator and ) ) ) 
                                                                ( combinor ( combinor ( combinor ( combinand ( symbol «bar» ) ) ) 
                                                                        ( combinand expiration ) 
                                                                        ( combinator nor ) ) 
                                                                    ( combinand ( symbol ( type person ) ) ) 
                                                                    ( combinator nor ) ) 
                                                                ( combinator or- ) ) 
                                                            ( combinor ( combinor ( combinand ( symbol ( type time ) ) 
                                                                        expiration ) ) 
                                                                ( combinand expiration ) 
                                                                ( combinator neither ) ) ) 
                                                        ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                                ( combinand 
                                                                    ( existence ( symbol «bar» ) 
                                                                        be ) ) 
                                                                ( combinator and ) ) 
                                                            ( combinand 
                                                                ( existence ( symbol «bar» ) 
                                                                    equal fixed ) ) 
                                                            ( combinator and ) ) ) 
                                                    ( combinor ( combinand expiration ) ) ) 
                                                ( combinor ( combinor ( combinor ( combinand 
                                                                ( negation 
                                                                    ( negator be ) 
                                                                    ( symbol ( type text ) ) 
                                                                    ( contract 
                                                                        ( this-contract «bar» ) ) ) ) ) 
                                                        ( combinand ( symbol ( type amount ) ) 
                                                            expiration ) 
                                                        ( combinator neither ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression 123 ) 
                                                            ( comparison-operator equal ) 
                                                            ( scalar-expression 123 ) ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinator nor ) ) 
                                            ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                    ( point-in-time current-time ) ) ) 
                                                            ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression 123 ) 
                                                                    ( comparison-operator equal ) 
                                                                    ( scalar-expression 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression ( symbol ( type amount ) ) ) 
                                                                                    ( time-unit weeks ) ) ) ) ) ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinand 
                                                            ( point-in-time 
                                                                ( relative-time 
                                                                    ( duration 
                                                                        ( scalar-expression 123 ) 
                                                                        ( time-unit days ) ) 
                                                                    ( symbol «bar» ) ) ) ) 
                                                        ( combinator and ) ) 
                                                    ( combinand ( symbol ( type amount ) ) 
                                                        expiration ) 
                                                    ( combinator and ) ) 
                                                ( combinand ( symbol «bar» ) ) 
                                                ( combinator and ) ) 
                                            ( combinator and ) ) ) ) ) 
                            ( predicate 
                                ( filing file ( symbol «bar» ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combination ( combinor ( combinor ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression 123 ) 
                                                                    ( comparison-operator equal ) 
                                                                    ( scalar-expression 123 ) ) ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol ( type binary ) ) 
                                                                being true ) ) 
                                                        ( combinator nor ) ) ) 
                                                ( combinor ( combinand 
                                                        ( point-in-time 
                                                            ( relative-time 
                                                                ( duration 
                                                                    ( scalar-expression 123 ) 
                                                                    ( time-unit weeks ) ) 
                                                                ( symbol ( type person ) ) ) ) ) ) 
                                                ( combinator or- ) ) 
                                            ( combinor ( combinand 
                                                    ( negation 
                                                        ( negator be ) 
                                                        ( symbol «bar» ) 
                                                        ( contract all-contracts ) ) ) ) 
                                            ( combinator or- ) ) ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combinor ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression ( symbol «bar» ) ) 
                                                                        ( comparison-operator equal ) 
                                                                        ( scalar-expression 123 ) ) ) ) ) 
                                                        ( combinor ( combinand ( symbol ( type binary ) ) ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinor ( combinor ( combinand ( symbol ( type data ) ) ) ) 
                                                        ( combinand ( symbol ( type time ) ) 
                                                            expiration ) 
                                                        ( combinator nor ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinor ( combinor ( combinor ( combinand ( symbol «bar» ) ) ) 
                                                        ( combinand 
                                                            ( negation 
                                                                ( negator be ) 
                                                                ( symbol «bar» ) ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand 
                                                        ( existence ( symbol ( type binary ) ) 
                                                            being true ) ) 
                                                    ( combinator and ) ) ) 
                                            ( combinor ( combinand expiration ) ) 
                                            ( combinator or- ) ) ) 
                                    preposition 
                                    ( object ( symbol «bar» ) ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( certification certify ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( registration register ( symbol ( type time ) ) ) ) 
                            ( predicate 
                                ( setting be ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type amount ) ) ) ) 
                            ( predicate 
                                ( termination terminate 
                                    ( this-contract «bar» ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol ( type text ) ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol ( type amount ) ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object reflexive ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combinor ( combinor ( combinand expiration ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression 123 ) 
                                                                            ( time-unit days ) ) 
                                                                        ( symbol «bar» ) ) ) ) 
                                                            ( comparison-operator later ) 
                                                            ( scalar-expression 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression 
                                                                                ( point-in-time 
                                                                                    ( relative-time 
                                                                                        ( duration 
                                                                                            ( scalar-expression ( symbol «bar» ) ) 
                                                                                            ( time-unit years ) ) 
                                                                                        ( symbol ( type amount ) ) ) ) ) 
                                                                            ( time-unit days ) ) 
                                                                        ( symbol «bar» ) ) ) ) ) ) 
                                                    ( combinator and ) ) ) 
                                            ( combinor ( combinor ( combinand 
                                                        ( existence ( symbol «bar» ) 
                                                            being true ) ) ) 
                                                ( combinand 
                                                    ( point-in-time current-time ) ) 
                                                ( combinator neither ) ) ) ) ) ) 
                            ( predicate 
                                ( setting be ( symbol ( type amount ) ) ) ) 
                            ( predicate 
                                ( notification notify 
                                    ( object reflexive ) 
                                    preposition 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combinor ( combinand 
                                                                    ( point-in-time current-time ) ) ) ) 
                                                        ( combinor ( combinor ( combinand 
                                                                    ( existence ( symbol ( type person ) ) 
                                                                        be ) ) ) 
                                                            ( combinand 
                                                                ( existence ( symbol «bar» ) 
                                                                    equal fixed ) ) 
                                                            ( combinator and ) ) ) 
                                                    ( combinor ( combinor ( combinand 
                                                                ( existence ( symbol ( type amount ) ) 
                                                                    being true ) ) ) 
                                                        ( combinand 
                                                            ( scalar-comparison 
                                                                ( scalar-expression 
                                                                    ( point-in-time 
                                                                        ( relative-time 
                                                                            ( duration 
                                                                                ( scalar-expression 123 ) 
                                                                                ( time-unit seconds ) ) ) ) ) 
                                                                ( comparison-operator equal ) 
                                                                ( scalar-expression 
                                                                    ( point-in-time current-time ) ) ) ) 
                                                        ( combinator or- ) ) ) 
                                                ( combinor ( combinand ( symbol ( type data ) ) ) ) 
                                                ( combinator and ) ) 
                                            ( combinor ( combinand ( symbol ( type text ) ) ) ) ) ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol ( type person ) ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( sending send 
                                    ( expression ( combination ( combination ( combinor ( combinor ( combinand ( symbol ( type amount ) ) ) ) 
                                                    ( combinand ( symbol «bar» ) 
                                                        expiration ) 
                                                    ( combinator nor ) ) ) 
                                            ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                    ( point-in-time current-time ) ) ) 
                                                            ( combinand expiration ) 
                                                            ( combinator or- ) ) 
                                                        ( combinand 
                                                            ( point-in-time current-time ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand ( symbol «bar» ) ) 
                                                    ( combinator neither ) ) 
                                                ( combinand 
                                                    ( existence ( symbol ( type person ) ) 
                                                        being true ) ) 
                                                ( combinator nor ) ) 
                                            ( combinator and ) ) ) 
                                    preposition 
                                    ( object ( symbol ( type data ) ) ) ) ) 
                            ( predicate 
                                ( termination terminate 
                                    ( this-contract «bar» ) ) ) 
                            ( predicate 
                                ( filing file ( symbol «bar» ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( certification certify ( symbol «bar» ) 
                                    ( expression ( combination ( combination ( combinor ( combinor ( combinor ( combinand ( symbol «bar» ) 
                                                                expiration ) ) 
                                                        ( combinand ( symbol «bar» ) 
                                                            expiration ) 
                                                        ( combinator neither ) ) 
                                                    ( combinand ( symbol ( type binary ) ) 
                                                        expiration ) 
                                                    ( combinator neither ) ) ) 
                                            ( combinor ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression 
                                                            ( point-in-time 
                                                                ( relative-time 
                                                                    ( duration 
                                                                        ( scalar-expression 
                                                                            ( point-in-time current-time ) ) 
                                                                        ( time-unit months ) ) 
                                                                    ( symbol ( type person ) ) ) ) ) 
                                                        ( comparison-operator equal ) 
                                                        ( scalar-expression 
                                                            ( point-in-time current-time ) ) ) ) ) 
                                            ( combinator nor ) ) ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( declaration declare ( symbol «bar» ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol «bar» ) 
                                    ( contract all-contracts ) ) ) ) 
                        permission 
                        ( condition if 
                            ( expression ( combination ( combinor ( combinor ( combinand 
                                                ( existence ( symbol «bar» ) 
                                                    be 
                                                    ( contract 
                                                        ( this-contract «bar» ) ) ) ) ) 
                                        ( combinand expiration ) 
                                        ( combinator nor ) ) ) ) ) ) ) ) ) ) 
    ( covenants 
        ( covenant «fred» 
            ( provisions 
                ( definitions 
                    ( definition «fred» ( type data ) ) ) ) ) ) )
