	%token A
	%token Appoint
	%token AppointS
	%token Appointed
	%token Appointment_Predicament
	%token Appointment_Predicate
	%token As
	%token Be
	%token From
	%token Is
	%token New
	%token Now
	%token On
	%token Party
	%token Somebody
	%token To
	
	Appointment_Predicate:	
		  Appoint Somebody Party                          { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoint Somebody As Party                       { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoint Somebody To Party                       { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoint Somebody To Be Party                    { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoint Somebody To From Now On Party           { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoint Somebody To From Now On Be Party        { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Appoint Somebody As A New Party                 { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| AppointS Somebody Party                         { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| AppointS Somebody As Party                      { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| AppointS Somebody To Party                      { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| AppointS Somebody To Be Party                   { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| AppointS Somebody To From Now On Party          { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| AppointS Somebody To From Now On Be Party       { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
		| AppointS Somebody As A New Party                { NEW(Appointment, *((Literal **)&yylval)); Appointment->Somebody=$Somebody; Appointment->Party=$Party; root=process_appointment(Appointment); }
	
	Appointment_Predicament:	
		  Is Appointed Party                              { NEW(Appointment, *((Literal **)&yylval)); Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Is Appointed As Party                           { NEW(Appointment, *((Literal **)&yylval)); Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Is Appointed To Party                           { NEW(Appointment, *((Literal **)&yylval)); Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Is Appointed To Be Party                        { NEW(Appointment, *((Literal **)&yylval)); Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Is Appointed To From Now On Party               { NEW(Appointment, *((Literal **)&yylval)); Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Is Appointed To From Now On Be Party            { NEW(Appointment, *((Literal **)&yylval)); Appointment->Party=$Party; root=process_appointment(Appointment); }
		| Is Appointed As A New Party                     { NEW(Appointment, *((Literal **)&yylval)); Appointment->Party=$Party; root=process_appointment(Appointment); }
