	
	Document:	
		  Head
		;


	
	Head:	
		  Lex
		| Lex Recital
		| Lex Preamble
		| Lex Preamble Recital
		| Lex Authors
		| Lex Authors Recital
		| Lex Authors Preamble
		| Lex Authors Preamble Recital
		| Lex Lexon
		| Lex Lexon Recital
		| Lex Lexon Preamble
		| Lex Lexon Preamble Recital
		| Lex Lexon Authors
		| Lex Lexon Authors Recital
		| Lex Lexon Authors Preamble
		| Lex Lexon Authors Preamble Recital
		;


	
	Lex:	
		  LEX Name Separator
		| LEX Colon Name Separator
		;


	
	Lexon:	
		  LEXON Text Separator
		| LEXON Colon Text Separator
		;


	
	Authors:	
		  AUTHOR Text Separator
		| AUTHOR Colon Text Separator
		| AUTHORS Text Separator
		| AUTHORS Colon Text Separator
		;


	
	Preamble:	
		  PREAMBLE Colon Text Separator
		;


	
	Recital:	
		  Text
		;


	Name: NAME						{ $$=$NAME; }
	    ;

	Description: DESCRIPTION						{ $$=$DESCRIPTION; }
	    ;

	Scalar: SCALAR						{ $$=$SCALAR; }
	    ;

