
precompilation:
---------------

test law 04   1:   LEX: «Paid Escrow».
test law 04   2:   LEXON: ‹0.3.xx›.
test law 04   3:   COMMENT: ‹%PRE %GEN %JUR an escrow that is controlled by a third party for a fee.›.

library 1     1:   CLAUSE: «Deadline Past».
library 1     2:   "«Deadline Past»" is defined as a given Time being earlier than Today.

test law 04   7:   LAW: New York
test law 04   8:   “«Paying Party»” is a person.
test law 04   9:   “«Paid Party»” is a person.
test law 04  10:   “«Pay Master»” is a person.
test law 04  11:   “«Payment»” is an amount.
test law 04  12:   “«Payment Fee»” is an amount.
test law 04  13:   “«Non-Payment Fee»” is an amount.
test law 04  14:   “«Master's Fee»” is an amount.

test law 04  16:   The «Paying Party» pays a «Payment» into escrow,
test law 04  17:   appoints the «Paid Party»,
test law 04  18:   appoints the «Pay Master»,
test law 04  19:   and also fixes the «Master's Fee».

test law 04  21:   CLAUSE: «Make Payment».
test law 04  22:   The «Pay Master» may pay from escrow the «Master's Fee» to themselves,
test law 04  24:   and afterwards pay the remainder of the escrow to the «Paid Party».

test law 04  26:   CLAUSE: «Return Payment».
test law 04  27:   The «Pay Master» may pay from escrow the «Non-Payment Fee» to themselves,
test law 04  29:   and afterwards return the remainder of the escrow to the «Paying Party».


