
precompilation:
---------------

test include 12   1:   LEX: «Paid Escrow».
test include 12   2:   LEXON: ‹0.3.xx›.
test include 12   3:   COMMENT: ‹%PRE %GEN an escrow that is controlled by a third party for a fee.›.

library 1         1:   CLAUSE: «Deadline Past».
library 1         2:   "«Deadline Past»" is defined as a given Time being earlier than Today.

test include 12   7:   “«Paying Party»” is a person.
test include 12   8:   “«Paid Party»” is a person.
test include 12   9:   “«Pay Master»” is a person.
test include 12  10:   “«Payment»” is an amount.
test include 12  11:   “«Payment Fee»” is an amount.
test include 12  12:   “«Non-Payment Fee»” is an amount.
test include 12  13:   “«Master's Fee»” is an amount.

test include 12  15:   The «Paying Party» pays a «Payment» into escrow,
test include 12  16:   appoints the «Paid Party»,
test include 12  17:   appoints the «Pay Master»,
test include 12  18:   and also fixes the «Master's Fee».

test include 12  20:   CLAUSE: «Make Payment».
test include 12  21:   The «Pay Master» may pay from escrow the «Master's Fee» to themselves,
test include 12  23:   and afterwards pay the remainder of the escrow to the «Paid Party».

test include 12  25:   CLAUSE: «Return Payment».
test include 12  26:   The «Pay Master» may pay from escrow the «Non-Payment Fee» to themselves,
test include 12  28:   and afterwards return the remainder of the escrow to the «Paying Party».

