( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «bar» 
                    ( this-contract «bar» ) ) ) 
            ( statements 
                ( statement 
                    ( action 
                        ( subject 
                            ( symbols ( symbol «bar» ) ) ) 
                        ( predicates 
                            ( predicate 
                                ( filing file ( symbol ( type text ) ) ) ) 
                            ( predicate 
                                ( registration register ( symbol ( type amount ) ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol ( type binary ) ) 
                                    ( expression ( combination ( combination ( combination ( combination ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinand ( symbol «bar» ) ) ) 
                                                                            ( combinand 
                                                                                ( negation 
                                                                                    ( negator ) 
                                                                                    ( symbol «bar» ) ) ) 
                                                                            ( combinator nor ) ) ) 
                                                                    ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                                            ( point-in-time 
                                                                                                ( relative-time 
                                                                                                    ( duration 
                                                                                                        ( scalar-expression 
                                                                                                            ( point-in-time 
                                                                                                                ( relative-time 
                                                                                                                    ( duration 
                                                                                                                        ( scalar-expression ( symbol ( type amount ) ) ) 
                                                                                                                        ( time-unit months ) ) ) ) ) 
                                                                                                        ( time-unit days ) ) 
                                                                                                    ( symbol ( type binary ) ) ) ) ) ) 
                                                                                    ( combinand 
                                                                                        ( scalar-comparison 
                                                                                            ( scalar-expression 
                                                                                                ( point-in-time 
                                                                                                    ( relative-time 
                                                                                                        ( duration 
                                                                                                            ( scalar-expression ( symbol «bar» ) ) 
                                                                                                            ( time-unit months ) ) ) ) ) 
                                                                                            ( comparison-operator equal ) 
                                                                                            ( scalar-expression 123 ) ) ) 
                                                                                    ( combinator or- ) ) 
                                                                                ( combinand ( symbol ( type person ) ) 
                                                                                    expiration ) 
                                                                                ( combinator nor ) ) 
                                                                            ( combinand 
                                                                                ( point-in-time current-time ) ) 
                                                                            ( combinator and ) ) 
                                                                        ( combinand ( symbol ( type amount ) ) 
                                                                            expiration ) 
                                                                        ( combinator and ) ) 
                                                                    ( combinator or- ) ) 
                                                                ( combinor ( combinand ( symbol «bar» ) ) ) ) 
                                                            ( combinor ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression 123 ) 
                                                                        ( comparison-operator equal ) 
                                                                        ( scalar-expression 123 ) ) ) ) ) 
                                                        ( combinor ( combinor ( combinand 
                                                                    ( existence ( symbol «bar» ) 
                                                                        being true ) ) ) 
                                                            ( combinand ( symbol «bar» ) ) 
                                                            ( combinator nor ) ) 
                                                        ( combinator or- ) ) 
                                                    ( combinor ( combinor ( combinand ( symbol «bar» ) ) ) 
                                                        ( combinand ( symbol «bar» ) ) 
                                                        ( combinator neither ) ) 
                                                    ( combinator nor ) ) 
                                                ( combinor ( combinand 
                                                        ( existence ( symbol ( type data ) ) 
                                                            be 
                                                            ( contract 
                                                                ( this-contract «bar» ) ) ) ) ) ) 
                                            ( combinor ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression ( symbol ( type time ) ) ) 
                                                        ( comparison-operator later ) 
                                                        ( scalar-expression 
                                                            ( point-in-time current-time ) ) ) ) ) 
                                            ( combinator nor ) ) ) ) ) 
                            ( predicate 
                                ( termination terminate 
                                    ( this-contract «bar» ) ) ) 
                            ( predicate 
                                ( grantment grant ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( certification certify ( symbol ( type person ) ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( registration register ( symbol ( type amount ) ) 
                                    ( contract all-contracts ) ) ) 
                            ( predicate 
                                ( fixture fix ( symbol ( type amount ) ) 
                                    ( contract 
                                        ( this-contract «bar» ) ) ) ) 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combination ( combinor ( combinor ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol ( type person ) ) ) ) 
                                                                    ( combinand ( symbol ( type binary ) ) ) 
                                                                    ( combinator or- ) ) 
                                                                ( combinand 
                                                                    ( scalar-comparison 
                                                                        ( scalar-expression ( symbol «bar» ) ) 
                                                                        ( comparison-operator equal ) 
                                                                        ( scalar-expression 
                                                                            ( point-in-time 
                                                                                ( relative-time 
                                                                                    ( duration 
                                                                                        ( scalar-expression 
                                                                                            ( point-in-time 
                                                                                                ( relative-time 
                                                                                                    ( duration 
                                                                                                        ( scalar-expression ( symbol ( type text ) ) ) 
                                                                                                        ( time-unit minutes ) ) 
                                                                                                    ( symbol «bar» ) ) ) ) 
                                                                                        ( time-unit days ) ) 
                                                                                    ( symbol ( type text ) ) ) ) ) ) ) 
                                                                ( combinator or- ) ) 
                                                            ( combinand 
                                                                ( scalar-comparison 
                                                                    ( scalar-expression 
                                                                        ( point-in-time 
                                                                            ( relative-time 
                                                                                ( duration 
                                                                                    ( scalar-expression ( symbol «bar» ) ) 
                                                                                    ( time-unit milliseconds ) ) ) ) ) 
                                                                    ( comparison-operator equal ) 
                                                                    ( scalar-expression 
                                                                        ( point-in-time current-time ) ) ) ) 
                                                            ( combinator and ) ) 
                                                        ( combinand expiration ) 
                                                        ( combinator and ) ) 
                                                    ( combinand 
                                                        ( scalar-comparison 
                                                            ( scalar-expression 123 ) 
                                                            ( comparison-operator equal ) 
                                                            ( scalar-expression 
                                                                ( point-in-time current-time ) ) ) ) 
                                                    ( combinator and ) ) ) 
                                            ( combinor ( combinor ( combinand expiration ) ) 
                                                ( combinand 
                                                    ( existence ( symbol «bar» ) 
                                                        equal fixed ) ) 
                                                ( combinator and ) ) 
                                            ( combinator neither ) ) ) 
                                    preposition 
                                    ( object ) ) ) 
                            ( predicate 
                                ( registration register ( symbol ( type data ) ) 
                                    ( expression ( combination ( combination ( combinor ( combinor ( combinand 
                                                            ( negation 
                                                                ( negator be ) 
                                                                ( symbol ( type person ) ) ) ) ) 
                                                    ( combinand 
                                                        ( existence ( symbol ( type amount ) ) 
                                                            be ) ) 
                                                    ( combinator nor ) ) ) 
                                            ( combinor ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression 123 ) 
                                                        ( comparison-operator later ) 
                                                        ( scalar-expression 
                                                            ( point-in-time 
                                                                ( relative-time 
                                                                    ( duration 
                                                                        ( scalar-expression 123 ) 
                                                                        ( time-unit minutes ) ) 
                                                                    ( symbol ( type time ) ) ) ) ) ) ) ) ) ) ) ) 
                            ( predicate 
                                ( certification certify ( symbol ( type binary ) ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol «bar» ) ) ) 
                            ( predicate 
                                ( setting 
                                    ( illocutor be ) 
                                    ( symbol ( type data ) ) ) ) 
                            ( predicate 
                                ( payment pay 
                                    ( expression ( combination ( combination ( combination ( combination ( combinor ( combinor ( combinor ( combinand 
                                                                        ( existence ( symbol ( type binary ) ) 
                                                                            equal fixed ) ) ) 
                                                                ( combinand ( symbol «bar» ) 
                                                                    expiration ) 
                                                                ( combinator or- ) ) 
                                                            ( combinand 
                                                                ( existence ( symbol ( type person ) ) 
                                                                    be ) ) 
                                                            ( combinator or- ) ) ) 
                                                    ( combinor ( combinor ( combinor ( combinor ( combinand 
                                                                        ( scalar-comparison 
                                                                            ( scalar-expression 123 ) 
                                                                            ( comparison-operator equal ) 
                                                                            ( scalar-expression ( symbol ( type amount ) ) ) ) ) ) 
                                                                ( combinand 
                                                                    ( existence ( symbol ( type data ) ) 
                                                                        being true ) ) 
                                                                ( combinator nor ) ) 
                                                            ( combinand expiration ) 
                                                            ( combinator or- ) ) 
                                                        ( combinand ( symbol ( type data ) ) ) 
                                                        ( combinator neither ) ) ) 
                                                ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol ( type time ) ) 
                                                                be ) ) 
                                                        ( combinator and ) ) 
                                                    ( combinand ( symbol «bar» ) ) 
                                                    ( combinator nor ) ) 
                                                ( combinator or- ) ) 
                                            ( combinor ( combinor ( combinor ( combinor ( combinand expiration ) ) 
                                                        ( combinand 
                                                            ( existence ( symbol «bar» ) 
                                                                equal fixed ) ) 
                                                        ( combinator nor ) ) 
                                                    ( combinand expiration ) 
                                                    ( combinator nor ) ) 
                                                ( combinand 
                                                    ( negation 
                                                        ( negator ) 
                                                        ( symbol ( type amount ) ) 
                                                        fixed ) ) 
                                                ( combinator or- ) ) ) ) 
                                    preposition 
                                    ( object reflexive ) ) ) 
                            ( predicate 
                                ( appointment appoint ( symbol «bar» ) ) ) ) 
                        permission 
                        ( condition if 
                            ( expression ( combination ( combinor ( combinor ( combinor ( combinor ( combinand ( symbol ( type time ) ) ) ) 
                                                ( combinand 
                                                    ( scalar-comparison 
                                                        ( scalar-expression 123 ) 
                                                        ( comparison-operator later ) 
                                                        ( scalar-expression ( symbol ( type time ) ) ) ) ) 
                                                ( combinator or- ) ) 
                                            ( combinand 
                                                ( point-in-time 
                                                    ( relative-time 
                                                        ( duration 
                                                            ( scalar-expression 
                                                                ( point-in-time 
                                                                    ( relative-time 
                                                                        ( duration 
                                                                            ( scalar-expression ( symbol ( type binary ) ) ) 
                                                                            ( time-unit minutes ) ) 
                                                                        ( symbol ( type time ) ) ) ) ) 
                                                            ( time-unit days ) ) 
                                                        ( symbol «bar» ) ) ) ) 
                                            ( combinator neither ) ) 
                                        ( combinand 
                                            ( scalar-comparison 
                                                ( scalar-expression ( symbol ( type amount ) ) ) 
                                                ( comparison-operator later ) 
                                                ( scalar-expression ( symbol ( type time ) ) ) ) ) 
                                        ( combinator and ) ) ) ) ) ) ) 
                ( statement 
                    ( flagging 
                        ( illocutor be ) 
                        ( symbol ( type text ) ) 
                        ( this-contract «bar» ) ) ) ) ) ) 
    ( covenants 
        ( covenant «grault-grault» 
            ( provisions 
                ( definitions 
                    ( definition «grault-grault» 
                        ( this-contract «bar» ) ) ) 
                ( clauses 
                    ( clause «garply» 
                        ( body 
                            ( statements 
                                ( statement 
                                    ( flagging 
                                        ( illocutor be ) 
                                        ( symbol ( type binary ) ) 
                                        ( this-contract «bar» ) ) ) 
                                ( statement 
                                    ( flagging 
                                        ( illocutor be ) 
                                        ( symbol ( type time ) ) ) ) ) ) ) ) 
                ( statements 
                    ( statement 
                        ( flagging 
                            ( illocutor be ) 
                            ( symbol «grault-grault» ) ) ) ) ) ) ) )
