( document 
    ( head 
        ( lex «bar» ) 
        ( preamble "Aenean commodo.") ) 
    ( terms 
        ( provisions 
            ( definitions 
                ( definition «bar» ( type data ) ) ) 
            ( statements 
                ( statement 
                    ( flagging 
                        ( illocutor be ) 
                        ( symbol ( type binary ) ) 
                        ( this-contract «bar» ) ) ) 
                ( statement 
                    ( flagging 
                        ( illocutor be ) 
                        ( symbol «bar» ) ) ) ) ) ) 
    ( covenants 
        ( covenant «xyzzy» 
            ( provisions 
                ( definitions 
                    ( definition «xyzzy» 
                        ( this-contract «bar» ) ) ) 
                ( statements 
                    ( statement 
                        ( flagging 
                            ( illocutor be ) 
                            ( symbol «xyzzy» ) 
                            ( this-contract «bar» ) ) ) ) ) ) ) )
