
precompilation:
---------------

veto b2 auto bind subject   1:   LEX: «Veto»

veto b2 auto bind subject   3:   "«Payer»" is a person.
veto b2 auto bind subject   4:   "«Receiver»" is a person.
veto b2 auto bind subject   5:   "«Officiator»" is a person.
veto b2 auto bind subject   6:   "«Time»" is a time.

veto b2 auto bind subject   8:   The «Payer» pays an amount into escrow, appoints the «Receiver», and fixes a «Time».

veto b2 auto bind subject  10:   CLAUSE: «Draw».
veto b2 auto bind subject  11:   The «Receiver» may, if the «Time» has passed, repay the escrow to themselves.

veto b2 auto bind subject  13:   CLAUSE: «Veto».
veto b2 auto bind subject  14:   The «Officiator» may repay the escrow to the «Payer».


