
precompilation:
---------------

veto   1:   LEX: «Timed Veto»

veto   3:   "«Payer»" is a person.
veto   4:   "«Receiver»" is a person.
veto   5:   "«Officiator»" is a person.
veto   6:   "«Time»" is a time.

veto   8:   The «Payer» pays an amount into escrow, appoints the «Receiver», appoints the «Officiator», and fixes a «Time».

veto  10:   CLAUSE: «Draw».
veto  11:   The «Receiver» may, if the «Time» has passed, pay the escrow to themselves.

veto  13:   CLAUSE: «Veto».
veto  14:   The «Officiator» may return the escrow to the «Payer».


