all one clean expclean deeptest comptest compmiss update autoupdate autocomp recheck _recheck _test new expectations compall _expects grammar_expectations grammar_expects focustest focusprep focuscomp testlog list_expectations list_sources:
	@echo "For a full source installation including test files git clone https://github.com/lexonian/lexon.git"

.PHONY: all one clean expclean deeptest comptest compmiss update autoupdate autocomp recheck _recheck _test new expectations compall _expects grammar_expectations grammar_expects focustest focusprep focuscomp testlog list_expectations list_sources 
