/** Lexon-generated Sophia code
 **
 **	code:        UCC Financing Statement
 **
 **	file:        statement.lex
 **
 **	code tagged: 0.2.12
 **
 **	compiler:    lexon 0.3 alpha 97 U
 **
 **	grammar:     0.2.20 / subset 0.3.8.2 alpha 97 - English / Reyes
 **
 **	backend:     sophia 0.3.97 U
 **
 **	target:      sophia 7.1+
 **
 **	options:     --sophia  --comment 
 **
 */

@compiler >=6

/**
 **
 **	Main UCC Financing Statement contract system
 **
 **/

/*
 | 	LEX UCC Financing Statement.
 | 
 | 	LEXON: 0.2.12
 | 
 | 	"Financing Statement" is this contract. 
 | 	"File Number" is data.
 | 	"Initial Statement Date" is a time.
 | 	"Filer" is a person. 
 | 	"Debtor" is a person.
 | 	"Secured Party" is a person.
 | 	"Filing Office" is a person.
 | 	"Collateral" is data.
 | 	"Digital Asset Collateral" is an amount.
 | 	"Reminder Fee" is an amount.
 | 	"Continuation Window Start" is a time.
 | 	"Continuation Statement Date" is a time.
 | 	"Continuation Statement Filing Number" is data.
 | 	"Lapse Date" is a time.
 | 	"Default" is a binary.
 | 	"Continuation Statement" is a binary.
 | 	"Termination Statement" is a binary.
 | 	"Termination Statement Time" is a time.
 | 	"Notification Statement" is a text. 
 | 
 | 	The Filer fixes the Filing Office, fixes the Debtor, fixes the Secured Party, and fixes the Collateral.
 */



main contract UCCFinancingStatement =

    record state = {
            file_number : string,
            initial_statement_date : int,
            filer : address,
            debtor : address,
            secured_party : address,
            filing_office : address,
            collateral : string,
            digital_asset_collateral : int,
            reminder_fee : int,
            continuation_window_start : int,
            continuation_statement_date : int,
            continuation_statement_filing_number : string,
            lapse_date : int,
            _default : bool,
            continuation_statement : bool,
            termination_statement : bool,
            termination_statement_time : int,
            notification_statement : string,
            terminated : bool
        }

    datatype event = Message(indexed address, indexed address, string)

    entrypoint init(filing_office : address, debtor : address, secured_party : address, collateral : string) = {
            file_number = "",
            initial_statement_date = 0,
            filer = Call.caller,
            debtor = debtor,
            secured_party = secured_party,
            filing_office = filing_office,
            collateral = collateral,
            digital_asset_collateral = 0,
            reminder_fee = 0,
            continuation_window_start = 0,
            continuation_statement_date = 0,
            continuation_statement_filing_number = "",
            lapse_date = 0,
            _default = false,
            continuation_statement = false,
            termination_statement = false,
            termination_statement_time = 0,
            notification_statement = "",
            terminated = false
        }



    /* built-in termination of the entire contract system */

    stateful function termination() =
        put(state{terminated = true})

    function check_termination() =
        require(!state.terminated, "contract system terminated before")

    /* built-in safe transfer */

    stateful function transfer(to : address, amount : int) =
        Chain.spend(to, amount)

    /* built-in send message */

    function send(to : address, message : string) =
        Chain.event(Message(Call.caller, to, message))

    /* built-in caller assertion */

    function permit(authorized : address) =
        require(Call.caller == authorized, "access")


    /* Certify clause */

    /*
     |  Clause: Certify.
     |  The Filing Office may certify the File Number.
     */

    stateful entrypoint certify(file_number : string) =
        check_termination()
        permit(state.filing_office)
        put(state{file_number = file_number})


    /* Set File Date clause */

    /*
     |  Clause: Set File Date.
     |  The Filing Office may fix the Initial Statement Date as the current time.
     */

    stateful entrypoint set_file_date() =
        check_termination()
        permit(state.filing_office)
        put(state{initial_statement_date = Chain.timestamp})


    /* Set Lapse clause */

    /*
     |  Clause: Set Lapse.
     |  The Filing Office may fix the Lapse Date.
     */

    stateful entrypoint set_lapse(lapse_date : int) =
        check_termination()
        permit(state.filing_office)
        put(state{lapse_date = lapse_date})


    /* Set Continuation Start clause */

    /*
     |  Clause: Set Continuation Start.
     |  The Filing Office may fix the Continuation Window Start.
     */

    stateful entrypoint set_continuation_start(continuation_window_start : int) =
        check_termination()
        permit(state.filing_office)
        put(state{continuation_window_start = continuation_window_start})


    /* Pay Fee clause */

    /*
     |  Clause: Pay Fee.
     |  The Secured Party may pay a Reminder Fee into escrow.
     */

    stateful payable entrypoint pay_fee() =
        check_termination()
        permit(state.secured_party)
        put(state{reminder_fee = state.reminder_fee + Call.value})


    /* Notice clause */

    /*
     |  Clause: Notice.
     |  The Filing Office may fix the Notification Statement.
     */

    stateful entrypoint notice(notification_statement : string) =
        check_termination()
        permit(state.filing_office)
        put(state{notification_statement = notification_statement})


    /* Notify clause */

    /*
     |  Clause: Notify.
     |  The Filing Office may, if the Continuation Window Start has passed, send the Notification Statement to the Secured Party.
     */

    entrypoint notify() =
        check_termination()
        permit(state.filing_office)
        if(state.continuation_window_start =< Chain.timestamp)
            send(state.secured_party, state.notification_statement)


    /* Pay Escrow In clause */

    /*
     |  Clause: Pay Escrow In.
     |  The Debtor may pay the Digital Asset Collateral into escrow.
     */

    stateful payable entrypoint pay_escrow_in() =
        check_termination()
        permit(state.debtor)
        put(state{digital_asset_collateral = state.digital_asset_collateral + Call.value})


    /* Fail to Pay clause */

    /*
     |  Clause: Fail to Pay.
     |  The Secured Party may declare Default.
     */

    stateful entrypoint fail_to_pay() =
        check_termination()
        permit(state.secured_party)
        put(state{_default = true})


    /* Take Possession clause */

    /*
     |  Clause: Take Possession.
     |  The Filing Office may, if Default is declared, pay the Digital Asset Collateral to the Secured Party.
     */

    stateful entrypoint take_possession() =
        check_termination()
        permit(state.filing_office)
        if(state._default)
            transfer(state.secured_party, state.digital_asset_collateral)


    /* File Continuation clause */

    /*
     |  Clause: File Continuation.
     |  The Secured Party may file the Continuation Statement.
     */

    stateful entrypoint file_continuation(continuation_statement : bool) =
        check_termination()
        permit(state.secured_party)
        put(state{continuation_statement = continuation_statement})


    /* Set Continuation Lapse clause */

    /*
     |  Clause: Set Continuation Lapse.
     |  The Filing Office may, if the Continuation Statement is filed, fix the Continuation Statement Date.
     */

    stateful entrypoint set_continuation_lapse(continuation_statement_date : int) =
        check_termination()
        permit(state.filing_office)
        if(state.continuation_statement)
            put(state{continuation_statement_date = continuation_statement_date})


    /* File Termination clause */

    /*
     |  Clause: File Termination.
     |  The Secured Party may file a Termination Statement, and certify the Termination Statement Time as the then current time.
     */

    stateful entrypoint file_termination(termination_statement : bool) =
        check_termination()
        permit(state.secured_party)
        put(state{termination_statement = termination_statement})
        put(state{termination_statement_time = Chain.timestamp})


    /* Release Escrow clause */

    /*
     |  Clause: Release Escrow.
     |  The Filing Office may, if the Termination Statement is filed, return the Digital Asset Collateral to the Debtor.
     */

    stateful entrypoint release_escrow() =
        check_termination()
        permit(state.filing_office)
        if(state.termination_statement)
            transfer(state.debtor, state.digital_asset_collateral)


    /* Release Reminder Fee clause */

    /*
     |  Clause: Release Reminder Fee.
     |  The Filing Office may, if the Termination Statement is filed, return the Reminder Fee to the Secured Party.
     */

    stateful entrypoint release_reminder_fee() =
        check_termination()
        permit(state.filing_office)
        if(state.termination_statement)
            transfer(state.secured_party, state.reminder_fee)


    /* Termination Period clause */

    /*
     |  Clause: Termination Period.
     |  "Termination Period" is defined as 365 days after the Termination Statement Time.
     */

    entrypoint termination_period() =
        (state.termination_statement_time + (365 * 86400000))


    /* Terminate and Clear clause */

    /*
     |  Clause: Terminate and Clear.
     |  The Filing Office may, if the Termination Period has passed, terminate this contract.
     */

    stateful entrypoint terminate_and_clear() =
        check_termination()
        permit(state.filing_office)
        if(termination_period() =< Chain.timestamp)
            termination()

/* end */
